### ISSUE TITLE
move region_group to assessment schema

### ISSUE THREAD

**Issue by minotogna** [openforis/fra-platform#1028]
- [x] move tables region and region_group to _legacy schema
- [x] create table public.region 
region_code  text not null
        constraint region_pkey
            primary key,
    name         text
- [x] insert into  public.region (region_code, name)  values from _legacy.region
- [x] add table assessment_${name}.region_group
    id      integer not null
        constraint region_group_pkey
            primary key,
    name    varchar not null,
    "order" integer not null
- [x] rename assessment_${name}.assessment_country to assessment_${name}.country and 
assessment_${name}.assessment_region to assessment_${name}.region
- [x] to table  assessment_${name}.region add column region_group_id references assessment_${name}.region_group and make unique region_code + region_group_id

**Comment by sorja** [comment]
Resolved in commit
https://github.com/openforis/fra-platform/pull/1024/commits/4f3549af719ab6327757f269e8f133848438b741
