### ISSUE TITLE
Upgrade Production Postgres DB

### ISSUE THREAD

**Issue by sorja** [openforis/fra-platform#1065]
https://www.postgresql.org/docs/current/release.html
https://www.postgresql.org/support/versioning/
<html><body>

Version | Current minor | Supported | First Release | Final Release
-- | -- | -- | -- | --
14 | 14.1 | Yes | September 30, 2021 | November 12, 2026
13 | 13.5 | Yes | September 24, 2020 | November 13, 2025
12 | 12.9 | Yes | October 3, 2019 | November 14, 2024
11 | 11.14 | Yes | October 18, 2018 | November 9, 2023
10 | 10.19 | Yes | October 5, 2017 | November 10, 2022
9.6 | 9.6.24 | <strong>No </strong>| September 29, 2016 | <strong>November 11, 2021</strong>

</body>
</html>

**Comment by minotogna** [comment]
upgrade to version 13 on Heroku: https://devcenter.heroku.com/articles/upgrading-heroku-postgres-databases

**Comment by minotogna** [comment]
production postgres version is now 14.6
