### ISSUE TITLE
migrate to react router v6

### ISSUE THREAD

**Issue by minotogna** [openforis/fra-platform#1148]
- [x] update locally react-router with ```yarn upgrade-interactive --latest```
- [ ] follow the upgrade instructions:
https://reactrouter.com/docs/en/v6/upgrading/v5 to refactor the code to use new components

**Comment by sorja** [comment]
client/pages/Assessment/Assessment.tsx
client/pages/AssessmentHome/FraHome/FraHome.tsx
client/pages/PageRoutes/PageRoutes.tsx
client/pages/OriginalDataPoint/components/OriginalData/OriginalData.tsx
