### ISSUE TITLE
CanView/Edit Middleware and Hook

### ISSUE THREAD

**Issue by minotogna** [openforis/fra-platform#1169]
- [x] Create hook in frontend useCanEdit
- [x] Add Server Api middleware canEdit/canView
- [ ] When loading ODP page, fetch section 'extentOfForest' add it to the store.
- [ ] When leaving ODP page, remove from store  'extentOfForest'.

NOTE: use 'extentOfForest' hardcoded to check if user can edit ODP

**Comment by sorja** [comment]
we can for now add useCurrentSection hook param (section: string) which returns this section instead of url param section
