### ISSUE TITLE
Access to any section: Could not serve - userNotAuthorized

### ISSUE THREAD

**Issue by minotogna** [openforis/fra-platform#1209]
- [x] accessing any section, e.g. https://fra-platform-incubator.herokuapp.com/AFG/assessments/fra/2020/
gives error userNotAuthorized 
<img width="1440" alt="Screenshot 2022-03-21 at 07 23 48" src="https://user-images.githubusercontent.com/1138156/159219190-58633cc4-7fd5-4301-bbc0-9e21e9c08289.png">

- [x] fetch sections from 2020 default cycle!  **xhr.js:210          GET https://fra-platform-incubator.herokuapp.com/api/assessment/fra/sections/2025 500 (Internal Server Error)**

- [x] **GET https://fra-platform-incubator.herokuapp.com/api/country/AFG/assessments/fra/cycles/2020/status 503 (Service Unavailable)**

**Comment by sorja** [comment]
Access right issues ssue resolved by reading also query params (previously in url params)

**Comment by sorja** [comment]
Note:
canView requires 'tableName' param which `getSections`, `getCountryStatus` don't have or use; requireView middleware removed from these until resolved
