### ISSUE TITLE
Table 1a: Hide/Show original data point

### ISSUE THREAD

**Issue by minotogna** [openforis/fra-platform#1210]
- [x] in store pages->assessmentSection add showOrigianlDataPoint boolean , default true 
- [x] In table 1a: When user is admin, add button Show/Hide original data points to show / hide original data points 

### (show show is true)
<img width="1057" alt="Screenshot 2022-03-21 at 07 28 26" src="https://user-images.githubusercontent.com/1138156/159219599-eca294db-7d0e-41c8-aa5b-165762f8ee1f.png">

### (when show is false)
<img width="1093" alt="Screenshot 2022-03-21 at 07 29 40" src="https://user-images.githubusercontent.com/1138156/159219695-0586d6a7-298d-4e0a-9a93-06fc54d5f6f5.png">

**Comment by sorja** [comment]
Implemented with functionality in store (functionality part in useData() -hook)
