### ISSUE TITLE
Table 1b: Use National Data Points

### ISSUE THREAD

**Issue by minotogna** [openforis/fra-platform#1211]
BE
- [x] move assessment country table to cycle schema
- [x] add column config jsonb 
- [x] add endpoint to update use original data point in country config: config contains { forestCharacteristics: {useOriginalDataPoint: boolean } }
- [x] migrate data 

FE
- [x] fetch config together with countries 
- [x] In table 1b add button `use/ don't use OriginalDataPoints` that calls endpoint described above

**Comment by sorja** [comment]
Scope changed a little, see PR #1221
