### ISSUE TITLE
DataExport: handle home countries filer update 

### ISSUE THREAD

**Issue by minotogna** [openforis/fra-platform#1263]
TODO After #1333 

_Originally posted by @minotogna in https://github.com/openforis/fra-platform/pull/1261#discussion_r850264359_

**Comment by rfontanarosa** [comment]
the filter it's already working

<img width="1060" alt="Schermata 2022-06-09 alle 09 17 21" src="https://user-images.githubusercontent.com/10047945/172809043-d4cd5b5c-45da-41d4-bdae-34c4aee7d0a2.png">

<img width="423" alt="Schermata 2022-06-09 alle 09 17 34" src="https://user-images.githubusercontent.com/10047945/172809066-8bb5d70c-8b2e-442b-a6c7-784cd16334e5.png">
