### ISSUE TITLE
ActivityLog to check

### ISSUE THREAD

**Issue by minotogna** [openforis/fra-platform#1506]
provide information to the team about the following activity logs:

nodeValueEstimate = 'nodeValueEstimate',
invitationRemove = 'invitationRemove',
userRemove = 'userRemove',
userUpdate = 'userUpdate',

in particular:
- were they used in old code?
- are they used in new code?
- have they been migrated?

**Comment by sorja** [comment]
`nodeValueEstimate = 'nodeValueEstimate',`
were they used in old code?
previously: generateFraValues
are they used in new code?
yes
have they been migrated?
yes

**Comment by sorja** [comment]
`invitationRemove = 'invitationRemove',`
were they used in old code?
yes
are they used in new code?
no, pending implementation (controller)
have they been migrated?
yes

**Comment by sorja** [comment]
`userRemove = 'userRemove',`
were they used in old code?
yes
are they used in new code?
no, because users are public level but activitylog is fra level (discuss in daily)
have they been migrated?
yes

**Comment by sorja** [comment]
`userUpdate = 'userUpdate',`
were they used in old code?
yes
are they used in new code?
no, because users are public level but activitylog is fra level (discuss in daily)
have they been migrated?
yes
