### ISSUE TITLE
Data Table Boolean cell: Allow selecting empty value

### ISSUE THREAD

**Issue by minotogna** [openforis/fra-platform#1516]
OJ: For Booleans, once Yes or No have been selected it is not possible to select blank (empty cell) again

**Comment by sorja** [comment]
<img width="445" alt="image" src="https://user-images.githubusercontent.com/5508251/191048372-e3bb68b2-5f7a-4e2e-a13f-c88c4ef6208a.png">

Unable to replicate, maybe automatically fixed in new version of FRA Platform
