### ISSUE TITLE
Calculation results: round results to 2 digits

### ISSUE THREAD

**Issue by minotogna** [openforis/fra-platform#1518]
OJ: Table 4a, mistake generated when the unknown ownership (4a) is using values from NDP in table 1a. Albania, Azerbaijan, Kazakhstan had a problem with the decimals. The NDP in table 1a generates a number of decimals which are not reflected in table 4a resulting in a very, very tiney negative difference. Had to add zeros manually in the sheet “Data”  (SEE ALBANIA: FIX: Round final calculation results)

**Comment by minotogna** [comment]
Would it work to round before formatting in src/client/pages/AssessmentSection/DataTable/Table/Row/RowData/Cell/Calculated/Calculated.tsx ?

**Comment by sorja** [comment]
I tried messing around a bit here, but I think the "root" issue is still unresolved.

We have currently:
`const value = nodeValue.raw ? Numbers.format(Number(nodeValue.raw), row.props?.format?.integer ? 0 : 2) : ''`

Even this gives the same result:
`Math.round((Number(nodeValue.raw) + Number.EPSILON) * 100) / 100`

https://stackoverflow.com/questions/7223359/are-0-and-0-the-same


We could fix it with a regex replace? As this is only for showing a string (here: -0)

**Comment by minotogna** [comment]
In Numbers.format, could we check if rounded number is -0 then consider it 0?
