### ISSUE TITLE
data inconstency table 2b growingStockComposition

### ISSUE THREAD

**Issue by sorja** [openforis/fra-platform#1521]
Remaining introduced tree species
`remaining_introduced_placeholder`

https://fra-data.fao.org/TZA/fra2020/growingStockComposition/

<img width="1682" alt="image" src="https://user-images.githubusercontent.com/5508251/190661092-627fde34-4fcd-46ee-b93b-832f4a5cd84e.png">

http://localhost:9000/TZA/assessments/fra/2020/growingStockComposition

<img width="1662" alt="Screenshot 2022-09-16 at 16 19 15" src="https://user-images.githubusercontent.com/5508251/190660980-d99b2f4b-e6b1-4bde-9196-75817535dc24.png">

Possibly affects:
`TZA,totalIntroduced,2015,"{""raw"": ""26.52"", ""calculated"": true}"`

**Comment by minotogna** [comment]
Is this related the data comparison ?
Open only one final issue , and move it to the project board

**Comment by sorja** [comment]
It is related to data migration (issue)

**Comment by minotogna** [comment]
this issue has been resolved in #1512
