### ISSUE TITLE
Descriptions/National Data/Data sources: structured data

### ISSUE THREAD

**Issue by minotogna** [openforis/fra-platform#1544]
- [x] update Descriptions (CommentableDescription) type and db table: rename content property to value and db type jsonb and ts type is {text:string,dataSources?:Array<DataSource>} where DataSource = {reference:string,type:string,fraVariable:string,year:string,comments:string}
- [x] update data migration to migrate current content into value ({text})
- [x] FE/BE update how data source is saved and fetched with new format 
- [x] in Descriptions/National Data/Data sources, before current text editor, render table  to show/edit data sources as follow:

**Reference to data source  | Type of data source | FRA variable | Year for data source | Comments** ( + )

**in edit mode, render edit fields as :**
reference: vertically growing text input
type: select [values from data source types]
fraVariable: select [take rows from first table of first table section where row.props.variableName is not null and row.props.type = data] - even store rowUuid in data 
year: select [tale table.props.columnNames]
 comments: vertically growing text input

**data source types:**
National Forest Inventory (NFI)
Remote sensing based assessment with ground truthing
Statistical remote sensing survey with accuracy assessment
Remote sensing based assessment without ground truthing
Vegetation mapping
Registers and statistics

// data source types managements
in meta/descriptions export an array of strings (keys)
add translations in descriptions.dataSources.{key}
 
 
 
 
 - [x] Add comment button for each row

**Comment by sorja** [comment]
Blocked by #1611
