### ISSUE TITLE
Do not reload page after logout

### ISSUE THREAD

**Issue by minotogna** [openforis/fra-platform#1569]

**Comment by rfontanarosa** [comment]
but now the page is not reloaded: logout.fulfilled, () => initialState

in which case it happens?

**Comment by rfontanarosa** [comment]
can't see this issue on heroku because I don't have a valid user

**Comment by minotogna** [comment]
I will add you there, but can't you try with local prod build ?

**Comment by minotogna** [comment]
you already have a valid user, just checked

**Comment by minotogna** [comment]
This issue happens when current page is assessment section. 
e.g. https://fra-platform-incubator.herokuapp.com/X20/assessments/fra/2020/otherLandWithTreeCover

**Comment by rfontanarosa** [comment]
this is my local instance. we have to testi it directly on heroku.

https://user-images.githubusercontent.com/10047945/195269965-87829c44-7a2a-4b91-b766-7fb7c7bfb4e5.mov

**Comment by rfontanarosa** [comment]
we are reloading the page only if the user are logging out from a page that an anonymous user can't see.

e.g. an administrator log out from an unpublished cycle

**Comment by minotogna** [comment]
this is not happening anymore.
