### ISSUE TITLE
Invalidate invalid token

### ISSUE THREAD

**Issue by sorja** [openforis/fra-platform#1664]
Issue:
Invalidate invalid token (eg. user not found, expired)

Steps to reproduce:
- After migrate-fra UI shows as logged in
- Trying to edit data shows an error

- Error probably related to token persisting, token should be reset if issue fetching user (eg. writing to activity log)

Correct steps:
- Log in
- Migrate fra
- Logged out

**Comment by minotogna** [comment]
Do you think it's important ?
I would close this

**Comment by sorja** [comment]
It can be closed

The issue is probably deeper in authentication, staying logged in itself is not the issue, but how it is handled


We should check in the requests (eg. initApp) if the user is logged in

**Comment by sorja** [comment]
Current version clears token correctly but does not verify
