### ISSUE TITLE
Table 1a/1b update: ODP or Cell with correspondent ODP

### ISSUE THREAD

**Issue by minotogna** [openforis/fra-platform#1671]
for 1b condition check that use national data point is active 

1. Case ODP Edit: when editing an ODP, node dependents that are an ODP variable should not be updated and validated, all the others yes.
2. Case Node Value (with correspondent ODP year) Edit: when editing a cell that has a correspondent ODP, dependencies that are ODP variables, should be updated, all the other variables should not.

**Comment by sorja** [comment]
Editing eg. table 1a when `Hide national data points` we should check if a ODP exists for this year
If it exists, don't update calculations
