### ISSUE TITLE
Dashboard 2025: Primary forest % of forest area (2020) no data

### ISSUE THREAD

**Issue by minotogna** [openforis/fra-platform#1700]
Tested with FIN

**2025: Primary forest % of forest area (2020) shows no data**

![Image](https://user-images.githubusercontent.com/1138156/201486810-3dedf67e-fad2-4b66-b289-14f2fdef1e84.png)

**2020: Primary forest % of forest area (2020) shows no data**

![Image](https://user-images.githubusercontent.com/1138156/201486873-2c3cbf47-fefc-4134-a2b3-8a310f71af20.png)

**Comment by sorja** [comment]
![image](https://user-images.githubusercontent.com/5508251/201617623-b0568ec5-4c9f-4b7c-b134-5d1caf8074f5.png)


![image](https://user-images.githubusercontent.com/5508251/201617373-24a2b55f-2abe-43f6-ae9b-8cd59eba954d.png)

We dont have primary forest for 2025, what should we show?

**Comment by sorja** [comment]
Primary forest found under table 1b in 2025
