### ISSUE TITLE
Fix invitation email if user exists and doesn't have a role in invited cycle

### ISSUE THREAD

**Issue by minotogna** [openforis/fra-platform#1726]

**Comment by rfontanarosa** [comment]
I was able to invite a new user and an existing user and the mail have been sent correctly

<img width="1418" alt="Screenshot 2022-11-22 alle 08 58 37" src="https://user-images.githubusercontent.com/10047945/203257625-860ce954-eded-4a66-9ab3-0df8075aaa0e.png">

**Comment by minotogna** [comment]
unable to replicate
