### ISSUE TITLE
1a calculation not executed

### ISSUE THREAD

**Issue by minotogna** [openforis/fra-platform#1734]
editing a and/or b should update calculated rows. tested in fin 2025

![Image](https://user-images.githubusercontent.com/1138156/203284806-3ea7d4d7-f4cd-484e-9fc8-0eae92ede61d.png)

**Comment by sorja** [comment]
Issue related most likely to Total land area (c) not migrated to column 2025
variable: Remaining land area is calculated with (missing) c - a - b

```
[
  {
    "country_iso": "FIN",
    "variable_name": "totalLandArea",
    "col_name": "2025",
    "value": "{\"raw\": null}"
  }
]
```


Migration should probably be 2025 = 2020 value


Demo when DB updated:

https://user-images.githubusercontent.com/5508251/203347008-2c05d164-cbb9-4935-a12f-114892216e69.mov
