### ISSUE TITLE
GEO: Add functionality to load agreement layer

### ISSUE THREAD

**Issue by minotogna** [openforis/fra-platform#1740]
similar api call as for forest layers. Input parameters for this call are selected layers (minimum of 2 layers) and level of agreement. Instead of 'Display' button we agreed that another layer check box would be added below 'Choose agreement level between all map layers'

**Comment by joonasnuutinen** [comment]
Example: `/api/geo/layers/forestAgreement/?countryIso=FIN&layer=JAXA&layer=TandemX&gteAgreementLevel=2`

**Comment by joonasnuutinen** [comment]
~~There's a [draft PR](https://github.com/openforis/fra-platform/pull/1582) related to this. Can it be used as a base?~~ EDIT: I decided to use it.

**Comment by joonasnuutinen** [comment]
PR: #1582
