### ISSUE TITLE
GEO: Add functionality to be able to filter the agreement layer

### ISSUE THREAD

**Issue by minotogna** [openforis/fra-platform#1741]
(the boxes on the mockup). Minimum level is one (only one layer says there is forest), maximum is number of layers selected (all the layers agree there is forest). This call to filter the agreement layer is the same as to load the layer but with a different agreement level as param

**Comment by joonasnuutinen** [comment]
Additional requirement from #1740:

> Instead of 'Display' button we agreed that another layer check box would be added below 'Choose agreement level between all map layers'
