### ISSUE TITLE
GEO FE: Statistics

### ISSUE THREAD

**Issue by minotogna** [openforis/fra-platform#1746]
Load column chart / table with area estimations calculated for each forest product. This should be easy as you are already rendering a lot of tables and charts on the platform.

https://xd.adobe.com/view/dfbd3ca3-74e1-49e7-92da-73d5e39bf12f-8aee/screen/791d9abd-1260-404c-bed5-32e53d0312a4

**Comment by eraviolo** [comment]
Reference for Forest Area Extent


![Image](https://user-images.githubusercontent.com/15015525/203377698-9614adfd-685b-418d-88d1-258f799dbe92.png)

To retrieve estimations query endoint:
api/geo/estimations/forest/?countryIso=country_iso&year=2020

For each forest product, the name of the property to query the estimated area can be found on src/meta/geo/forestEstimations.ts (forestAreaDataProperty under sourcesMetadata)
