### ISSUE TITLE
Separate user roles and jwt token

### ISSUE THREAD

**Issue by rfontanarosa** [openforis/fra-platform#1762]
Users assigned to various countries can't login due the following problem:

`xhr.js:210 Set-Cookie header is ignored in response from url: http://localhost:9000/auth/login. The combined size of the name and value must be less than or equal to 4096 characters.`

**Comment by minotogna** [comment]
- [ ] BE: Remove user roles from token generation 
- [ ] BE: add in a middleware req.user (integrate with passport if possible , or custom middleware)
- [ ] BE: init endpoint : get user from db not from cookie
