### ISSUE TITLE
Table 7c rendering issue

### ISSUE THREAD

**Issue by AnssiSamuli** [openforis/fra-platform#1786]
https://fra-data.fao.org/AUT/fra2020/nonWoodForestProductsRemovals/

![image](https://user-images.githubusercontent.com/1213245/205069870-1ceda0c7-e9d1-4f7e-8905-0091e8133cb0.png)

**Comment by minotogna** [comment]
Still present in current version . https://fra-data.review.fao.org/AUT/assessments/fra/2020/nonWoodForestProductsRemovals
