### ISSUE TITLE
User access rights with pending invitation

### ISSUE THREAD

**Issue by minotogna** [openforis/fra-platform#1794]
How is it possible that a User (user with Role  Atlantis01 NC 2020, and with pending invitation for Atlantis01 NC 2025) has access to 2025 Atlantis01 ?

**Comment by sorja** [comment]
fixed in #1796

**Comment by sorja** [comment]
previously non-accepted roles were counted as roles, resulting in the possibility to view invited cycles (eg. 2025 here) even though pending
