### ISSUE TITLE
Admin: User edit: roles by cycle

### ISSUE THREAD

**Issue by minotogna** [openforis/fra-platform#1803]
Add tab bar to choose cycle for roles edit

**Comment by sorja** [comment]
@minotogna 

Is this still valid?

We can change the cycle from cycle selector

**Comment by minotogna** [comment]
> @minotogna 
> 
> Is this still valid?
> 
> We can change the cycle from cycle selector
> 
> 

I don't know @sorja 
This is something we will consider later on
