### ISSUE TITLE
Update FAOSTAT land area 2025 values

### ISSUE THREAD

**Issue by AnssiSamuli** [openforis/fra-platform#1826]
The text under Table 1a says "The FAOSTAT land area figure for the year 2015 is used for all reference years"

Örjan says " ... for total land area we will be using available FAOSTAT data for each year. "

**Comment by sorja** [comment]
[FRA 2025 countries_with imputations.csv](https://github.com/openforis/fra-platform/files/10193207/FRA.2025.countries_with.imputations.csv)

**Comment by minotogna** [comment]
I will rename the issue, since this involves: 
- [ ] update FAOSTAT land area in node table for 2025 cycle for each year using attached CSV file
- [ ] In Cycle 2025 remove text under table "The FAOSTAT land area figure for the year 2015 is used for all reference years"
