### ISSUE TITLE
Table 1a Estimation: Verify all methods are giving correct results

### ISSUE THREAD

**Issue by minotogna** [openforis/fra-platform#1859]

**Comment by sorja** [comment]
Working as expected

Results in production (incubator)

![image](https://user-images.githubusercontent.com/5508251/210321125-f28891b0-bd48-4221-a181-951a359c2426.png)
![image](https://user-images.githubusercontent.com/5508251/210321139-6ed0066f-d817-43d2-a405-ef45ff2fcc83.png)
![image](https://user-images.githubusercontent.com/5508251/210321154-36f1eec0-16e3-4098-a0e0-e55312098e93.png)
![image](https://user-images.githubusercontent.com/5508251/210321163-1f186b99-840b-463e-b7f5-c4eeddbf4f02.png)
![image](https://user-images.githubusercontent.com/5508251/210321179-66553a29-416f-41a9-8e2f-030c8acd7715.png)
![image](https://user-images.githubusercontent.com/5508251/210321193-1d1f1f2c-db73-41b9-b068-640f9ee85c7f.png)

![image](https://user-images.githubusercontent.com/5508251/210321254-cea1f95a-6692-4778-9db9-6f3a6dbc88a6.png)
![image](https://user-images.githubusercontent.com/5508251/210321259-62cb1ba8-8192-41ec-a8a1-058c5ab66898.png)
![image](https://user-images.githubusercontent.com/5508251/210321268-652c8293-e94e-4c5b-a9eb-55819785046c.png)
![image](https://user-images.githubusercontent.com/5508251/210321279-84d565e6-fefa-46db-b04b-13f4f14501b4.png)
![image](https://user-images.githubusercontent.com/5508251/210321288-814c3a9d-db8a-44c9-b2a0-0f123ee79033.png)
![image](https://user-images.githubusercontent.com/5508251/210321303-8c4e4e09-59e7-4a50-9386-2afcc39e35d6.png)
![image](https://user-images.githubusercontent.com/5508251/210321331-3a439450-497e-477e-9b84-63ce062d25af.png)


TODO
Update unit tests
