### ISSUE TITLE
Geo: agreement layer selection show level colors

### ISSUE THREAD

**Issue by minotogna** [openforis/fra-platform#1890]

**Comment by joonasnuutinen** [comment]
@eraviolo I need more details.

**Example 1**

Request:
`/api/geo/layers/forestAgreement/?countryIso=FIN&layer=JAXA&layer=TandemX&layer=GlobeLand&layer=ESAGlobCover&layer=Copernicus&layer=ESRI&layer=ESAWorldCover&gteAgreementLevel=3`

Response:
```
{
  mapId: "projects/earthengine-legacy/maps/ea2e1aa6cbfd4f7b435a4e3ee76ffdf5-0ac9f9d1d85ad7da42530910b54bdf7f",
  palette: [
    "#FF8000",
    "#FFFF00",
    "#01def9",
    "#0040FF",
    "#01DF01"
  ]
}
```

**Example 2**

Request:
`/api/geo/layers/forestAgreement/?countryIso=FIN&layer=JAXA&layer=TandemX&layer=GlobeLand&layer=ESAGlobCover&layer=Copernicus&layer=ESRI&layer=ESAWorldCover&gteAgreementLevel=7`

Response:
```
{
  mapId: "projects/earthengine-legacy/maps/61419160f14a67e1a2b90fcf02d82fea-db23c2f6d82084aec75602fda6381567",
  palette: [
    "#01DF01"
  ]
}
```

**Questions**

1. In Example 1, I have 7 layers and an agreement level 3. I get a palette of 5 colors. What do these colors refer to? I.e. where in the UI should each color show up?
2. In Example 2, I have 7 layers and an agreement level 7. I get a palette of 1 color. What does this color refer to? I.e. where in the UI should the color show up?
3. In general, what is the size of the palette based on and where should the colors be mapped?

**Comment by eraviolo** [comment]
1. There are 7 input layers and the agreement image is filtered to return only the places where the agreement level is greater or equal to 3, so it will return the image filtered with values >= 3, in this case, values will be 3, 4, 5, 6 or 7. The 5 colors correspond to those values on the image.
2.  Same input as example 1 but here the image is filtered with values >= 7 (meaning all input layers agree). In this case, the only possible value returned is 7 and the color returned corresponds to that level of agreement (7/7, 100%).
3. The size of the palette corresponds with all the levels of agreement shown in the returned layer. We have a fixed base list of colors for the agreement layer, and depending on the agreement level selected, that list is sliced.

In the GEE app we are showing a legend on top of the map. In this case maybe we can use the fixed list of colors to set the background color in the boxes? 

Example for an agreement layer with 7 input layers and agreement level >= 1 
![image](https://user-images.githubusercontent.com/15015525/208435039-81d5426f-dab3-41b3-9204-73eef75a411a.png)

Example for question 1, 7 input layers and agreement level >= 3
![image](https://user-images.githubusercontent.com/15015525/208435313-3e85312b-4609-4cbd-853d-f225b3495147.png)

Example for question 2, 7 input layers and agreement level >= 7
![image](https://user-images.githubusercontent.com/15015525/208436810-3a150fb7-013b-4aaa-80c6-fe6610086657.png)
