### ISSUE TITLE
Rename CSV file downloaded from table data

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#1924]
For sub-sessions(e.g. 8a) with multiple tables, it is possible to download tables one by one now. In case some people want to have all the tables of the designated topic in one CSV file, it would be great to have a download button that allows this function.

One more thing, all the download CSV files for one designated topic have the same name( e.g.8 a), which may cause some issues. We may add the table name in the filename(e.g. _SDG15.1.1;SDG15.2.1.1_... ) or rename them in _8a.1, 8a.2_......in such a manner. @minotogna 

Pics below were screenshots took before the update:
![Feature1](https://user-images.githubusercontent.com/99216009/209187030-33ca0fb4-d10c-4381-8932-2a00882ccb2f.png)
![Feature2](https://user-images.githubusercontent.com/99216009/209187044-3107788a-db0c-43ba-b1d7-18ee496c0059.png)

**Comment by pengchenglai** [comment]
As an improvement, need to discuss if necessary

**Comment by minotogna** [comment]
we can rename the CSV file output for now. 
We can think later of the feature regarding downloading all files together. If user wants to download multiple data, can go to data download section.
renaming the issue accordingly

**Comment by pengchenglai** [comment]
Sounds good. Table 2 c&d csv files of carbon stock calculator also need to be renamed btw.
![4](https://user-images.githubusercontent.com/99216009/210604802-93a21a5e-209e-49f7-9c13-d5937dedafe5.png)

@minotogna

**Comment by minotogna** [comment]
> Sounds good. Table 2d csv files of carbon stock calculator also need to be renamed btw.
> 
> ![4](https://user-images.githubusercontent.com/99216009/210604802-93a21a5e-209e-49f7-9c13-d5937dedafe5.png)
> 
> 
> 
> @minotogna 
> 
> 
> 
> 

What would be an appropriate name @pengchenglai ?

**Comment by pengchenglai** [comment]
> 

Good morning, it makes more clear(for table 2c &d) if we rename it with either _BiomassBoreal, BiomassTemperate ...__ or _BiomassCalculatorBoreal, BiomassCalculatorTemperate ..._ in such a manner. Users can know which climate domain that file refers to. @minotogna

**Comment by minotogna** [comment]
> > 
> 
> 
> 
> Good morning, it makes more clear(for table 2c &d) if we rename it with either _BiomassBoreal, BiomassTemperate ...__ or _BiomassCalculatorBoreal, BiomassCalculatorTemperate ..._ in such a manner. Users can know which climate domain that file refers to. @minotogna 

Ok @pengchenglai !

**Comment by pengchenglai** [comment]
Consider renaming the csv files of Table 1 a with _1a.1_ and _1a.2_
![6](https://user-images.githubusercontent.com/99216009/210972821-42580f53-f81f-4574-a6a3-8d3f10de53d6.PNG)
@minotogna

**Comment by pengchenglai** [comment]
Consider renaming the csv files of Table 1 b with _1b.1_ and _1b.2_
![7](https://user-images.githubusercontent.com/99216009/210973274-46030e73-43ef-4f67-8822-8a0ee384b469.PNG)

**Comment by pengchenglai** [comment]
Same custom for 2 a, c& d;3 a
