### ISSUE TITLE
Table 1a & 1b 2025 prediction error 

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#1943]
Table 1a：In the trend graph, there is no 2025 time point; there is an error when tring to generate values for 2025(values not be shown after the refresh) @minotogna 
![1](https://user-images.githubusercontent.com/99216009/210333118-9880e9f3-3857-4e64-99a3-2337c8084e31.png)
![2](https://user-images.githubusercontent.com/99216009/210333265-a69f165c-623b-489a-879e-899232b2c158.png)

**Comment by pengchenglai** [comment]
Table 1b ：In the trend graph, there is no 2025 time point; the _Generate values_ button does not work
![4](https://user-images.githubusercontent.com/99216009/210340458-39e24920-cbde-414a-b9c4-13955d5a0d33.png)

**Comment by minotogna** [comment]
this is not an issue. architecture server has been updated. please test now.

**Comment by pengchenglai** [comment]
> this is not an issue. architecture server has been updated. please test now.

Table 1a is functional indeed, but the time point 2025 is still missing in table 1b graph and generation value button does not work
![4](https://user-images.githubusercontent.com/99216009/210598129-aa6f46c7-5ec2-4497-8724-0f37579c0fcd.png)
@minotogna
