### ISSUE TITLE
Original Data Point Page: Copy previous values -> Prefill 

### ISSUE THREAD

**Issue by AnssiSamuli** [openforis/fra-platform#1952]
Currently, the add national data point dialogue has a button "copy previous values" next to "National classifications". It functions perfectly, but to me if would be more logical to have this button above the " National Classifications" and change the label to "prefill with [year] previous datat" / or just "prefill" as the button prefills both the classifications, and the data and reclassification sections. The [year] would become the year of prev datapoint.

![image](https://user-images.githubusercontent.com/1213245/210566265-5569810c-aaed-4a9b-a905-4d19f2d5ff42.png)

Just a thought.

**Comment by minotogna** [comment]
To implement 
- [x] Remove Copy previous values button and functionality 
- [x] In edit mode right below Classifications and definitions label: 
  - Add Bold text 'Prefill with ' followed by select with placeholder 'Select year' and options with all odp years available (odp that have classes)
  - followed by primary (blue) button 'Prefill', disabled when year is not selected or prefill action is pending 
  - on click, implement backend integration to populate odp values with data from the selected year
  - on prefill action completed, reset select year.
