### ISSUE TITLE
ENHANCEMENT: Replace N/A with " " in geographical area country pulldown menu

### ISSUE THREAD

**Issue by AnssiSamuli** [openforis/fra-platform#1953]
If an authorized user selects a country for which the user has no role, the system displays N/A next to the country name. That is rather cryptic. Suggest replacing with "no role", "no specific role", " " or similar,  

![image](https://user-images.githubusercontent.com/1213245/210571483-98ffb0fc-9e5e-4f44-9f89-9fca9dd0f066.png)

**Comment by minotogna** [comment]
I think we should just remove N/A and show nothing. would that work for you @AnssiSamuli ?
