### ISSUE TITLE
Credentials(NC etc.) deleted after the platform update

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#1955]
Not sure if it is just a single case, but it happens twice after the new version of the FRA platform was deployed. I cannot log in to the platform as it shows below credential is not recorded in the system.
![1](https://user-images.githubusercontent.com/99216009/210577212-2f28b9a5-f057-4920-96d8-66b71c5c91cc.png)
@minotogna

**Comment by minotogna** [comment]
this is not an issue. it can happen when we are developing new application we need to reset database.
what were your roles @pengchenglai ? I will invite you again.

**Comment by pengchenglai** [comment]
Aha, I see. Could you please invite me(pengcheng.lai@fao.org) as NCs for China and Atlantis 18 @minotogna? Many thanks!

**Comment by minotogna** [comment]
@pengchenglai invited you to both countries

**Comment by pengchenglai** [comment]
> @pengchenglai invited you to both countries

Great, well receipted
