### ISSUE TITLE
ODP Edit: Max Reference year can be Cycle year - 1

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#1956]
In case it has not been mentioned, table 1a national data point does not have choices for 2021, 2022, 2023.....
![1](https://user-images.githubusercontent.com/99216009/210602065-d1761697-2357-4592-a9c1-40c041a37d5c.png)
@minotogna 

Another issue for table 1b refers to the last comment in #1943

**Comment by minotogna** [comment]
it was mentioned, just not scheduled yet. will reuse this issue then @pengchenglai
