### ISSUE TITLE
Table 2c & d (Unit conversion issue & Data entry issues)

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#1958]
If I understand correctly, two tables each for Biomass stock(2c) & Carbon stock(2d) are basically the same with a different unit.

But when you look at the conversion, you will find something is wrong：
e.g. Table 2c 1990 values between these two tables
![1](https://user-images.githubusercontent.com/99216009/210748347-710cb9ff-c5f6-450a-8a3f-374598cb5def.png)
same for table 2d
![2](https://user-images.githubusercontent.com/99216009/210748570-9c5b740c-1395-47ce-b342-1603d4c63109.png)

Double-check with the formula @minotogna

**Comment by pengchenglai** [comment]
Cannot entry data for 2025(table 2c & d), error message(ERR Error running script (call to f_24739165f5bfaa4de7d57a031963021daa07c56f): @user_script:142: @user_script: 142: -OOM command not allowed when used memory > 'maxmemory'.) 
@minotogna 
![3](https://user-images.githubusercontent.com/99216009/210749554-d4958a7a-2320-4a0e-9489-681ab6a6d78e.png)

**Comment by minotogna** [comment]
> If I understand correctly, two tables each for Biomass stock(2c) & Carbon stock(2d) are basically the same with a different unit.
> 
> But when you look at the conversion, you will find something is wrong： e.g. Table 2c 1990 values between these two tables ![1](https://user-images.githubusercontent.com/99216009/210748347-710cb9ff-c5f6-450a-8a3f-374598cb5def.png) same for table 2d ![2](https://user-images.githubusercontent.com/99216009/210748570-9c5b740c-1395-47ce-b342-1603d4c63109.png)
> 
> Double-check with the formula @minotogna

Sorry @pengchenglai what is the problem ?

**Comment by minotogna** [comment]
> Cannot entry data for 2025(table 2c & d), error message(ERR Error running script (call to f_24739165f5bfaa4de7d57a031963021daa07c56f): @user_script:142: @user_script: 142: -OOM command not allowed when used memory > 'maxmemory'.)
> @minotogna
> ![3](https://user-images.githubusercontent.com/99216009/210749554-d4958a7a-2320-4a0e-9489-681ab6a6d78e.png)

@pengchenglai this will be addressed in https://github.com/openforis/fra-platform/issues/1960

**Comment by pengchenglai** [comment]
> > If I understand correctly, two tables each for Biomass stock(2c) & Carbon stock(2d) are basically the same with a different unit.
> > But when you look at the conversion, you will find something is wrong： e.g. Table 2c 1990 values between these two tables ![1](https://user-images.githubusercontent.com/99216009/210748347-710cb9ff-c5f6-450a-8a3f-374598cb5def.png) same for table 2d ![2](https://user-images.githubusercontent.com/99216009/210748570-9c5b740c-1395-47ce-b342-1603d4c63109.png)
> > Double-check with the formula @minotogna
> 
> Sorry @pengchenglai what is the problem ?
 
Maybe I am wrong, but I felt it bit weird
e.g. Table 2d 
The biggest value highlighted with red underscore in the first table has a lowest value in second table
<img width="581" alt="4" src="https://user-images.githubusercontent.com/99216009/210785614-bf8da464-013e-49b4-9537-3eb00fb3c5f5.PNG">
while you can see the conversion of 1 unit is equal across FRA categories(same column) in the following img

<img width="553" alt="5" src="https://user-images.githubusercontent.com/99216009/210785887-386db808-26c3-424d-ba61-47f50ab6e01a.PNG">

e.g. Table 2c
1 unit conversed into different values across column
<img width="778" alt="6" src="https://user-images.githubusercontent.com/99216009/210786302-4ac43ffe-5c85-4b44-9ddb-b586dc3876b1.PNG">

Kindly let me know in case it is unclear @minotogna

**Comment by minotogna** [comment]
> > > If I understand correctly, two tables each for Biomass stock(2c) & Carbon stock(2d) are basically the same with a different unit.
> > > But when you look at the conversion, you will find something is wrong： e.g. Table 2c 1990 values between these two tables ![1](https://user-images.githubusercontent.com/99216009/210748347-710cb9ff-c5f6-450a-8a3f-374598cb5def.png) same for table 2d ![2](https://user-images.githubusercontent.com/99216009/210748570-9c5b740c-1395-47ce-b342-1603d4c63109.png)
> > > Double-check with the formula @minotogna
> > 
> > 
> > Sorry @pengchenglai what is the problem ?
> 
> Maybe I am wrong, but I felt it bit weird e.g. Table 2d The biggest value highlighted with red underscore in the first table has a lowest value in second table <img alt="4" width="581" src="https://user-images.githubusercontent.com/99216009/210785614-bf8da464-013e-49b4-9537-3eb00fb3c5f5.PNG"> while you can see the conversion of 1 unit is equal across FRA categories(same column) in the following img
> 
> <img alt="5" width="553" src="https://user-images.githubusercontent.com/99216009/210785887-386db808-26c3-424d-ba61-47f50ab6e01a.PNG">
> 
> e.g. Table 2c 1 unit conversed into different values across column <img alt="6" width="778" src="https://user-images.githubusercontent.com/99216009/210786302-4ac43ffe-5c85-4b44-9ddb-b586dc3876b1.PNG">
> 
> Kindly let me know in case it is unclear @minotogna

@pengchenglai , please discuss with Örjan this. it's not related to the platform

**Comment by pengchenglai** [comment]
Sure, I will email him @minotogna
