### ISSUE TITLE
BUG: Conflict in user authorization?

### ISSUE THREAD

**Issue by AnssiSamuli** [openforis/fra-platform#1961]
1. Log in as admin
2. Open new tab and copy and paste the address
3. 2nd tab - log out and log in again with **NC** credentials. Now you have two sessions, one as admin and another as NC
4. Navigate to a table in both tabs
5. log out admin
6. navigate to another table as NC
7. you will get a series of "User not authorized" errors

![image](https://user-images.githubusercontent.com/1213245/210770036-193a6ad8-217c-4a1c-978d-21950c7cd32d.png)

**Comment by minotogna** [comment]
@AnssiSamuli This doesn't seem to be a bug, actually the expected behavior. 
user in per session, not per tab. two tabs of the same browser share the same session. 
here what happened : 
1 and 2 user is admin
2,3,4 user is NC
5,6,7 there's no user logged in and since you are accessing 2025 cycle which is not published, but restricted to invited users only, BE api calls give you correctly the error 'user not authorized'.

**Comment by AnssiSamuli** [comment]
Thanks  @minotogna - but why is there no user logged in in 5,6 and 7? I did not log out the NC.

**Comment by minotogna** [comment]
> Thanks @minotogna - but why is there no user logged in in 5,6 and 7? I did not log out the NC.

@AnssiSamuli because you logged out at step 5.
You’re not logging out admin , but last logged user , the NC.
There’s only one user per browser. When you logged in as NC, admin got logged out .
let me know if you need more info

**Comment by AnssiSamuli** [comment]
Many thanks @minotogna! This is clear now. The reason for confusion was the fact that if you log our using tab 2, tab 1 still displays one's status as logged in. It is updated only when one does  a refresh. That is, the error message is displayed on a screen with wrong login status.  See below for an example in which I logged in as NC in two tabs, then logged our from one and am trying to access a table in the first tab. Can we add a functionality that updates the status / change the error message to "user not logged in"?

![image](https://user-images.githubusercontent.com/1213245/211014662-b6e37437-7935-44b0-a7a6-60507c39ede7.png)

**Comment by AnssiSamuli** [comment]
Or, if easier, something like this:

![image](https://user-images.githubusercontent.com/1213245/211016368-a8e5027c-2d4c-4333-a39e-d056bfd6c6ad.png)
