### ISSUE TITLE
ENHANCEMENT - validity check for year in the introduction

### ISSUE THREAD

**Issue by AnssiSamuli** [openforis/fra-platform#1963]
The introduction allows asks for "Expected date/year for next update of the country report" and allows adding a year that is earlier than the current year. This should not be possible.

![image](https://user-images.githubusercontent.com/1213245/210792878-d6e10c11-59fb-4e13-b7e1-9d8deed59cff.png)

**Comment by minotogna** [comment]
@AnssiSamuli , we will add a validation rule, entering wrong value is always allowed.
