### ISSUE TITLE
Data Validations to add / check

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#1964]
Table 1b Add red warning signal for _...of which primary forest_ which should not exceed the value of  _Naturally generating forest(a)_
@minotogna 

<img width="762" alt="1" src="https://user-images.githubusercontent.com/99216009/210795693-ef03a7cc-b618-40b4-9e45-8be6023c9dfc.PNG">

**Comment by pengchenglai** [comment]
Table 1a &b(first and second table) add warning signs for abnormal values

<img width="743" alt="2" src="https://user-images.githubusercontent.com/99216009/210797533-a64b5b1f-a7e1-4032-a2c0-4152a4e0334a.PNG">

<img width="767" alt="3" src="https://user-images.githubusercontent.com/99216009/210801286-5d84794c-1ab1-48c6-8739-5e9790f0f11e.PNG">

**Comment by pengchenglai** [comment]
Table 2b first and second table: Mismatch for _primary forest_ between these two tables should be highlighted
<img width="814" alt="4" src="https://user-images.githubusercontent.com/99216009/210804235-5805784b-a203-49df-b2c2-9cc3c5efeb7f.PNG">

**Comment by pengchenglai** [comment]
Add warnings for abnormal values Table 1c
<img width="730" alt="5" src="https://user-images.githubusercontent.com/99216009/210805366-17924b4d-add9-4e48-a899-dd55e13f3d8d.PNG">

**Comment by pengchenglai** [comment]
Table 1d add warnings for abnormal values;
_a1 +a2_ should equal _a_, again if it is not the case the abnormal values also not being highlighted

<img width="732" alt="6" src="https://user-images.githubusercontent.com/99216009/210806259-117c2b72-c8aa-43d7-9640-3418026e6640.PNG">

**Comment by pengchenglai** [comment]
Table 1e category values should not exceed the _Remaining land area_ ;highlight abnormal values
<img width="725" alt="7" src="https://user-images.githubusercontent.com/99216009/210823642-f3d2cbae-a3f5-4ad3-b688-7bfd76654c53.PNG">

**Comment by minotogna** [comment]
> Table 1a &b(first and second table) add warning signs for abnormal values
> 
> <img alt="2" width="743" src="https://user-images.githubusercontent.com/99216009/210797533-a64b5b1f-a7e1-4032-a2c0-4152a4e0334a.PNG">
> 
> <img alt="3" width="767" src="https://user-images.githubusercontent.com/99216009/210801286-5d84794c-1ab1-48c6-8739-5e9790f0f11e.PNG">

@pengchenglai what do you mean by abnormal values in this case?

**Comment by minotogna** [comment]
- [ ] 1b:  ...of which primary forest which should not exceed the value of Naturally generating forest
- [ ] 2b: Table primary forest by climatic domain table -> all variables should not exceed primary forest (table above)

> Add warnings for abnormal values Table 1c
> <img alt="5" width="730" src="https://user-images.githubusercontent.com/99216009/210805366-17924b4d-add9-4e48-a899-dd55e13f3d8d.PNG">

@pengchenglai what do you mean by abnormal values in this case?

**Comment by minotogna** [comment]
## Validations to add / check 

- [x] 1b:  ...of which primary forest which should not exceed the value of Naturally generating forest
- [x] 2b: Table primary forest by climatic domain table -> all variables should not exceed primary forest (table above)
- [x] 1e: all variables should not exceed the Remaining land area
- [x] 1a climatic domain: Values of Override value in second table in table 1a should <=100; sum = 100.

**Comment by pengchenglai** [comment]
> * [ ]  1b:  ...of which primary forest which should not exceed the value of Naturally generating forest
> * [ ]  2b: Table primary forest by climatic domain table -> all variables should not exceed primary forest (table above)
> 
> > Add warnings for abnormal values Table 1c
> > <img alt="5" width="730" src="https://user-images.githubusercontent.com/99216009/210805366-17924b4d-add9-4e48-a899-dd55e13f3d8d.PNG">
> 
> @pengchenglai what do you mean by abnormal values in this case?

Hi Mino!

For instance, the values for Mangroves are something between 20 to 40 until 2020 and I put 555 for 2025 which is more than 10 times higher than the average for the past period. This value could be 55.5 in reality, but in the current setting, there is no warning.

It would be great to allow the comparison of the values between times and set kinda of sensitivity(threshold needs to be discussed) test, which will pop up warning in case fail @minotogna 

Ps: I think it is a typo _2b_ should be _1b_

**Comment by minotogna** [comment]
> > * [ ]  1b:  ...of which primary forest which should not exceed the value of Naturally generating forest
> 
> > * [ ]  2b: Table primary forest by climatic domain table -> all variables should not exceed primary forest (table above)
> 
> > 
> 
> > > Add warnings for abnormal values Table 1c
> 
> > > <img alt="5" width="730" src="https://user-images.githubusercontent.com/99216009/210805366-17924b4d-add9-4e48-a899-dd55e13f3d8d.PNG">
> 
> > 
> 
> > @pengchenglai what do you mean by abnormal values in this case?
> 
> 
> 
> Hi Mino!
> 
> 
> 
> For instance, the values for Mangroves are something between 20 to 40 until 2020 and I put 555 for 2025 which is more than 10 times higher than the average for the past period. This value could be 55.5 in reality, but in the current setting, there is no warning.
> 
> 
> 
> It would be great to allow the comparison of the values between times and set kinda of sensitivity(threshold needs to be discussed) test, which will pop up warning in case fail @minotogna 
> 
> 
> 
> Ps: I think it is a typo _2b_ should be _1b_
> 
> 

@pengchenglai yes I understand what you mean, but we need clear formulas for the validations . 
You can discuss the details with Örjan and then let me know .
Thank you

**Comment by pengchenglai** [comment]
> > Table 1a &b(first and second table) add warning signs for abnormal values
> > <img alt="2" width="743" src="https://user-images.githubusercontent.com/99216009/210797533-a64b5b1f-a7e1-4032-a2c0-4152a4e0334a.PNG">
> > <img alt="3" width="767" src="https://user-images.githubusercontent.com/99216009/210801286-5d84794c-1ab1-48c6-8739-5e9790f0f11e.PNG">
> 
> @pengchenglai what do you mean by abnormal values in this case?


Similar to the statement above, Forest(a) and Other wooded land(b) should be highlighted for the year 1997 and 2015 in the first table of 1a; the same for first table in 1b.

**Comment by pengchenglai** [comment]
> > > * [ ]   1b:  ...of which primary forest which should not exceed the value of Naturally generating forest
> > 
> > 
> > > * [ ]   2b: Table primary forest by climatic domain table -> all variables should not exceed primary forest (table above)
> > 
> > 
> > > 
> > 
> > 
> > > > Add warnings for abnormal values Table 1c
> > 
> > 
> > > > <img alt="5" width="730" src="https://user-images.githubusercontent.com/99216009/210805366-17924b4d-add9-4e48-a899-dd55e13f3d8d.PNG">
> > 
> > 
> > > 
> > 
> > 
> > > @pengchenglai what do you mean by abnormal values in this case?
> > 
> > 
> > Hi Mino!
> > For instance, the values for Mangroves are something between 20 to 40 until 2020 and I put 555 for 2025 which is more than 10 times higher than the average for the past period. This value could be 55.5 in reality, but in the current setting, there is no warning.
> > It would be great to allow the comparison of the values between times and set kinda of sensitivity(threshold needs to be discussed) test, which will pop up warning in case fail @minotogna
> > Ps: I think it is a typo _2b_ should be _1b_
> 
> @pengchenglai yes I understand what you mean, but we need clear formulas for the validations . You can discuss the details with Örjan and then let me know . Thank you

No worries, will send him an email and Cc you @minotogna

**Comment by pengchenglai** [comment]
Values of _Override value_ in second table in table 1a should <=100; sum = 100. Warning in case not.

![1](https://user-images.githubusercontent.com/99216009/211571663-1bd9e82c-33d2-4496-a6fa-a96d4b1a4926.PNG)
@minotogna
