### ISSUE TITLE
ENHANCEMENT - consistency re the text editor behavior

### ISSUE THREAD

**Issue by AnssiSamuli** [openforis/fra-platform#1965]
When editing a national data point, the default mode of the editor is live code. In addition, the live code is displayed under the text fields as sort of WYSIWYG output.  In the comment section of 1a, the WYSIWYG is missing.

Not sure what the options are, but I think it would be good to have within platform consistency in the way the editor works.

**Comment by minotogna** [comment]
indeed. 
- [x] In ODP view the Comments WYSIWYG editor options must be the same as used in the Descriptions and Comments section page

**Comment by rfontanarosa** [comment]
they already are. it has been fixed meanwhile...


![Image](https://user-images.githubusercontent.com/10047945/228764480-76ad5142-7597-42c5-8eb0-6ba876e316d2.png)

**Comment by minotogna** [comment]
@rfontanarosa I really don't see how they are the same. am I missing something ?

### ODP comments:
<img width="1435" alt="Screenshot 2023-03-30 at 19 18 40" src="https://user-images.githubusercontent.com/1138156/228914964-31f24173-a987-4bef-9149-65d7ce985fb4.png">

### Table 1a comments:
<img width="1612" alt="image" src="https://user-images.githubusercontent.com/1138156/228915106-6e5103d2-0490-4143-8635-74a615d5e26d.png">

**Comment by rfontanarosa** [comment]
sorry, I've got those screenshots from my local instance, and they are the very same. Tomorrow I'll investigate better.
