### ISSUE TITLE
Table 1 d calculation error /enable col level validations

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#1966]
The calculation of _Forest expansion(a)_ - _Deforestation(b)_ is not correct @minotogna 

<img width="529" alt="1" src="https://user-images.githubusercontent.com/99216009/210967866-9b3bc387-8f86-4e71-9991-f9c9cc3aab0b.png">

**Comment by sorja** [comment]
Discussed with Örjan:
- The table currently is showing correct result but can be misleading
- Update:
![image](https://user-images.githubusercontent.com/5508251/212701276-d746a259-3cbe-4715-970f-b3dc0b0a6cbe.png)

**Comment by pengchenglai** [comment]
> Discussed with Örjan:
> 
> * The table currently is showing correct result but can be misleading
> * Update:
>   ![image](https://user-images.githubusercontent.com/5508251/212701276-d746a259-3cbe-4715-970f-b3dc0b0a6cbe.png)

@sorja 
Indeed, would be great to show warnings in case mismatch of _Forest area net change (a-b)_ between this table and table 1a.

Btw, please add warnings in case  _…of which afforestation (a1)_ + _…of which natural expansion (a2)_ not equal to _Forest expansion (a=a1+a2)_
![1](https://user-images.githubusercontent.com/99216009/212711480-612e03df-d500-465c-a426-f037632b778a.PNG)
