### ISSUE TITLE
ODP View: Category 'Other land' must be renamed 'Remaining Land' in cycle 2025

### ISSUE THREAD

**Issue by AnssiSamuli** [openforis/fra-platform#1967]
In ODP view the table 1a title includes remaining land, but remaining land is not displayed in the table

![image](https://user-images.githubusercontent.com/1213245/210815263-efcd4482-b18c-45c0-9356-8c4ca75816f0.png)

**Comment by minotogna** [comment]
@AnssiSamuli Category 'Other land' should be renamed 'Remaining Land' in cycle 2025
