### ISSUE TITLE
BUG - editing ODP table does not change value in table 1a 

### ISSUE THREAD

**Issue by AnssiSamuli** [openforis/fra-platform#1969]
Atlantis 09 2025 - NC changing ODP value for forest in 1970 does not result in updated table 1a. 

![image](https://user-images.githubusercontent.com/1213245/210960213-4f8673f3-6e55-45ce-b963-dfab80b51a45.png)
![image](https://user-images.githubusercontent.com/1213245/210960281-bccda4a8-1fba-4b34-96c9-fee201f756cd.png)

**Comment by minotogna** [comment]
@AnssiSamuli it seems it's working. see video below.
Closing the issue now, but please reopen it in case you notice something wrong

https://user-images.githubusercontent.com/1138156/211552274-0395d40e-5f2b-459b-beb8-d94c93357aeb.mov
