### ISSUE TITLE
Reminder: tabs that are unfunctional  

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#1970]
1. go to add _National data point_ in table 1 a
2. scroll down the page and find _1b Forest Characteristics_
@minotogna 

![1](https://user-images.githubusercontent.com/99216009/210969998-274fd065-43f8-4a7c-96cb-fe1ba2c26a65.png)

**Comment by pengchenglai** [comment]
Table 1b _Gernerate values_
![2](https://user-images.githubusercontent.com/99216009/210970775-7f21e322-b71d-4549-95c1-58932987211c.PNG)

**Comment by minotogna** [comment]
@pengchenglai Data points in table 1b must be enabled by user by clicking 'Use National Data Points' button available during editing

**Comment by pengchenglai** [comment]
> @pengchenglai Data points in table 1b must be enabled by user by clicking 'Use National Data Points' button available during editing

Great, I see how it works. Many thansk:) @minotogna
