### ISSUE TITLE
Common issues in table 1c,d & e

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#1972]
1. Highlight the abnormal values for _Year for data source_;

2. It should not be allowed to finish editing when the compulsory column(e.g. _Type of data source_) has not been filled.
![1](https://user-images.githubusercontent.com/99216009/211002484-0879a934-af24-488a-aa05-89337ca41383.png)

**Comment by minotogna** [comment]
> 1. Highlight the abnormal values for _Year for data source_;
> 
> 
> 
> 2. It should not be allowed to finish editing when the compulsory column(e.g. _Type of data source_) has not been filled.
> 
> ![1](https://user-images.githubusercontent.com/99216009/211002484-0879a934-af24-488a-aa05-89337ca41383.png)
> 
> 

@pengchenglai , system allows entering data not valid .
The real issue is that the validations are missing because we never received instructions about that.
Can you please provide validation rules for each cell ?
E.g. field required , only numbers , max X... etc..
Thank you

**Comment by pengchenglai** [comment]
> > 1. Highlight the abnormal values for _Year for data source_;
> > 2. It should not be allowed to finish editing when the compulsory column(e.g. _Type of data source_) has not been filled.
> > 
> > ![1](https://user-images.githubusercontent.com/99216009/211002484-0879a934-af24-488a-aa05-89337ca41383.png)
> 
> @pengchenglai , system allows entering data not valid . The real issue is that the validations are missing because we never received instructions about that. Can you please provide validation rules for each cell ? E.g. field required , only numbers , max X... etc.. Thank you

No worries, will add up some validation rules soon.

One more question, I do not fully understand why there is another text box under the data entry table as there is a _comment_ column. @minotogna 
![1](https://user-images.githubusercontent.com/99216009/211030564-4be2d71a-83bf-486f-b4a7-56b75d9ac0db.png)
