### ISSUE TITLE
Table 2 series: warning issues

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#1979]
Table 2a _Growing stock m³/ha (over bark)_ : subcategory exceed parent value does not pop up warnings(eg below)
<img width="708" alt="1" src="https://user-images.githubusercontent.com/99216009/211280753-3a5f6df1-0432-42e1-bf29-54cd8740ac3e.PNG">

_Total growing stock (million m³ over bark)_: warnings appear not to be appropriate as the subcategory does not have a value or 0 in this example
<img width="713" alt="2" src="https://user-images.githubusercontent.com/99216009/211280779-b57367a2-2025-4384-a270-88dbd25e3309.PNG">

**Comment by pengchenglai** [comment]
Table 2b _Updated growing stock composition_

Warnings should pop up on the following conditions for the rows in column _% of total_:
1. value of the row below is surpassing the row above
2. Any of the row values surpass 100

<img width="700" alt="3" src="https://user-images.githubusercontent.com/99216009/211335652-1817a5ce-f2ff-4763-a056-a38a21716042.PNG">
@minotogna

**Comment by minotogna** [comment]
@pengchenglai please discuss these with Örjan

**Comment by pengchenglai** [comment]
Not sure which one(or may be all) you refer to, will discuss them tomorrow.

@minotogna
