### ISSUE TITLE
Rename 2020 -> 2025 series

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#1980]
Table 1c _Reclassification into FRA 2020 categories_
<img width="581" alt="1" src="https://user-images.githubusercontent.com/99216009/211282260-300b76c9-fad3-437e-8033-2b9b0473cb5d.PNG">

**Comment by pengchenglai** [comment]
Table 1d _Reclassification into FRA 2020 categories_

**Comment by pengchenglai** [comment]
Table 1e _Reclassification into FRA 2020 categories_

**Comment by pengchenglai** [comment]
Table 2a _Reclassification into FRA 2020 categories_

**Comment by pengchenglai** [comment]
Table 2b,2c,2d,3a,3b,4a,4b,5a,5b _Reclassification into FRA 2020 categories_

**Comment by pengchenglai** [comment]
Table 7 & 7a(currently labelled as 7c)
2020-> 2025
<img width="185" alt="2" src="https://user-images.githubusercontent.com/99216009/211286253-6efcc1cc-3393-4743-b6ca-bf29d1b46546.PNG">

**Comment by pengchenglai** [comment]
Table 6b

In the table
<img width="768" alt="1" src="https://user-images.githubusercontent.com/99216009/211328355-c2a687d8-1a1f-4a5d-82a4-2d0cf1ce39a7.PNG">
@minotogna

**Comment by minotogna** [comment]
@pengchenglai we can fix only last two comments. the rest is user content, we can;'t do much about it

**Comment by pengchenglai** [comment]
> @pengchenglai we can fix only last two comments. the rest is user content, we can;'t do much about it

@minotogna  Just double checked(with the Atlantis), it(_Reclassification into FRA 2020 categories_) seems belong to Html feature

![10](https://user-images.githubusercontent.com/99216009/211623844-5d994de7-2c66-4288-b4ba-d56dc05a457c.PNG)

**Comment by sorja** [comment]
7a label should be correct as is (2020)
Check cycle 2020 (label '2015')

**Comment by pengchenglai** [comment]
> 7a label should be correct as is (2020) Check cycle 2020 (label '2015')

Hi Miro! Thanks for double-checking, it is most likely to be right(2020). I will send an email to Örjan(Cc you) just to be fully sure.

Confirmed it now :)
@sorja
