### ISSUE TITLE
Potential issue National data-remove data source entry boxes

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#1981]
In case someone did not mention it before, the highlighted boxes should be removed for **all** _National Data_ session since we have new feature to enter data source 
<img width="688" alt="1" src="https://user-images.githubusercontent.com/99216009/211284369-3c588915-87f7-46c5-95ea-fb1bc48fc251.PNG">
@minotogna

**Comment by minotogna** [comment]
@pengchenglai this is user entered content. we can't do anything about it. only user can update its own data.

**Comment by pengchenglai** [comment]
Sorry, I didn't write it very clearly properly. I assume that 1(in the following images) is a new feature in FRA 2025. If that is the case, then we have two places 1 and 2 (in the following images) to enter the data source, which may bring users some confusion because they (like me) don't know what to put in 2 since they put data source info in 1 already.

Empty:
![8](https://user-images.githubusercontent.com/99216009/211619512-79e257ac-27fe-4034-a6e0-82f93fdcbbe2.PNG)

With previous data source:
![9](https://user-images.githubusercontent.com/99216009/211619524-a95883a7-9075-4880-bb4a-bcd1204e3f20.PNG)
@minotogna 
 
In case still unclear, we can talk about it tomorrow.
