### ISSUE TITLE
Issues- Table 3a &3c

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#1985]
Current _Total forest area_ in Table 3a(first table) is refilled from Table 1a(see below):
<img width="532" alt="1" src="https://user-images.githubusercontent.com/99216009/211353876-5d2150ba-e488-4a1a-883f-c17d58fa249a.PNG">
 
1._Total forest area_ appears to be wrong for some years(e.g. 0 or nothing), double check the script
2. Not sure why, cannot enter data for _No designation_ and _Unknown_ between 1990 and 2020
3.For the row, add warnings if any of the row values are beyond the values in the _Total forest area_
4.For _Total forest area_, add a warning if _a+...+f_ beyond the values in the Total forest area; add a warning if _a+...+f or a+...+f+ No designation +Unknown_ mismatch the values in the _Total forest area_

<img width="766" alt="2" src="https://user-images.githubusercontent.com/99216009/211354496-14e1b18a-06f0-4b97-8fff-7aa20261dd8c.PNG">

**Comment by pengchenglai** [comment]
Table 3a second table: 
Add warnings for any of the rows beyond the values in the _Total forest area_(table 1a or table 3a first table which does not appear here)
<img width="777" alt="3" src="https://user-images.githubusercontent.com/99216009/211357726-10d8306d-ae08-416f-ba5f-80cb105077d4.PNG">
@minotogna

**Comment by pengchenglai** [comment]
Table 3c(enhancement) 
Condition: select _No_, disable entry for rest of rows
<img width="764" alt="4" src="https://user-images.githubusercontent.com/99216009/211362440-9e057d41-f91e-460d-82ca-f92c8897d3b7.PNG">

**Comment by minotogna** [comment]
@pengchenglai can you please clearly mention the validation rules we should add or which value is wrong?
Please, create a separate issue for last comment

**Comment by pengchenglai** [comment]
> 
Sure, will label the issue in the pic and create an another issue
@minotogna
