### ISSUE TITLE
Issues- Table 4

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#1988]
Table 4a:

1. Add warnings if a subcategory surpasses the parent category in case only one or two subcategory data are available (currently **only** these three rows are filled and sum exceeds the parent the warning will pop up)
2. _Unknow(d)_ is auto-filled with negative values, double check
3. _Total (a+b+c+d)_, if I understand right, should equal _Total forest area_(table 1a). 
![1](https://user-images.githubusercontent.com/99216009/211510623-bfb6d3fc-8c53-49df-b390-4699f34cfcb1.PNG)

Ps:  _Unknow(d)_  and   _Total (a+b+c+d)_ can be updated if re-enter data in one of the three parent categories

**Comment by pengchenglai** [comment]
Table 4b

_Other (specify in comments) (d)_ does not include in the formula, double check 
![2](https://user-images.githubusercontent.com/99216009/211522130-dc1571f0-8c86-4173-93c7-eb484956a200.PNG)
@minotogna

**Comment by minotogna** [comment]
> Table 4b
> 
> _Other (specify in comments) (d)_ does not include in the formula, double check ![2](https://user-images.githubusercontent.com/99216009/211522130-dc1571f0-8c86-4173-93c7-eb484956a200.PNG) @minotogna

@pengchenglai sorry, what formula?

**Comment by pengchenglai** [comment]
> > Table 4b
> > _Other (specify in comments) (d)_ does not include in the formula, double check ![2](https://user-images.githubusercontent.com/99216009/211522130-dc1571f0-8c86-4173-93c7-eb484956a200.PNG) @minotogna
> 
> @pengchenglai sorry, what formula?

If I am right, there is a formula something like _Public Administration (a)_ +...+_Unknown (e)_ =_Total public ownership (a+b+c+d+e)_. 

And it misses _Other (specify in comments) (d)_ in this example which shows _a+b+c+e_=_Total public ownership (a+b+c+d+e)_
![6](https://user-images.githubusercontent.com/99216009/211617363-32444ab3-a0cc-49bd-bc5b-07b0e0b60f6e.PNG)
@minotogna

**Comment by minotogna** [comment]
> > > Table 4b
> > > _Other (specify in comments) (d)_ does not include in the formula, double check ![2](https://user-images.githubusercontent.com/99216009/211522130-dc1571f0-8c86-4173-93c7-eb484956a200.PNG) @minotogna
> > 
> > 
> > @pengchenglai sorry, what formula?
> 
> If I am right, there is a formula something like _Public Administration (a)_ +...+_Unknown (e)_ =_Total public ownership (a+b+c+d+e)_.
> 
> And it misses _Other (specify in comments) (d)_ in this example which shows _a+b+c+e_=_Total public ownership (a+b+c+d+e)_ ![6](https://user-images.githubusercontent.com/99216009/211617363-32444ab3-a0cc-49bd-bc5b-07b0e0b60f6e.PNG) @minotogna

ok @pengchenglai , got it.

**Comment by sorja** [comment]
@pengchenglai table 4b total public ownership references to previous table Public ownership value and it is not calculated in this table

**Comment by pengchenglai** [comment]
> Total public ownership (a+b+c+d+e)

@sorja Fully understand _Total public ownership (a+b+c+d+e)_ value(Table 4b) is fixed and auto-cited from _Public owenership(b)_ value(Table 4a). 

The issue is that _Public Administration (a) +...+Unknown (e)_, from reading the Table 4b, should also equal to _Total public ownership (a+b+c+d+e)_ since it shows this value is summed up all _a_ to _e_ variables in this table. In reality, it is not the case, at least _**Other (specify in comments) (d)**_ is **excluded** and there would **no warnings** for extreme values that exceed the sum(see below).

![1](https://user-images.githubusercontent.com/99216009/212338533-eed1ebe0-aea1-4da5-a6e4-a835944bb4d0.PNG)

**Comment by sorja** [comment]
@pengchenglai 
So is the preferred change:
calculate a+b+c+d+e from table 4b and check that it is equal to 4a value?

**Comment by pengchenglai** [comment]
@sorja 
Or maybe following the mindset from the previous cycle: auto-cite _Public ownership (b)_ value(tab 4a) as Total public ownership (a+b+c+d+e) value(tab 4b); and use this value to deduct a,b...e in case there is a value. 

In the end, _unknown(e)_ is an auto-calculated value that should >=0 like now. Raising a warning, in case the value is below 0(as below).
![1](https://user-images.githubusercontent.com/99216009/212367050-8f0e6e79-11e6-4652-86cc-bffe2e2c9569.PNG)


Kindly let me know if something unclear, many thanks:)

**Comment by sorja** [comment]
@pengchenglai clarified with Örjan:
table 4b is ok as is now
when all fields are empty, unknown = total public ownership

**Comment by pengchenglai** [comment]
@sorja  Good to know it is fine. 
Just a question that _a+b+c+d+e_ could exceed the _Total public ownership_ in the current table as _Other (specify in comments) (d)_ is not included in the equation(highlighted in yellow). Would it be an issue?
![1](https://user-images.githubusercontent.com/99216009/212648350-d4826add-e511-4686-a3b0-7134b016ff78.PNG)
