### ISSUE TITLE
Enhancement- Add button(copy previous data sources)

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#1991]
Add an option “Copy previous data sources” in place(National data-data sources) for all tables 1 to 4.
(1d,1e copied from 1c;2b,2c,2d copied from 2a;3b copied from 3a; 4b copied from 4a)

E.g. The data source of the National data in 2b, 2c, and 2d commonly share the same data source sometimes with additional references.  Adding a button to quote the data source of 2a, namely **Copy previous data sources**.

![1](https://user-images.githubusercontent.com/99216009/211758466-c09c630c-e1f9-4fee-a489-6d658e0027ad.PNG)

@minotogna

**Comment by pengchenglai** [comment]
Having discussed this issue with Örjan last week, would be beneficial to have this feature, which can help users to do less repetitive work.

However, wait for his respond in the coming email.
@minotogna

**Comment by pengchenglai** [comment]
@minotogna 

Not an urgent issue, adding the function when is possible.

**Comment by minotogna** [comment]
@pengchenglai thats what i thought 👍

**Comment by sorja** [comment]
Append copied underneath current if current exists
