### ISSUE TITLE
Table 5c- disable text entry(selection - No)

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#1993]
When users choose _No_ for the questions 
_Has your country a national definition of "Degraded forest"_ and _Does your country monitor area of degraded forest_ (5c first and second table), disable text entry for the following text boxes highlighted in yellow.

![1](https://user-images.githubusercontent.com/99216009/211767243-a5d45961-d722-4c91-bb6f-6717efdf2c82.PNG)
@minotogna

**Comment by minotogna** [comment]
Duplicated from #1992
