### ISSUE TITLE
National data- data sources change content & add a delete button

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#1998]
After discussion, I understand part 2(see below) can be used as references that derived from the previous reporting cycle.

![1](https://user-images.githubusercontent.com/99216009/211859441-9c95f3f9-49bc-4194-a78b-b070ba1278ba.PNG)

However, this also brings a new issue: content could be repetitive(between 1 &2) which may cause some confusion.
![2](https://user-images.githubusercontent.com/99216009/211863318-bfdacb62-d7a5-444d-b8cc-4edb4e03beb0.PNG)

**Comment by pengchenglai** [comment]
One solution would be:①. to replace(hide) the source code with guidance text something like below(meanwhile keep the previous reporting data source but not in an editable status): 

 _The data source(s) on the right was used in FRA 2020 and only showed here as a reference. Please delete it using the button below after finishing the editing._

②. Add a delete(hide) button something like _Delete(Hide) previous data source(s)_ below the previous data 
![3](https://user-images.githubusercontent.com/99216009/211868520-dec6d43b-9667-41d2-889a-d4dcf65d6c94.PNG)
@minotogna

**Comment by minotogna** [comment]
@pengchenglai I understood this was clarified between @sorja and Örjan

**Comment by pengchenglai** [comment]
> @pengchenglai I understood this was clarified between @sorja and Örjan

@minotogna  Indeed
