### ISSUE TITLE
Warning issues-Table 2a total growing stock(million m³ over bark)

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#2002]
1. These three warnings highlighted in yellow(_Subcategory exceeds parent_) do not make sense as the subcategory does not surpass the parent
![1](https://user-images.githubusercontent.com/99216009/212032834-466fb787-8bcc-4e81-b90a-b115c0febb05.PNG)
2. For the above issue, the data validation rule should be(in case there is a parent value): single subcategory value <= the parent; sum of (in case some available not all)subcategory values< the parent; sum of (in case all data available)subcategory values= the parent
![2](https://user-images.githubusercontent.com/99216009/212036941-eda097b5-2228-4fb2-a2f6-427fb9917c51.PNG)

**Comment by pengchenglai** [comment]
3.Another data validation rule: _Total Forest_ should =_Naturally regenerating forest_ +_Planted forest_
![4](https://user-images.githubusercontent.com/99216009/212038576-fbb9d8aa-d7c3-4b2a-b0d7-77dd9d1ed657.PNG)



4.These two warnings highlighted in yellow(_Value should be equal to Total Growing Stock (2a)_) do not make sense as it is the table.
![3](https://user-images.githubusercontent.com/99216009/212037353-b472fa95-0b7b-4ae3-9af5-a38c89f5bf4f.PNG)

**Comment by sorja** [comment]
Blocked by #2047

**Comment by pengchenglai** [comment]
Blocked by #2044

**Comment by pengchenglai** [comment]
@sorja 
Visualized validation rules for Table 2a second table

<img width="745" alt="1" src="https://user-images.githubusercontent.com/99216009/213496265-b5ff2047-15bc-4444-854d-190b77fd019c.PNG">
