### ISSUE TITLE
Table 7a- Total calculation is disabled

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#2005]
_Total_ is in bold which perhaps means it is an auto-calculated value(the cell does not allow to enter data). However, it does not work(sum up the values in the column).

<img width="761" alt="1" src="https://user-images.githubusercontent.com/99216009/212132691-cc01c1a8-f051-4ac7-b436-bff876a55f5d.PNG">
@minotogna

**Comment by sorja** [comment]
Issue in generating assessment meta cache:

![Image](https://user-images.githubusercontent.com/5508251/212900070-a00306ee-9715-4967-a5b0-22f6860c8dd6.png)
