### ISSUE TITLE
BUG- status change email(only read by people from the current cycle)

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#2035]
@minotogna 
Status change emails can **only** be read by people(NCs, collaborators, etc...) of the ****current** cycle**, **not including** the previous cycle(s).
<img width="550" alt="1" src="https://user-images.githubusercontent.com/99216009/213153846-1866a968-2cf1-4e92-b3c9-e2dce7b7a13f.PNG">

e.g. People from last reporting cycle(2020) can also receive the status change email for this cycle(2025).

**Comment by sorja** [comment]
**Add list of recipients**

![image](https://user-images.githubusercontent.com/5508251/213461676-dfb72b52-c322-45fa-ad46-9ea5a9ac501d.png)
