### ISSUE TITLE
Add one more country status 

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#2046]
_Country status_#1911:
After admin approved the country reporting data, the status should change from something like  **Approved** to **Waiting for country validation**
@minotogna @sorja

**Comment by minotogna** [comment]
> _Country status_#1911:
> 
> After admin approved the country reporting data, the status should change from something like  **Approved** to **Waiting for country validation**
> 
> @minotogna @sorja 

@pengchenglai if it doesn't it's a bug we'll fix.

**Comment by pengchenglai** [comment]
> > _Country status_#1911:
> > After admin approved the country reporting data, the status should change from something like  **Approved** to **Waiting for country validation**
> > @minotogna @sorja
> 
> @pengchenglai if it doesn't it's a bug we'll fix.

@minotogna 
Great, discussed with Örjan and Miro about it yesterday which is missing in the country status list

**Comment by minotogna** [comment]
at the moment the workflow is editing->review->Awaiting approval->Approved
where exactly should waiting for country validation should fit? and who has the rights to update the status from awaiting for country validation?

Closing this issue, until further clarification.
