### ISSUE TITLE
Merge table 2a/c/d tables in the reporting process 

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#2047]
@minotogna @sorja 
Merge table 2a growing stock tables into one table(with options to switch units)
<img width="782" alt="1" src="https://user-images.githubusercontent.com/99216009/213449950-2ad76576-04da-46e3-897b-770fe793f4b7.PNG">

PS: ****Keep** these two tables in the final country report**

**Comment by sorja** [comment]
See unit switching from data export

**Comment by minotogna** [comment]
@pengchenglai This is something that doesn't help users to realize there are two tables .
I wouldn't do that .
Did you agree with Örjan this feature ?

**Comment by pengchenglai** [comment]
> @pengchenglai This is something that doesn't help users to realize there are two tables . I wouldn't do that . Did you agree with Örjan this feature ?

@minotogna @sorja 

Örjan agrees this implementation, of which Miro proposed it and he can also explain it to you.

In fact, it is a sort of high priority issue after the discussion as current setting is bit confusing.

There would be **only one** table for users when they **reporting**(with the option of choosing unit as Miro' comment above).
But notice we need to **keep these two tables** when **generating** data for **country report** that public will see it later on.

Kindly let me know if I need open a new issue or you can reopen this issue

**Comment by minotogna** [comment]
> > @pengchenglai This is something that doesn't help users to realize there are two tables . I wouldn't do that . Did you agree with Örjan this feature ?
> 
> 
> 
> @minotogna @sorja 
> 
> 
> 
> Örjan agrees this implementation, of which Miro proposed it and he can also explain it to you.
> 
> 
> 
> In fact, it is a sort of high priority issue after the discussion as current setting is bit confusing.
> 
> 
> 
> There would be **only one** table for users when they **reporting**(with the option of choosing unit as Miro' comment above).
> 
> But notice we need to **keep these two tables** when **generating** data for **country report** that public will see it later on.
> 
> 
> 
> Kindly let me know if I need open a new issue or you can reopen this issue
> 
> 

Ok @pengchenglai thanks for the clarification . I'll reopen the issue

**Comment by pengchenglai** [comment]
@minotogna @sorja 
Applied same feature for table 2c(**Biomass stock**) /2d(**Carbon stock**) since they are the same table with different unit as well.
![1](https://user-images.githubusercontent.com/99216009/217296929-88ce30a8-4a51-4b1f-8d8e-be740545dea3.PNG)

**Comment by minotogna** [comment]
@pengchenglai @sorja @rfontanarosa 
Proposed solution:

- [ ] Add collapsable feature that is persisted at country level 

would that work ?

**Comment by pengchenglai** [comment]
@minotogna 

Not sure how it would work. Possible to show an example(a screenshort or a video clip)?

**Comment by minotogna** [comment]
@pengchenglai something like this:


![Image](https://user-images.githubusercontent.com/1138156/228864040-68825bc6-3352-4915-9e96-0a5d67e5587f.png)

with title is the Table header and content is the table, when expanded is visible.

**Comment by minotogna** [comment]
We'll basically add an arrow before the table header label

**Comment by pengchenglai** [comment]
@minotogna 
I think Orjan want the arrow behind the table header label where users can switch the units. 

So between two units the table basically look the same and data will convert into another unit by clicking the arrow and choosing the another unit once user have put data for one unit of the table.

**Comment by minotogna** [comment]
@pengchenglai what is 'behind the table' for you? 😅thank you

**Comment by pengchenglai** [comment]
@minotogna 
This is how it currently looks, using the biomass table (2c) as an example:

![1](https://user-images.githubusercontent.com/99216009/235863551-cb508356-f737-4948-865d-9b7a9e81eb44.JPG)


Ideally, there should only be one table (named 'new table') instead of two (named 'original tables'), since we know that the original tables are basically the same but with different units and column headers.

The new table should look like this, with a scrolling down menu (SD menu) behind the table header label:
![2](https://user-images.githubusercontent.com/99216009/235863597-6878d1bf-ac4a-45eb-8b4f-d2ec5c36b218.JPG)



There should be two options available in this case: 1) forest carbon (tonnes/ha) and 2) total forest carbon (million tonnes) for SD menu. However, the validation for each option should remain the same. In other words, we are only changing the way the table is presented; the structure and validation remain the same and if one option is filled another option will auto-fill the values.

**Comment by pengchenglai** [comment]
Kindly let me know if anything unclear :)
