### ISSUE TITLE
Prefill same Total land area for the Atlantis 

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#2057]
@minotogna 
For the Atlantis countries use the same Total land area for all years

![1](https://user-images.githubusercontent.com/99216009/213713153-26c2954e-5103-442a-b1ea-0790c57d3668.PNG)

**Comment by minotogna** [comment]
@pengchenglai what value should we use ?

**Comment by pengchenglai** [comment]
@minotogna  

Will discuss it later in the meeting with Orjan.

**Comment by pengchenglai** [comment]
@minotogna 

4412.00 is used in the last cycle for **Total forest area** and also agreed by Orjan to use it in FRA 2025.
