### ISSUE TITLE
Geo: recipes

### ISSUE THREAD

**Issue by minotogna** [openforis/fra-platform#2089]
Add select above layers selection with pre calculated recipes

**Comment by joonasnuutinen** [comment]
Notes from the weekly:
- Default: empty
- Other values: get from meta
- When a preset recipe is selected, select those layers, set the opacity to 0 and show agreement layer
  - by default agreement level 1, Eugenia will add correct values to meta
- If any layer selection is modified, reset the recipe to its default value
