### ISSUE TITLE
Translations need to be updated

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#2095]
@minotogna 
e.g. Chinese and French
![1](https://user-images.githubusercontent.com/99216009/214813552-d708270a-a59b-4419-9957-1c692d23da91.PNG)
![2](https://user-images.githubusercontent.com/99216009/214813577-a17cc3e0-fae5-48f6-94ed-d5d4187c10dd.PNG)

**Comment by sorja** [comment]
https://github.com/openforis/fra-platform/issues/1080
