### ISSUE TITLE
Login alert

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#2129]
@minotogna 
People for the first login would subconsciously click the home without filling in the info for INSTITUTION and POSITION. Raising an alert in case it happens.

![a](https://user-images.githubusercontent.com/99216009/216652461-da890a9a-2237-431a-8837-f49c3b9141c2.PNG)

**Comment by minotogna** [comment]
User should be redirected to edit info page if that happens

**Comment by sorja** [comment]
Added notification

Home icon didn't do anything anyway (redirected to here)

Can you verify this was the behaviour?

I am unable to navigate to any other part of application if missing fields

**Comment by pengchenglai** [comment]
Me neither, it will stay on the personal profile info page if the info not being completed
