### ISSUE TITLE
Content / Check in the Dashboard under the reviewer role

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#2130]
It shows _Home section Placeholder_, not sure what it means. Should it suppose show something in this tab?

![a](https://user-images.githubusercontent.com/99216009/216656089-6b0128b6-cd6c-4e25-b7ab-710145ca4d21.PNG)

May consider removing it in case it does not have any functions

**Comment by minotogna** [comment]
We’ll disable it . Legacy app to be implemented

**Comment by pengchenglai** [comment]
Tks
