### ISSUE TITLE
Table 1a Total land area inconsistent between FRA 2020 and 2025

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#2134]
@minotogna 
For some years(highlighted in yellow), **Total land area(c)** is inconsistent. Is it an immigration error?

FRA2025:
![1](https://user-images.githubusercontent.com/99216009/216668877-238681da-1340-41ed-9985-9a93d3bae460.PNG)

FRA2020:
![2](https://user-images.githubusercontent.com/99216009/216669713-f8d3fe5a-08ed-48ab-a549-1a8b8ccec867.PNG)

**Comment by minotogna** [comment]
It's new data for 2025

**Comment by pengchenglai** [comment]
Ok, I see
