### ISSUE TITLE
Allowable error range

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#2135]
@minotogna 

To be discussed next week with the error range.

e.g. China table 1d 
![a](https://user-images.githubusercontent.com/99216009/216671727-03e5d107-f647-4fd8-a821-6121f2d7253a.PNG)

**Comment by pengchenglai** [comment]
@minotogna 
Table 1b allow minor difference for **forest area**
![2](https://user-images.githubusercontent.com/99216009/217217374-af91aceb-9a8e-49c6-b328-2d080cfe7db1.PNG)
![1](https://user-images.githubusercontent.com/99216009/217217393-f2b91862-a292-4aad-9ed7-a945896b7430.PNG)

**Comment by pengchenglai** [comment]
> @minotogna
> 
> To be discussed next week with the error range.
> 
> e.g. China table 1d ![a](https://user-images.githubusercontent.com/99216009/216671727-03e5d107-f647-4fd8-a821-6121f2d7253a.PNG)

@minotogna 
High priority
Discussed with Orjan: allow ±1(unit 1000 ha/year) difference between **Forest area net change (a-b)** in table 1d and forest area changes(table 1a)

**Comment by sorja** [comment]
Closed as duplicate for #2208
