### ISSUE TITLE
FRA T&D inconsistent format

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#2136]
@minotogna 
The font formatting and serial numbering&formatting has changed.

e.g. 1:
The updated T&D in github:
![3](https://user-images.githubusercontent.com/99216009/216674321-fe107b9c-8ce5-4839-a961-da0f7d659a28.PNG)

how it shows in FRA platform:
![1](https://user-images.githubusercontent.com/99216009/216674468-d7c65f57-398f-4360-961c-63a6bbb37083.PNG)

**Comment by pengchenglai** [comment]
e.g. 2:
The updated T&D in github:
![4](https://user-images.githubusercontent.com/99216009/216674714-916e6f08-55ea-4304-8d4b-505292dd8b75.PNG)


how it shows in FRA platform:
![2](https://user-images.githubusercontent.com/99216009/216674748-800b3a81-b124-467f-beb4-74245a3709b7.PNG)

**Comment by pengchenglai** [comment]
e.g. 1:
The updated T&D in github:
![6](https://user-images.githubusercontent.com/99216009/216674861-8e90b1be-e7c2-4b16-a8f7-1ab91c931acd.PNG)


how it shows in FRA platform in italic:
![5](https://user-images.githubusercontent.com/99216009/216674893-aae85d39-0c59-4495-a29e-87c17cf85208.PNG)

**Comment by minotogna** [comment]
This is how the format has been uploaded

**Comment by pengchenglai** [comment]
Alright, just look pretty weird the format in the FRA platform
