### ISSUE TITLE
Rich text editor (Jodit) spellcheck 

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#2156]
The spellcheck does not work for English characters. 

Comment from other colleagues would be great to have this function for all six languages.

![1](https://user-images.githubusercontent.com/99216009/216982620-a037f580-0d32-4a9a-94b1-331594961b46.PNG)

**Comment by pengchenglai** [comment]
Reorganize the location of **superscript** and **subscript**, please move them next to the features of the format

![5](https://user-images.githubusercontent.com/99216009/216987980-ae0e1036-fca8-477f-b6e2-eef671ec14b7.PNG)

**Comment by pengchenglai** [comment]
Plz remove color selection since it is not needed and cannot be saved after clicking done
![6](https://user-images.githubusercontent.com/99216009/216991483-5584f4c5-93cf-44cb-b9f4-5faccd5cbb5d.PNG)

**Comment by pengchenglai** [comment]
The **underline,font,font size,line height**......(**_highlighted in yellow_**) does not save the settings after clicking done.
![6](https://user-images.githubusercontent.com/99216009/216993767-2a8701c1-177d-4fb3-80bb-f16c11d18ce9.PNG)

**Comment by pengchenglai** [comment]
Not sure what **Insert classname** does, nothing changes in surface. Considering removing it if it is not necessary

![7](https://user-images.githubusercontent.com/99216009/216994554-71955a6d-d783-4007-9caf-551ee98c3ae2.PNG)

**Comment by pengchenglai** [comment]
Heading 1,2,3,4 have same result.

![8](https://user-images.githubusercontent.com/99216009/216995347-8cf55f51-a6ae-4530-bbe8-fc7b1313cbe1.PNG)

**Comment by minotogna** [comment]
@pengchenglai the editor we use has a spellcheck plugin, but we need to buy the pro version: https://xdsoft.net/jodit/pro/#plugins . it costs 99$

Can you please check with management if we can buy that?
thanks  ☺️

**Comment by minotogna** [comment]
https://xdsoft.net/jodit/docs/modules/plugins_spellcheck.html

**Comment by pengchenglai** [comment]
> @pengchenglai the editor we use has a spellcheck plugin, but we need to buy the pro version: https://xdsoft.net/jodit/pro/#plugins . it costs 99$
> 
> Can you please check with management if we can buy that? thanks ☺️

@minotogna  This would be a one-time payment, is that right?

**Comment by minotogna** [comment]
> > @pengchenglai the editor we use has a spellcheck plugin, but we need to buy the pro version: https://xdsoft.net/jodit/pro/#plugins . it costs 99$
> 
> > 
> 
> > Can you please check with management if we can buy that? thanks ☺️
> 
> 
> 
> @minotogna  This would be a one-time payment, is that right?

Yes @pengchenglai

**Comment by pengchenglai** [comment]
@minotogna 

Green light from Anssi :)

**Comment by minotogna** [comment]
> @minotogna 
> 
> 
> 
> Green light from Anssi :)
> 
> 
> 

@pengchenglai I would remove sensitive information from here ! 
Can u talk to our secretaries and proceed to purchase ?

**Comment by minotogna** [comment]
> > @minotogna 
> > 
> > 
> > 
> > Green light from Anssi :)
> > 
> > 
> > 
> 
> @pengchenglai I would remove sensitive information from here ! 
> Can u talk to our secretaries and proceed to purchase ?
> 

But before that , let us try the demo version and see how it works . Afterwards we'll proceed . What do you think ?

**Comment by pengchenglai** [comment]
> > > @minotogna
> > > Green light from Anssi :)
> > 
> > 
> > @pengchenglai I would remove sensitive information from here !
> > Can u talk to our secretaries and proceed to purchase ?
> 
> But before that , let us try the demo version and see how it works . Afterwards we'll proceed . What do you think ?

@minotogna 
Sure, let's see how the demo works, and I will talk with the secretary tomorrow if it works well.

**Comment by pengchenglai** [comment]
@minotogna 

Kindly let know if the demo is working or not, tks!

**Comment by minotogna** [comment]
> @minotogna 
> 
> 
> 
> Kindly let know if the demo is working or not, tks!

@pengchenglai please , give me the time

**Comment by pengchenglai** [comment]
@minotogna 

No rush, if you want me send the request to the secretary later on, just let me know whenever the test is done

**Comment by minotogna** [comment]
@sorja , I tried to test the pro version with spell check plugin but I had no luck.
Maybe a fresh pair of eyes can help. Can you have a look as first thing when you get back?
