### ISSUE TITLE
Table 1a add National data point

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#2158]
@minotogna 
Without clicking **Done editing** in National data point(NDP), NDP will create if one year is selected

<img width="742" alt="1" src="https://user-images.githubusercontent.com/99216009/217017979-46021aae-b4ac-43b4-94ba-1881e7140e0e.PNG">
<img width="477" alt="2" src="https://user-images.githubusercontent.com/99216009/217018215-9aa5568f-5ec2-4870-83d8-3d5ee7028cbd.PNG">

**Comment by minotogna** [comment]
correct, that's a fake button. data saving happens asynchronously in the background. should we remove the done editing button then ?

**Comment by pengchenglai** [comment]
From the user's perspective, there is a sense of certainty if there is a **Done editing** button although it does not do anything in reality. We can put this issue on hold at this moment and I will send an email to Örjan(Cc you).

**Comment by pengchenglai** [comment]
@minotogna 
We agreed to keep this button for the assurance
