### ISSUE TITLE
Table 2a second table validation rules

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#2172]
@minotogna 
Table 2a growing stock _second table_: Not sure what these two errors mean and the data suppose to be right since it is from the last cycle.
![2](https://user-images.githubusercontent.com/99216009/217263440-25fb5f79-5458-46eb-9c2a-8015c166d6d5.PNG)
![3](https://user-images.githubusercontent.com/99216009/217263466-12b4a14e-8170-4134-85a0-e264aa81a9ea.PNG)

**Comment by pengchenglai** [comment]
#2047

**Comment by pengchenglai** [comment]
Now I see the reason for the first error as **Naturally regenerating forest** +**Planted forest** should = **Total Forest**. The current alert is bit misleading

**Comment by pengchenglai** [comment]
Replace _Value should be equal to Total Growing Stock (2a)_ by **The summed value should be equal to the Total Forest**

**Comment by pengchenglai** [comment]
Still not sure what does second one mean

**Comment by sorja** [comment]
Hi @pengchenglai !
The second one was a typo, fixed by correcting the label:

``` 
mustBeEqualToForestArea:
      'The sum of Naturally regenerating and Planted forest should be equal to Total growing stock',
```

I have updated the first one :
old:
```
    mustBeEqualToTotalGrowingStock: 'Value should be equal to Total Growing Stock (2a)',
```

new:
```
    mustBeEqualToTotalGrowingStock: 'The summed value should be equal to the Total Forest',
```
