### ISSUE TITLE
Table 5c error message

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#2184]
@minotogna 
Validation check for **Degraded forest area for that year (in 1 000 ha)** is not appropriate: 
<img width="895" alt="1" src="https://user-images.githubusercontent.com/99216009/217578601-8cf4446d-dd1e-4da2-8390-f3ba1c73b384.PNG">

Follow the rule(choose one):
Exact match --- the cell value should **not exceed** the value of **Forest area** in table 1a for that year; e.g. for 2000, compare degraded forest area in 2000 with the forest area of 2000, which should not exceed the latter;

Flexible match(due to time limitation): the cell value should **not exceed** the _largest value_ of **Forest area** in table 1a; e.g. for 2000, compare degraded forest area in 2000 with the _largest value_ of Forest area available in table 1a

**Comment by pengchenglai** [comment]
#2185
The second option seems better since not all the years are available in table 1a

**Comment by minotogna** [comment]
Validation to implement :

- [ ] Section 5c->Table 'Forest degradation monitoring and assessment'->Cell 'Degraded forest area for that year (in 1 000 ha)': value should be <= maxForestArea. error message: 'Value cannot exceed the maximum value reported for forest area (1a)' 

cc @pengchenglai

**Comment by pengchenglai** [comment]
@minotogna 
It is a feasible solution if time is limited. 


Alternatively, would be great if users can enter & select(dropdown list) a year in the **Year of lastest assessment** later on when possible.  Then apply the following rules for the validation of **Degraded forest area for that year (in 1 000 ha)**:

In case A. if  forest area in that year such as 2000 is available in table 1a, then the value should be <= ForestArea(in that year such as 2000). error message: 'Value cannot exceed the forest area in {year}(1a)';
In case B. if  forest area in that year such as 2001 is **not** available in table 1a,then the value should be <= maxForestArea. error message: 'Value cannot exceed the maximum value reported for forest area (1a)'
