### ISSUE TITLE
Table 5 a/b supplementary validation rule

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#2185]
@minotogna 
Table 5 a/b may have the national data point(e.g. 2002) which does not exist in table 1a.  There is no validation rule apply for this case now. 

As supplementary validation rules for the years **not included** in table 1a: 
the value of the **single cell** should not exceed the _largest value_ of the Forest area in table 1a;
the sum of the value of  **all the cells**  in one year should not exceed the _largest value_ of the Forest area in table 1a.

<img width="748" alt="1" src="https://user-images.githubusercontent.com/99216009/217589775-64d04ac6-6e21-427e-ba32-cafb04ab4912.PNG">
<img width="714" alt="2" src="https://user-images.githubusercontent.com/99216009/217589883-c7bf73a2-c7a0-4d2a-a14b-4a04467b7e6b.PNG">

**Comment by minotogna** [comment]
@pengchenglai 

> Table 5 a/b may have the national data point(e.g. 2002) which does not exist in table 1a. There is no validation rule apply for this case now.

There's validation rule. if there's a data point, the value of the row is validated against forest area of that data point.

> As supplementary validation rules for the years not included in table 1a:

Do you mean the validation rule applies to years: [

    '2001',
    '2002',
    '2003',
    '2004',
    '2005',
    '2006',
    '2007',
    '2008',
    '2009',

    '2011',
    '2012',
    '2013',
    '2014',

    '2016',
    '2017',
    '2018',
    '2019',

    '2021',
    '2022'
  ]
?

> the value of the single cell should not exceed the largest value of the Forest area in table 1a; 

When calculating the largest forest area value, should we include forest area coming from original data points?

> the sum of the value of all the cells in one year should not exceed the largest value of the Forest area in table 1a.

Thank you

**Comment by pengchenglai** [comment]
@minotogna 
Thanks for raising the question:
Indeed, in case there is a forest area value from the corresponding data point(year) in Tab 1a, we should use this value to verify whether the corresponding value in 5a/5b has met the requirements.

As you listed these years above which are not necessarily data points in Tab 1a, thus may not a validation rule would do the check.  We can take the biggest value(among these cells highlighted in yellow) of the forest area from the existing DNP in Tab 1a to set as a threshold value which the sum of the value of all the cells in one year(e.g. table 5 b 2001 …of which on forest)should not exceed 
![1](https://user-images.githubusercontent.com/99216009/221952834-f4cff0c9-36d2-4d9c-9363-91c87131dd56.PNG)

If it is not clear, kindly let me know

**Comment by minotogna** [comment]
- [ ] **1. Implement function ```maxForestArea: ()=>string|undefined```**
  - add function maxForestArea that returns the maximum value of extentOfForest.forestArea if available 
  - update metacache: when generating meta cache and encounter this function, then treat it as if dependency was extentOfForest.forestArea (see member on how to populate the dependency cache)  

- [ ] **2. To  Section 5a and 5b -> Tables 'Forest damage' and 'Area affected by fire'-> All Cells of years ''2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009', '2011', '2012', '2013', '2014', '2016', '2017', '2018', '2019', '2021', '2022'' add two validations:**
  - value should be <= maxForestArea. error message: 'Value cannot exceed the maximum value reported for forest area (1a)' 
  - sum of all column cells should be <= maxForestArea. error message: 'The sum of year {{year}} cannot exceed the maximum value reported for forest area (1a)' 

(cc @pengchenglai)

**Comment by pengchenglai** [comment]
@minotogna @sorja 

Pay attention for 5b  **'Area affected by fire'** : 
_total land area_ of table 1a is used for the first row **Total land area affected by fire**; _forest area_ of table 1a is used for the second row **…of which on forest**

**Comment by minotogna** [comment]
@pengchenglai and how does it affect the validation mentioned above? Can you please be more explicit ? Thanks

**Comment by pengchenglai** [comment]
@minotogna 
First thing to highlight and add up(example for forest area):

We should set an **if** condition, such as:

A. **If a year, such as 2018, belongs to an NDP year, then "Value cannot exceed the value reported for forest area (1a) in that year (2018)."** This targets the years (2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2011, 2012, 2013, 2014, 2016, 2017, 2018, 2019, 2021, 2022) that could belong to an NDP year.

B. If a year does not belong to an NDP year, the value should be <= maxForestArea. The error message should be "Value cannot exceed the maximum value reported for forest area (1a)."

**Comment by pengchenglai** [comment]
The second thing to notice for Table 5b:

The first row is **Total land area affected by fire** for which we use the same method as before: if a year belongs to an NDP year, we verify that the value does not exceed the reported value for **Land area** (Table 1a). If the year does not belong to an NDP year, we use the maximum value among exsiting years to verify.

The second row is **...of which on forest** for which we also use the same method as before: if a year belongs to an NDP year, we verify that the value does not exceed the reported value for **Forest area** (Table 1a). If the year does not belong to an NDP year, we use the maximum value among exsiting years to verify.
