### ISSUE TITLE
Validations update

### ISSUE THREAD

**Issue by minotogna** [openforis/fra-platform#2208]
- [x] The consistency check in Table 1a is referring to Forest area reported in FRA 2015, it should compare with reported data in FRA 2020. Further the message should read “Click on the cell for more details” it should not say “ error”. The following message should be displayed. “Note that forest area reported is different from what was reported in FRA 2020 –please provide a comment explaining why it is different”. Further when adding a value for the year 2025 I also get the same message, the validation check should ONLY compare the FRA 2020 reported values for the years 1990, 2000, 2010, 2015 and 2020 –not 2025!
- [x] The consistency check in for primary forest reporting is comparing with forest area reported in FRA 2015, it should however compare with the forest area as actually reported in table 1a.
- [x] Table 1d. There seems to be an issue with rounding in the validation check, pls see Guyana. The validation should allow for minor differences caused by rounding e g less than 1 values.
- [x] In table 2a the current validation message reads Value should be equal to Total Growing Stock (2a) It should read “The sum of Naturally regenerating and Planted forest should be equal to Total growing stock”
- [x] In table 2b, there should be a validation check that the total growing stock should not exceed the total growing stock reported in table 2a
- [x] Table 4a, New Zealand why are all the cells for the “…of which” categories highlighted? The validation check should not consider cells that are empty. If all sub-categories are reported on then  the sum should be equal to the parent, but in case of missing values this is not the case.
- [x] The consistency check in for table 3a reporting is comparing with forest area reported in FRA 2015, it should however compare with the forest area as reported in table 1a.
- [x] For the validation check in table 3a the current message reads Exceeds Forest area (1a)   It should read “The sum of the reported FRA categories exceeds the forest area reported in table 1a”
- [x] In table 3a Total area designated (the table at the bottom) should NOT allow areas reported which are larger than the forest area reported in table 1a. Please add validation check.
- [x] In table 3b the total should be compared with what is reported in table 1a and nothing else.
- [x] Table 5b Area affected by fire. The validation check should ONLY apply for the subcategory “…of which on forest” NOT the “Total land area affected by fire”
- [x] Table 7 please add a validation check if a NWFP has been added then countries must indicate “NWFP Category”

**Comment by sorja** [comment]
Unable to replicate
- [ ] The consistency check in for primary forest reporting is comparing with forest area reported in FRA 2015, it should however compare with the forest area as actually reported in table 1a.
1a

![Screenshot 2023-02-14 at 13 40 45](https://user-images.githubusercontent.com/5508251/218741474-5ef73770-f68c-493c-9559-cd16fa71b501.png)


1b

![image](https://user-images.githubusercontent.com/5508251/218741295-4d2f8b5e-5df3-4fd4-a6bb-f80f345334e8.png)


- [ ] The consistency check in for table 3a reporting is comparing with forest area reported in FRA 2015, it should however compare with the forest area as reported in table 1a.

![image](https://user-images.githubusercontent.com/5508251/218693615-4d712b40-5aaa-4ede-b8d4-1b07c0c55295.png)


>  * [ ] In table 3b the total should be compared with what is reported in table 1a and nothing else.

![image](https://user-images.githubusercontent.com/5508251/218498450-0cf298dc-604b-4200-89b6-c7040b7ba3a5.png)


> * [ ]  Table 5b Area affected by fire. The validation check should ONLY apply for the subcategory “…of which on forest” NOT the “Total land area affected by fire”

![image](https://user-images.githubusercontent.com/5508251/218497101-874d6512-8270-489a-a5a8-3d6097911999.png)
