### ISSUE TITLE
Copy values

### ISSUE THREAD

**Issue by minotogna** [openforis/fra-platform#2225]
<ol type="1" start="1" style="font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none; caret-color: rgb(36, 36, 36); color: rgb(36, 36, 36); font-family: &quot;Segoe UI&quot;, &quot;Segoe UI Web (West European)&quot;, &quot;Segoe UI&quot;, -apple-system, BlinkMacSystemFont, Roboto, &quot;Helvetica Neue&quot;, sans-serif; font-size: 15px; margin-top: 0px; margin-bottom: 0px;"><li style="font-size: 12pt; font-family: &quot;Times New Roman&quot;, serif; margin: 0px; color: rgb(31, 73, 125) !important;"><span style="border: 0px; font-family: Calibri, sans-serif; font-size: 11pt; font-style: inherit; font-variant-caps: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; margin: 0px; padding: 0px; vertical-align: baseline; color: inherit;"> For FRA 2020 reporting we had the copy values button for table 1b and 2a, this is needed for the use of the biomass calculator. Please note that when selecting “Copy values” then only the values for the relevant variables for the biomass calculator should be copied..</span></li></ol><p style="font-size: 12pt; font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none; caret-color: rgb(36, 36, 36); color: rgb(36, 36, 36); font-family: &quot;Times New Roman&quot;, serif; margin-right: 0px; margin-bottom: 0px; margin-left: 36pt;"><span style="border: 0px; font-family: Calibri, sans-serif; font-size: 11pt; font-style: inherit; font-variant-caps: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; margin: 0px; padding: 0px; vertical-align: baseline; color: rgb(31, 73, 125) !important;">Relevant for Table 1b</span></p>

Forest category | 1990 | 2000 | 2010 | 2015 | 2020 | 2025
-- | -- | -- | -- | -- | -- | --
1000 ha | 1000 ha | 1000 ha | 1000 ha | 1000 ha | 1000 ha
Naturally regenerating forest |   |   |   |   |   |  
Plantation forest |   |   |   |   |   |  
...of which introduced species |   |   |   |   |   |  
Other planted forest |   |   |   |   |   |  

<p style="font-size: 12pt; font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none; caret-color: rgb(36, 36, 36); color: rgb(36, 36, 36); font-family: &quot;Times New Roman&quot;, serif; margin-right: 0px; margin-bottom: 0px; margin-left: 36pt;"><span style="border: 0px; font-family: Calibri, sans-serif; font-size: 11pt; font-style: inherit; font-variant-caps: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; margin: 0px; padding: 0px; vertical-align: baseline; color: rgb(31, 73, 125) !important;">Relevant for Table 2a</span></p>

Forest category | 1990 | 2000 | 2010 | 2015 | 2020 | 2025
-- | -- | -- | -- | -- | -- | --
m3/ha | m3/ha | m3/ha | m3/ha | m3/ha | m3/ha
Naturally regenerating forest |   |   |   |   |   |  
Planted forest |   |   |   |   |   |  
...of which plantation forest |   |   |   |   |   |  
...of which other planted forest |   |   |   |   |   |  

<p style="font-size: 12pt; font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none; caret-color: rgb(36, 36, 36); color: rgb(36, 36, 36); font-family: &quot;Times New Roman&quot;, serif; margin: 0px;"><span style="border: 0px; font-family: Calibri, sans-serif; font-size: 11pt; font-style: inherit; font-variant-caps: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; margin: 0px; padding: 0px; vertical-align: baseline; color: rgb(31, 73, 125) !important;"> </span></p>

**Comment by sorja** [comment]
Note: Functionality removed from code base

Old code found in GitLab (or version history)
