### ISSUE TITLE
Missing values

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#2239]
@minotogna 
![1](https://user-images.githubusercontent.com/99216009/219316583-b6fbc98a-bef5-4640-a9ff-4bec2232f599.PNG)

**Comment by pengchenglai** [comment]
Use the 1990 value for those years older than this DNP;

New list should include the total land area for the periods 1991-1999, 2001-2009, 2011-2014 and 2016-2019

**Comment by pengchenglai** [comment]
Not urgent, fixing this issue when high-priority matters have been solved.

**Comment by minotogna** [comment]
@pengchenglai this will be handled in #2303
