### ISSUE TITLE
Table 1a- add NDP-1a Forest, other wooded land and remaining land

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#2240]
@minotogna 
1.Not sure why there is an error without any warning message
![1](https://user-images.githubusercontent.com/99216009/219320085-a19319a9-3a97-4f9e-9d4a-ca3dbd2ee415.PNG)

**Comment by pengchenglai** [comment]
2. **Area** value does not being copied when choosing **Copy previous values**
![1](https://user-images.githubusercontent.com/99216009/219322307-e7ac8e33-0337-4987-b998-34c771dd1e38.PNG)

**Comment by sorja** [comment]
> 2. **Area** value does not being copied when choosing **Copy previous values**
>    ![1](https://user-images.githubusercontent.com/99216009/219322307-e7ac8e33-0337-4987-b998-34c771dd1e38.PNG)

This is expected behavior

More information:
https://github.com/openforis/fra-platform/pull/2139

**Comment by sorja** [comment]
Completed
