### ISSUE TITLE
Repeat profile info entry

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#2242]
@minotogna 
For each invitation, the user has to enter their profile data again. Not sure if it is the case for reviewers, but is the situation for NC and collaborators
<img width="828" alt="1" src="https://user-images.githubusercontent.com/99216009/219344850-0451bcba-c7da-4e4d-8aaf-09fed666f0f4.PNG">

**Comment by minotogna** [comment]
@pengchenglai it's very unlikely that a NC,C,ANC have a similar role in two countries.
plus certain user information area related to cycle/country.
closing the issue now, please advice if it should be changed.
