### ISSUE TITLE
Issues-4a Forest ownership

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#2243]
@minotogna 
Apart from the issue mentioned in #2234(been solved), there are two issues show up in the latest version.
1. Validation rules have act weirdly:
a.**Total (a+b+c+d)** should equal **Total forest area(table 1a)**
<img width="711" alt="1" src="https://user-images.githubusercontent.com/99216009/219373032-b7a9a629-09f6-4b86-b47e-65e5f5b136ff.PNG">
b. **Private ownership (a)**  +...+ **Unknown (d)** = **Total (a+b+c+d)**
<img width="711" alt="2" src="https://user-images.githubusercontent.com/99216009/219373133-53a0bd7f-aec9-4704-8955-54a02f7aa677.PNG">

**Comment by pengchenglai** [comment]
2. Missing data prefill:
<img width="705" alt="3" src="https://user-images.githubusercontent.com/99216009/219385047-613b9761-6ff2-4604-a515-77f709975021.PNG">

**Comment by sorja** [comment]
Should be ok,
closing  until reproduced in latest environment


https://user-images.githubusercontent.com/5508251/219851084-5029c430-fe24-408b-b00b-16692207301d.mov

**Comment by pengchenglai** [comment]
> Should be ok, closing until reproduced in latest environment

Well done!
