### ISSUE TITLE
The disabled intertubular function of table 2a /c/d 

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#2247]
Unit convention between the first and second tables of 2a /c/d is currently disabled
<img width="785" alt="1" src="https://user-images.githubusercontent.com/99216009/219397547-a4ee8b38-98dc-4187-bad6-10074d16464c.PNG">
<img width="770" alt="2" src="https://user-images.githubusercontent.com/99216009/219397560-8be51c6a-9bd9-4b8d-b06e-2f56ca0829be.PNG">
<img width="783" alt="3" src="https://user-images.githubusercontent.com/99216009/219397579-b003acf4-854a-4e55-9046-65c492d3f418.PNG">

**Comment by minotogna** [comment]
@pengchenglai , can you please advice what the issue is about? it's a bit unclear.
