### ISSUE TITLE
Send invitation email gives an error

### ISSUE THREAD

**Issue by AnssiSamuli** [openforis/fra-platform#2248]
1. Log in as NC of Atlantis 02
2. Invite collaborator
3. Click info icon
4. Click send invitation email link
5.
![image](https://user-images.githubusercontent.com/1213245/219401566-a85d9502-8589-4270-a81f-d1dae813916a.png)

**Comment by AnssiSamuli** [comment]
Sharing as this may be linked to the invitation email issue

**Comment by minotogna** [comment]
@AnssiSamuli is this still happening ?

**Comment by AnssiSamuli** [comment]
Nope!
