### ISSUE TITLE
General bugs (green ones)

### ISSUE THREAD

**Issue by rfontanarosa** [openforis/fra-platform#2251]
- [x] When filling the contact info form, if user selects “Other” then it does not work (does not allow user to access the platform)
- [x] Table 1b NDP reclassification table should show error if sum of the row is not 100%
- [x] T1d – The Forest area net change for period 2020-2025 is not calculated/populated
- [ ] ~~Table 1d It would have been nice to have an additional row at the end of the table showing net change according to T1a and prefilled (validation check). That would let countries see how data they fill in correspond to what they have reported in T1a. As it is now, no validation against T1a is done and the table can be filled with data that completely contradicts T1a without any warning message~~
- [x] Table 1e Delete the category “Remaining land area”
- [x] T5c – the cell value for “Degraded forest area for that year” indicates error even if it is correct. It says that it must match forest area from 1a which of course is not the case here…

[Some issues 16_02_23.docx](https://github.com/openforis/fra-platform/files/10764629/Some.issues.16_02_23.docx)

**Comment by pengchenglai** [comment]
Table 5c error message #2184

**Comment by minotogna** [comment]
@rfontanarosa (cc @sorja ) your hotfixes part 2 has been reverted. it broke data migration. it must be done again.
