### ISSUE TITLE
missing Russian translations

### ISSUE THREAD

**Issue by AlexandraFRA25** [openforis/fra-platform#2256]
Table 1 a
Remaining land area (c-a-b) - Остальные земли
Area (1000 ha) Площадь (1000 га)

**Comment by AlexandraFRA25** [comment]
1c Mangroves - Мангры

**Comment by AlexandraFRA25** [comment]
1c Specific forest categories -  Определенные категории лесов

**Comment by AlexandraFRA25** [comment]
1c Includes both Forest and Other wooded land Включает как леса, так и прочие лесопокрытые земли.

**Comment by AlexandraFRA25** [comment]
1b …of which primary forest  …в том числе девственные леса

**Comment by minotogna** [comment]
@AlexandraFRA25 @sorja is this issue still valid ?
