### ISSUE TITLE
Moveable message box(even better if can adjust the size)

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#2265]
The position of the current message box is fixed and could cover some reporting info, which is not handy for checking these info.

<img width="329" alt="1" src="https://user-images.githubusercontent.com/99216009/219697176-56de81f5-7fad-4b2a-b84b-adbbf5860382.PNG">

**Comment by minotogna** [comment]
@pengchenglai do you have any suggestion?

**Comment by minotogna** [comment]
maybe, we can have a button to collapse the section? something like Facebook chat ?

**Comment by minotogna** [comment]
TODO: 

- [ ] add button to collapse/expand message window (see Facebook chat for example)

**Comment by pengchenglai** [comment]
@minotogna 

Sorry, I did not see the messages before. What would be the ideal model looks like? Could you plz send a pic of the Facebook chat. Not sure if I find a right one in google:
![download](https://github.com/openforis/fra-platform/assets/99216009/bc9e3afa-9878-4620-ad08-c254e537dca0)

**Comment by minotogna** [comment]
can we close this issue @pengchenglai ?

**Comment by pengchenglai** [comment]
@minotogna 

Absolutely!
