### ISSUE TITLE
2d carbon stock

### ISSUE THREAD

**Issue by sorja** [openforis/fra-platform#2269]
Problem with avg vs total calculation:
Inserting '1' in total gives extremely big numbers for avg

https://user-images.githubusercontent.com/5508251/219851264-68cdf2a8-5d14-4b09-a30c-5cac93cc81c4.mov

**Comment by minotogna** [comment]
@sorja unable replicate

**Comment by minotogna** [comment]
can u provide conditions to replicate ?
