### ISSUE TITLE
Add footnotes if possible in table 1a

### ISSUE THREAD

**Issue by minotogna** [openforis/fra-platform#2297]
![Image](https://user-images.githubusercontent.com/1138156/220555334-ac362ebd-ee66-4b1d-bfbf-1ccc8a6a86be.png)

**Comment by sorja** [comment]
What are the footnotes..?

**Comment by pengchenglai** [comment]
Table 2c footnotes
https://github.com/openforis/fra-platform/issues/2241#issuecomment-1437042811

**Comment by pengchenglai** [comment]
Plz update tier tables(minor changes have been made in the table text) with footnotes when urgent issues have been solved
[Tier criteria_final.docx](https://github.com/openforis/fra-platform/files/10804474/Tier.criteria_final.docx)
