### ISSUE TITLE
Table 1d - additional row

### ISSUE THREAD

**Issue by minotogna** [openforis/fra-platform#2299]
Table 1d It would have been nice to have an additional row at the end of the table showing net change according to T1a and prefilled (validation check). That would let countries see how data they fill in correspond to what they have reported in T1a. As it is now, no validation against T1a is done and the table can be filled with data that completely contradicts T1a without any warning message

**Comment by rfontanarosa** [comment]
<img width="1067" alt="Screenshot 2023-02-22 alle 10 48 29" src="https://user-images.githubusercontent.com/10047945/220605061-dc866ba5-0105-438f-b453-a1499769843d.png">

[forestAreaChange.txt](https://github.com/openforis/fra-platform/files/10803073/forestAreaChange.txt)

**Comment by minotogna** [comment]
- [x] Add new metadata row
- [x] handle linkToSection per cycle
- [x] pre calculate new row
