### ISSUE TITLE
Fix User edit and api endpoints

### ISSUE THREAD

**Issue by minotogna** [openforis/fra-platform#231]
- [ ] User api endpoints must be /users/:userId/ (CRUD)
- [ ] User profile picture api endpoint must be /users/:userId/avatar
- [ ] Move user under server/modules directory 
- [ ] UI: When user is editing himself disable role checkboxes
- [ ] Make sure user can edit himself from home with no country selection
- [ ] In user action, pass countryIso in the request query 
- [ ] Refactor UI user components

**Comment by sorja** [comment]
wontfix
