### ISSUE TITLE
ODP Edit fixes

### ISSUE THREAD

**Issue by minotogna** [openforis/fra-platform#2310]
- [x] In table 1a if you look at Dominica, their first NDP (1984)  you will see that the reclassification of National class “Other land (1984)” is  0% forest and 0% Other wooded land but the remaining land area is empty, in this case it should be 100%.
- [x] ~~Table 1a, when adding NDPs the copy previous does not work if you add older NDPs (try with Atlantis 07 and add NDP for year 2002)~~
- [ ] introduced species not calculated . See production St Lucia 2025 1b. Table and odp report no value , it should be 0

**Comment by sorja** [comment]
@minotogna 
Working as planned:
You can't copy if there is no previous year


Should we instead implement the dropdown for years?

**Comment by minotogna** [comment]
@pengchenglai regarding point #2 that’s how it was requested to work . Please create a separe issue if and how the behavior has to change
