### ISSUE TITLE
Waiting for country validation- Country status

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#2317]
@minotogna 
Not a high priority issue
Updated workflow show be: editing->review->Awaiting approval->Approved> **Waiting for country validation**
#2046

**Comment by minotogna** [comment]
@pengchenglai So the ultimate status is Awaiting for country validation ?
And which role is allowed to move the status from Approved to Awaiting for country validation ?

**Comment by pengchenglai** [comment]
@minotogna 
Reply from Orjan:
![1](https://user-images.githubusercontent.com/99216009/220974304-247cc23c-988b-4900-a76f-0fb96ddb2177.PNG)

This issue may be put on hold since it is not urgent

**Comment by minotogna** [comment]
@pengchenglai should 2020 statuses be updated to 'validated by country' ?
which role is allowed to update those statuses ? 
which roles should be notified via email about the status change ?
should we invent some color scheme for these two new statuses ?

**Comment by pengchenglai** [comment]
Refer to the communication emails
