### ISSUE TITLE
Create AreaSelector component

### ISSUE THREAD

**Issue by sorja** [openforis/fra-platform#2334]
![Screenshot 2023-02-27 at 11 04 29](https://user-images.githubusercontent.com/5508251/221534044-d6da16b2-75eb-42a1-a49d-e89eedf0d99d.png)

**Comment by minotogna** [comment]
We should implement a generic country selector with autocomplete . 
This compomemt must be used in

- [x] toolbar 
- [x] In user edit form
- [x] landing page country selector
- [x] landing region selector
