### ISSUE TITLE
Pasting values from excel doesn't work or works incorrectly

### ISSUE THREAD

**Issue by sorja** [openforis/fra-platform#2336]
clipboard:

Table from excel:
123 | 123 | 123 | 123 | 123 | 123
-- | -- | -- | -- | -- | --
333 | 333 | 333 | 333 | 333 | 333
44 | 44 | 44 | 44 | 44 | 44

Result:
![Screenshot 2023-02-27 at 11 19 38](https://user-images.githubusercontent.com/5508251/221537443-097f012e-452b-4609-ae9b-675b9bebd978.png)

**Comment by minotogna** [comment]
@sorja can you please post a video? It's unclear where you started pasting

**Comment by sorja** [comment]
> video?

First cell
