### ISSUE TITLE
Error changing cycle from 2025 to 2020

### ISSUE THREAD

**Issue by sorja** [openforis/fra-platform#2338]
On atlantis 06 cycle 2025
Change cycle 2020

![Screenshot 2023-02-27 at 11 24 30](https://user-images.githubusercontent.com/5508251/221538504-78dae33b-841c-42de-8c89-7187df9dee6f.png)

**Comment by sorja** [comment]
Probably related to atlantis countries not existing in cycle 2020
Should redirect to /

**Comment by minotogna** [comment]
> Probably related to atlantis countries not existing in cycle 2020
> Should redirect to /

agreed, if country doesn't exists in target cycle then redirect to cycle home would be the solution
