### ISSUE TITLE
add assessment label

### ISSUE THREAD

**Issue by sorja** [openforis/fra-platform#2339]
add 

- [x] in email 

> You have been invited to access **_fra_** 2025 as National correspondent for Atlantis 06.

1. fra -> Should be FRA 
2. panEuropean-> panEuropean

- [x] in country selector

1. FRA -> FRA 
2. PANEUROPEAN -> should be panEuropean

**Comment by minotogna** [comment]
add i18n label:

```fra.lables.short ```
