### ISSUE TITLE
FRA-2020 Printing tables

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#2413]
@minotogna 

When trying to print tables(only) for FRA 2020, it shows the texts such as introduction first ,and then about 20 sec it deletes the texts and shows tables. 

Should show tables only.

<img width="527" alt="1" src="https://user-images.githubusercontent.com/99216009/225602400-a98c7c16-6fce-4076-b6fa-b29c0cf87bdd.PNG">

[Printing error.webm](https://user-images.githubusercontent.com/99216009/225602434-2287d6ce-0ecd-4bcf-973b-bd109e1e9754.webm)

**Comment by sorja** [comment]
@pengchenglai can you share country iso you are testing with

also can you reupload video? doesn't load for me

**Comment by pengchenglai** [comment]
@sorja 
You could try China 2020.

Sure, 
[99448287-d83b-4367-9127-bf39d57ec714.webm](https://github.com/openforis/fra-platform/assets/99216009/50d6879a-5efe-4cf4-b45a-bb5be17bc4e1)
https://github.com/openforis/fra-platform/assets/99216009/50d6879a-5efe-4cf4-b45a-bb5be17bc4e1
