### ISSUE TITLE
Table 2b rearrangement for "Most recent year:"

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#2414]
@minotogna 

Set _Most recent year_ be in **bold** and put it in the location as shown by the red arrow.
<img width="677" alt="1" src="https://user-images.githubusercontent.com/99216009/225651369-3eb29b1e-bab1-4753-a082-abc9bbcb925d.PNG">

**Comment by minotogna** [comment]
@pengchenglai not entirely sure what we should move ? the label? or the drowdown ?

**Comment by pengchenglai** [comment]
@minotogna 
Only the label **"Most recent year:"** and highlight it in bold
