### ISSUE TITLE
Time limit for accepting invitation: 2 weeks

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#2416]
@minotogna 

Could you please double check if there is any time limit for accepting invitation(whenever possible), which is not urgent? I got an invitation for one Atlantis and tried to accept it after one week, but the link interface says "**This invitation has already been expired**".

**Comment by minotogna** [comment]
Hi @pengchenglai 
Correct , invitations are valid for one week .
Afterwards user must be invited again .
There’s a security risk if we keep those links valid for long time .
I close this issue for now , but please let me know if there’s any further question 
Thank you

**Comment by pengchenglai** [comment]
@minotogna 
Hey! Good to know this and will talk with Örjan to see if it is an issue or not since there are invitations sent two weeks before the workshop.

Thanks!

**Comment by pengchenglai** [comment]
@minotogna 
Plz reset the time limit for accepting invitations if possible

Quote from Örjan:
I think that the platform invitation message should specify how long the invitations are actually valid and what to do if it has expired.  In any case I think that it would be good if we could extend the period from one to two weeks and add the text: **Please access the platform within two weeks after receiving the invitation after that the invitation is invalid. Should you need a new invitation then please contact fra@fao.org.**

If 2 weeks is too long(due to the security concern) then perhaps we can have a compromise of 10 days. Plz change the text of **two weeks** to **ten days** in this case.

Thanks :)

**Comment by minotogna** [comment]
### TODO

- [x] update invitation time limit to 2 weeks
- [ ] add text **Please access the platform within two weeks after receiving the invitation after that the invitation is invalid. Should you need a new invitation then please contact [fra@fao.org](mailto:fra@fao.org).** in bold after accept invitation button
