### ISSUE TITLE
Issue of Total land area --- Table 1a

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#2419]
@minotogna 

The issue seems appearing again: When adding new National data points, the **Total land area** would disappear.

<img width="743" alt="1" src="https://user-images.githubusercontent.com/99216009/225922157-e247b5c6-7964-4f28-a16d-a99d51dea6a9.PNG">

**Comment by minotogna** [comment]
@pengchenglai please mention country and cycle 
Thank you

**Comment by pengchenglai** [comment]
@minotogna 

I have this issue for all Atlantis countries(4,18,19) I can access to in the fra-data 2025 cycle.

Thanks!
