### ISSUE TITLE
High priority --Add tutorial clips

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#2420]
@minotogna 

To be confirmed in the coming emails:

 Plz add two tutorial buttons, such as 'Login with FRA' and 'Login with Google' (followed by video icons):
<img width="644" alt="1" src="https://user-images.githubusercontent.com/99216009/225927779-da5108d7-b932-4e40-b967-a3f9553251f7.PNG">

Additionally, please add a button of **Tutorials** in the appropriate position on the main page which redirects to one public space that lists tutorials for different languages. For each language it should have _Navigation_, _Upload Document, Add NDP and Add Collaborator_ :
<img width="951" alt="2" src="https://user-images.githubusercontent.com/99216009/225927802-50a62eb1-e0dc-4050-be3a-24cf62643d36.PNG">

**Comment by pengchenglai** [comment]
Video clips can be found in the email attachment

**Comment by pengchenglai** [comment]
Kindly find tutorial clips link in the email

**Comment by pengchenglai** [comment]
The tutorial of _Add NDP_ is available now in the same folder

**Comment by minotogna** [comment]
@pengchenglai do you have any news about this?

**Comment by pengchenglai** [comment]
@minotogna 
Good morning! 

I have talked with Sara and she told me the person in charge of publishing still on leave. She has sent him another reminder today. I will forward the emails to you.

**Comment by pengchenglai** [comment]
@minotogna 
@rfontanarosa 
@sorja 

It is time to plan adding FRA [tutorials](https://unfao.sharepoint.com/:f:/s/NFO/Eh9SZeCV2z9CqXwqwUC5thkB5xYp_xhEOs8ZHBdxivo11g?e=atS0ZB) to the platform.

Separate tutorials based on the content and place them in suitable locations, such as the login page or dashboard.

PS: I have sent a request to OCC to publish the video last week, but I'm not sure when they will publish them.

**Comment by pengchenglai** [comment]
@minotogna 
On the login page, we put the logos of the video that associate with the first two videos( info for the video and translations [check here ](https://unfao-my.sharepoint.com/:x:/g/personal/pengcheng_lai_fao_org/EaKdTshlCZ1NlT8q5C_Z2gMBZJ-an9TZeDoBbnHHVl-I1Q?e=OkZN38))  which show how to log in and put user info either using a self-defined password or Google authentication **separately**,
<img width="495" alt="1" src="https://github.com/openforis/fra-platform/assets/99216009/e57cc35f-3934-49e4-beac-a4111a7575cd">

**Comment by pengchenglai** [comment]
@minotogna 

One suggestion could be

The logo for rest four videos could be put next to the dashboard or other free space as below showed in yellow:
<img width="949" alt="3" src="https://github.com/openforis/fra-platform/assets/99216009/6eeb17db-0ca5-4ac9-ba19-3e130fa97ba2">




We could put a logo with a link for the third video [How to add a collaborator](https://www.youtube.com/watch?v=SsGXSaNFmH4&list=PLzp5NgJ2-dK4ZmmQ2qHRVR--pu-kVp5DZ&index=5) and ideally user can find other videos in the playlist. Or we could put a logo with a drop-down menu that lists the rest four videos.

Other options are welcomed as long as there are suitable!

**Comment by pengchenglai** [comment]
The tutorials for all UN languages except French will use the [video links](https://unfao-my.sharepoint.com/:x:/g/personal/pengcheng_lai_fao_org/EaKdTshlCZ1NlT8q5C_Z2gMBZJ-an9TZeDoBbnHHVl-I1Q?e=OkZN38&CID=91bf5d13-3bb0-d6f1-8ce0-b411bc326cee) for English at this stage.

**Comment by minotogna** [comment]
All the info needed for publishing videos on the platform is now available [here](https://unfao-my.sharepoint.com/:x:/g/personal/pengcheng_lai_fao_org/EaKdTshlCZ1NlT8q5C_Z2gMBZJ-an9TZeDoBbnHHVl-I1Q?e=OkZN38&CID=91bf5d13-3bb0-d6f1-8ce0-b411bc326cee). 

PS: The tutorials for all UN languages except French will use the video links for English at this stage.
