### ISSUE TITLE
High priority- Missing overview- FRA 2025

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#2421]
@minotogna @sorja 

This is a high priority issue:

The **Overview** for data is missing for FRA 2025:

FRA 2020
<img width="960" alt="0" src="https://user-images.githubusercontent.com/99216009/225950342-abb43605-3b56-4485-96b6-8f3cbc2781c8.PNG">

FRA 2025
<img width="960" alt="1" src="https://user-images.githubusercontent.com/99216009/225950351-5e13f221-003d-457d-9dd8-514dc571a6fe.PNG">

**Comment by sorja** [comment]
Overview is hidden for 2025 until data collection part is complete (and other related discussion for this also going on in the background)

**Comment by sorja** [comment]
@minotogna Closing as not planned - please reopen if this should be opened

**Comment by pengchenglai** [comment]
Great, thanks! I will let Örjan know
