### ISSUE TITLE
make cycle lading page accessible only for users with a role or when assessment is published

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#2422]
When accessing platform for the first time(see below), it always direct to https://fra-data.fao.org/assessments/fra/2020 instead of https://fra-data.fao.org/assessments/fra/2025.
<img width="669" alt="1" src="https://user-images.githubusercontent.com/99216009/225952312-46a12718-7235-440e-8fcb-5b9f6c92c5f2.PNG">

**Comment by sorja** [comment]
Please kindly add more information:
- Are you logged in?
- What roles do you have (do you have for cycle 2025)
- What is the expected behavior? (Last invited cycle, latest cycle, etc)
Thanks, have a nice weekend

**Comment by pengchenglai** [comment]
I logged out any roles before accessing it from web search results as a general member of the public who is trying to view the FRA 2025 platform, but see FRA 2020 home page:
![0](https://user-images.githubusercontent.com/99216009/226061654-e54ba970-46ca-44cc-9176-6c819fccbe64.PNG)


Now to view FRA 2025 (instead of FRA 2020), I have to type in  _https://fra-data.fao.org/assessments/fra/2025/_. 
![1](https://user-images.githubusercontent.com/99216009/226060341-a0391d0e-1217-427d-99ff-d0d0bffd282e.PNG)


No worries, it's just a minor issue.

Thanks, you too! :)

**Comment by sorja** [comment]
FRA 2025 should not be available for general public before it is published
So I think the real issue is that you are able to access FRA 2025 landing page without being logged in*

*logged in with a user that has a role in 2025

**Comment by pengchenglai** [comment]
Right, it is the other way around. Maybe we can consider disabling open accessibility for FRA 2025 as gernerl public at this stage. 

Thanks!

**Comment by minotogna** [comment]
Hi @pengchenglai @sorja 
There’s no harm with that page , however for consistency we’ll make cycle lading page accessible only for users with a role or when assessment is published as you mentioned above 
I consider this issue very low priority

**Comment by pengchenglai** [comment]
Hey, it is a minor issue indeed
