### ISSUE TITLE
Wrong country status after login/ Blank county page

### ISSUE THREAD

**Issue by minotogna** [openforis/fra-platform#2426]
After login and redirect to 2025 , country status seem to reflect 2020 cycle 

Steps to replicate : 
- goto to 2020 landing 
- login with fra using AP account 
- user gets redirected to a 2025 county page 
- bug 1: open county selectors in toolbar -> country statuses are 2020 , not 2025 
- bug 2: click Atlantis06 -> page is blank

**Comment by sorja** [comment]
Unable to replicate

**Comment by minotogna** [comment]
It seems related to old cookies stored in the browser 
How can it be possible 😀😅?
Let's talk in the daily

**Comment by minotogna** [comment]
@sorja Closing it for now .
