### ISSUE TITLE
CountrySelect Autofocus missing

### ISSUE THREAD

**Issue by sorja** [openforis/fra-platform#2440]
![image](https://user-images.githubusercontent.com/5508251/227139574-069ae769-3ec3-48dd-ab69-4021aa41fead.png)

On first open the text input is not autofocused

**Comment by minotogna** [comment]
Not sure if we want autofocus; it's an old paradigm.
I would rather let the user choose if he/she wants to search .
What do you think @sorja @rfontanarosa ?
