### ISSUE TITLE
Translations: Add typeOfDataSourceText for ru/fr

### ISSUE THREAD

**Issue by sorja** [openforis/fra-platform#2443]
on hold: Pending translations for languages

fr and ru
`typeOfDataSourceText: '$t(dataSource.typeOfDataSource)',`

**Comment by pengchenglai** [comment]
@minotogna @sorja 

Seems the changes may be applied already.
Plz double-check if this issue has been fixed or not.

![2](https://github.com/openforis/fra-platform/assets/99216009/c5929feb-8d51-46ef-a65a-8d8482079bd0)
![3](https://github.com/openforis/fra-platform/assets/99216009/42b16540-96bf-48ad-8cf9-d1be850843d6)
![4](https://github.com/openforis/fra-platform/assets/99216009/5724f1eb-24b9-49e4-8aad-e61d1f90931c)
![5](https://github.com/openforis/fra-platform/assets/99216009/5db5ad66-3eb7-4d66-8ade-f82bd5643761)

**Comment by minotogna** [comment]
I see the translations in the platform. Please advise if otherwise. 
 I close the issue for now
