### ISSUE TITLE
Flexible match of primary forest in table 1b

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#2503]
@minotogna 
As highlighted in yellow, the values(if any) of these two rows should be flexibly matched with an approximation of 1 unit(1000 ha in this case) should be allowed.

![1](https://user-images.githubusercontent.com/99216009/229733219-89612fe9-e509-49a8-814a-6e6584ab4d98.JPG)

**Comment by minotogna** [comment]
@pengchenglai , I'm sorry, this is not 100% clear to me. what is the exact change we should apply to the platform ?
thank you ☺️

**Comment by pengchenglai** [comment]
@minotogna 
Session 1b now has two tables: the first table has one variable called **…of which primary forest** which is the sum of  
**Primary forest by climatic domain** in the second table.

Now it would be great if we apply the following rule: In case there is a value for  **…of which primary forest** for a certain year(such as 2025) and all the sub-categories of **Primary forest by climatic domain** are available(no sub-category empty,such as in 2025), check the **Total**(which is the sum of all sub-categories of **Primary forest by climatic domain** ) in second table if it is matched with **…of which primary forest** in the first table.

Flexible match with 1 unit(1000 ha in this case) difference should be allowed.

Kindly let me know if it is still unclear, thanks :)

**Comment by pengchenglai** [comment]
![1](https://user-images.githubusercontent.com/99216009/234231897-3e8cb2fe-e21e-49e1-bdf8-646d01a18ae8.JPG)
Example for flexible match:

If all the values for 4 sub-classes in **Primary forest by climatic domain** are available, then should check whether the value for **Total** is between 99 and 101.
![2](https://user-images.githubusercontent.com/99216009/234232045-c2da0cd3-3e8d-4df5-937f-60784b29259d.JPG)

**Comment by pengchenglai** [comment]
![4](https://user-images.githubusercontent.com/99216009/234233495-26d3ba9b-925b-4a6a-9c4f-6d40b0c0ad48.JPG)

If any of the value(s) among 4 sub-classes in **Primary forest by climatic domain** is/are missing, then should check whether the value for **Total** is greater than the value of **…of which primary forest** in the first table.
![3](https://user-images.githubusercontent.com/99216009/234233470-dd30b455-0f93-457a-b6af-765f0d63c8bd.JPG)


In this case, we should allow the value of the **Total** below of **…of which primary forest**. Such as 1 is allowed in this case
