### ISSUE TITLE
High priority-Table 1b-NDP-primary forest(cannot be empty)

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#2509]
@minotogna 

When keeping percentage of the primary forest as empty and area of others in the **Naturally regenerating forest** is 0, the overall value is 0, but should be **empty**
![1](https://user-images.githubusercontent.com/99216009/229962887-606dc7a7-ce0c-44ec-89ea-8b127cc890d4.JPG)
![2](https://user-images.githubusercontent.com/99216009/229962901-36d276d1-fc62-415a-bbf5-50f4a24b84e4.JPG)

**Comment by rfontanarosa** [comment]
verified with penchang. this issue doesn't occur anymore.

https://user-images.githubusercontent.com/10047945/232509669-7fc70fdd-96c2-4432-9b19-fe7c5146057a.mov
