### ISSUE TITLE
Cursor should stay where the data is entered(not the last)

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#2511]
@minotogna 

[cf57e6ba-c1ae-4dda-b21e-9065fe04a448.webm](https://user-images.githubusercontent.com/99216009/229969454-c556ba07-ef7c-4e90-948d-3de4490d4680.webm)

**Comment by rfontanarosa** [comment]
already solved

https://user-images.githubusercontent.com/10047945/231085387-ab479bc2-2579-4bc7-98d3-f5341edc8660.mov
