### ISSUE TITLE
Highest priority- disable NC permission of editing(choose picture and APPELLATION*)

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#2512]
The national correspondent can edit others'(including reviewer and collaborator) pictures and APPELLATION*.

![2](https://user-images.githubusercontent.com/99216009/229978949-3b381a95-25cd-475e-ac9e-6b11e1da4d5e.JPG)
![1](https://user-images.githubusercontent.com/99216009/229978937-876e56cc-d12c-459c-9131-30e4cde83718.JPG)

**Comment by minotogna** [comment]
NCs should be able to ADD any collaborators and alternates but not to EDIT their profiles.

While Reviewers can edit them.

**Comment by pengchenglai** [comment]
@minotogna 

Discussed with Orjan and there are the rules we should follow:
1. Only allow each person to edit their profile;
2. NCs should **not** be able to invite a alternative NC since it must be a official nomination

**Comment by minotogna** [comment]
ok @pengchenglai so the changes are:

- [x] NCs can only invite Collaborators. They cannot invite Alternate NC.
- [ ] NCs cannot edit any profile.

**Comment by pengchenglai** [comment]
@minotogna 
That is correct, thanks!

**Comment by rfontanarosa** [comment]
the first point is already valid:


![Image](https://user-images.githubusercontent.com/10047945/231193200-5b832788-8623-4434-90ac-86bf7bddf9f9.png)
