### ISSUE TITLE
Round issue- keep only two digits for each table

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#2515]
@minotogna 

![Screenshot 2023-04-05 122907](https://user-images.githubusercontent.com/99216009/229989063-e7814937-d1f6-4ff5-8801-13ba2164e652.png)

**Comment by minotogna** [comment]
@pengchenglai that cell must have been calculated . When data is visualized is rounded, calculations are not .
Are you 100% sure it's what we want ? We might lose information . 
Please confirm this.
Thank you 😊

**Comment by pengchenglai** [comment]
@minotogna 
Talk with Orjan again and he would rethink of this issue again once possible.  Let's put it on hold for now.

**Comment by minotogna** [comment]
ok @pengchenglai . I close this issue for now.
