### ISSUE TITLE
T&Ds in AR

### ISSUE THREAD

**Issue by samym392** [openforis/fra-platform#2542]
@minotogna @sorja Terms and definitions in Arabic language in the FRA platform are not in a right positions and some of them they are unallocated

![Capture](https://user-images.githubusercontent.com/123095733/232042553-4fdf3519-787d-43da-9de7-7cce252686af.PNG)

**Comment by sorja** [comment]
Thanks, fixed

Should be visible in review instance

https://fra-data.review.fao.org/assessments/fra/2020
