### ISSUE TITLE
±1 difference for the Total in Primary forest by climatic domain(session 1b)

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#2556]
@minotogna 

As highlighted below  ±1 unit(= ±1000 ha) difference for the **Total** in the table   _Primary forest by climatic domain(session 1b)_ should be allowed.
![1](https://user-images.githubusercontent.com/99216009/233142819-f7912e35-27ef-4c4e-8987-bd06d7ccad08.JPG)

**Comment by rfontanarosa** [comment]
see #2503
