### ISSUE TITLE
MessageBoard - Disable one to one / country message button if user is admin

### ISSUE THREAD

**Issue by rfontanarosa** [openforis/fra-platform#2563]
Admin can write messages to all
All can't see Admin messages

<img width="1098" alt="Screenshot 2023-04-24 alle 21 19 22" src="https://user-images.githubusercontent.com/10047945/234094981-c09d863b-00fb-4298-965d-ca9d87eb6751.png">

<img width="1112" alt="Screenshot 2023-04-24 alle 21 19 10" src="https://user-images.githubusercontent.com/10047945/234094996-d24051a3-e43b-4b2b-b3b3-c6b85055de7e.png">

**Comment by minotogna** [comment]
That's actually because admin is not part of users list and it should remain that way .

Proposed changes:
- [ ] Disable one to one / country message button if user is admin
