### ISSUE TITLE
ODP: Remaining land area not taken from the NDP but different, please align

### ISSUE THREAD

**Issue by minotogna** [openforis/fra-platform#2593]
Remaining land area not taken from the NDP but different, please align. See below

Country Tuvalu: 

![Image](https://user-images.githubusercontent.com/1138156/236750657-1b6dee88-2d9d-4f48-8737-85b5f58f37d8.png)

**Comment by sorja** [comment]
> There’s no issue . Remaining land area in table 1a is calculated from the formula you see (c-a-b) . In ODP is enters by the user (using percentages) . Therefore the two values can be , obviously, different .
