### ISSUE TITLE
Reviewer not receiving country status change email notification

### ISSUE THREAD

**Issue by minotogna** [openforis/fra-platform#2594]
MG: as a reviewer (Monica) I am not getting notifications when a country is changing status

MG: Yes I am not getting the email, today Micronesia submitted for review by mistake, Chiara got the email, I did not, we both are reviewers but it had happened again with Saint Vincent

**Comment by rfontanarosa** [comment]
MG: about my issue, yes mistery solved thanks!the email notification go to the gmail, which i never check while I was expecting it to go to the fao email
