### ISSUE TITLE
Email provider

### ISSUE THREAD

**Issue by minotogna** [openforis/fra-platform#2598]
INC0098176

**Comment by sorja** [comment]
> There’s no issue . Remaining land area in table 1a is calculated from the formula you see (c-a-b) . In ODP is enters by the user (using percentages) . Therefore the two values can be , obviously, different .

**Comment by sorja** [comment]
Using OutLook365

Info specified previously mentioned ticket ID

**Comment by sorja** [comment]
@minotogna this can be closed?
