### ISSUE TITLE
High-priority issue- delay in calculation

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#2603]
@minotogna 
@sorja 
@rfontanarosa 

Very slow for the calculation, example from table 1a:

This situation may cause some confusion for the users:
In table 1a _Extent of forest and other wooded land_, after using **Repeat last**, the **Remaining land area (c-a-b)** value is missing at the beginning and it pops up with an error after refreshing for a while(see below), In the end, the value is auto-corrected and values are all right:

Right after using estimation(using **Repeat last**) : 
<img width="727" alt="1" src="https://github.com/openforis/fra-platform/assets/99216009/49fba0e6-e661-47a1-a4f1-6c768f16e8af">

After refreshing(_quite few minutes around 10_):
<img width="744" alt="2" src="https://github.com/openforis/fra-platform/assets/99216009/d0670f1c-5584-467c-aba3-fc43a95677d8">

Another few minutes all good:
<img width="732" alt="3" src="https://github.com/openforis/fra-platform/assets/99216009/fe39489b-b9bc-4e76-a96d-c1a7a26ba111">

**Comment by pengchenglai** [comment]
Not sure if it is an issue: the FRA year 2020 which is between 2017 and 2022 uses linear trend to estimate the data while the user has chose the method of **Repeat last**. In case it is an issue, please also fix it for estimation(using **Repeat last**) in session 1b

**Comment by minotogna** [comment]
> Not sure if it is an issue: the FRA year 2020 which is between 2017 and 2022 uses linear trend to estimate the data while the user has chose the method of **Repeat last**. In case it is an issue, please also fix it for estimation(using **Repeat last**) in session 1b

@pengchenglai that's how it was requested to be implemented. please talk to OJ for details.

**Comment by minotogna** [comment]
btw this is not a real issue. we need to work on performances optimization. closing this issue
