### ISSUE TITLE
Comments section does not work in table 1a

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#2614]
@minotogna 

The comments area does not pop up in table 1a
<img width="773" alt="1" src="https://github.com/openforis/fra-platform/assets/99216009/abaad47a-63c6-4c95-a0fb-05bd382f0437">

**Comment by sorja** [comment]
https://github.com/openforis/fra-platform/issues/2595
Duplicate & Resolved

Thanks for reporting!
