### ISSUE TITLE
Missing Translations: Russian

### ISSUE THREAD

**Issue by sorja** [openforis/fra-platform#2617]

**Comment by sorja** [comment]
<html><body>
<google-sheets-html-origin>

key | English
-- | --
common.areYouSureYouWantToDeleteAllTableData | Are you sure you want to delete all data from the table?
common.clearTable | Clear table
common.continue | Continue
common.copyToClipboard | Copy to clipboard
common.dashboard | Dashboard
common.status | Status
common.tier | Tier
common.tiers.high | High
common.tiers.low | Low
common.tiers.notSelected |  
common.trend | Trend
contentCheck.// | Keys are in same format as the database fields
fra.labels.short | FRA
fra.extentOfForest_forestAreaStatusAndTrend_Description.footer1 | ¹ Data not older than 5 years from year of submission of report (2018 or more recent for FRA 2025 country reports)
fra.extentOfForest_forestAreaStatusAndTrend_Description.footer2 | ² Data older than 5 years from year of submission of report (older than 2018 for FRA 2025 country reports)
fra.extentOfForest_forestAreaStatusAndTrend_Description.footer3 | ³ Compatible in terms of methods, categories and definitions used
fra.growingStock_growingStockStatus_Description.footer1 | ¹ Data not older than 10 years from year of submission of report (2013 or more recent for FRA 2025 country reports)
fra.growingStock_growingStockStatus_Description.footer2 | ² Data older than 10 years from year of submission of report (older than 2013 for FRA 2025 country reports)
definition.seeReportingNotes | See Reporting Notes
nationalDataPoint.prefill | Prefill
nationalDataPoint.prefillWith | Prefill with
nationalDataPoint.dataSource2025ExplanatoryText | The data sources listed were reported in FRA 2020. Please copy and paste relevant data sources in table above.
nationalDataPoint.confirmCopyPreviousValues | Do you want to override previous values? This operation cannot be undone.
userManagement.invitationLinkCopied | The invitation link has been copied
forestAreaChange.forestAreaNetChangeFrom1a | Forest area net change from table 1a
assessment.status.notStarted.label | Not started
generalValidation.notEmpty | Value cannot be empty
generalValidation.mustBeEqualToPrimaryForest | Subcategories sum should be equal to Primary Forest
generalValidation.landAreaExceedsTotalLandArea | Land area exceeds total land area (1a) ({{value}})
generalValidation.classValueNotGreaterThan | {{name}} should be not greater than {{value}}
generalValidation.classValuesMustBeEqualTo | {{name}} sum must be equal to {{value}}
generalValidation.valueCannotExceedMaximumValueReportedForForestArea | Value cannot exceed the maximum value ({{maxForestArea}}) reported for forest area (1a)
generalValidation.valueCannotExceedMaximumValueReportedForForestAreaYear | The sum of year {{year}} cannot exceed the maximum value ({{maxForestArea}}) reported for forest area (1a)
generalValidation.valueCannotExceedMaximumValueReportedForLandArea | Value cannot exceed the maximum value ({{maxLandArea}}) reported for land area (1a)


</body>
</html>

**Comment by minotogna** [comment]
@sorja do we still keep this issue opened or is it somehow completed from your side?

**Comment by sorja** [comment]
@minotogna keep open still, I will manually close when completed

**Comment by minotogna** [comment]
ok @sorja . moving it to the next milestone.

**Comment by sorja** [comment]
@AlexandraFRA25

**Comment by AlexandraFRA25** [comment]
ok
