### ISSUE TITLE
Email notification - One To One Messages

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#2640]
@minotogna 
Please,double-check if it has already been implemented:

When someone leaves a message in the message box(one-to-one message), the recipient's email box should receive something like this: "Dear [the name of the person]: You have received a message from the FRA platform." The email should also include a link to the webpage(Message board).

<img width="933" alt="1" src="https://github.com/openforis/fra-platform/assets/99216009/27080867-c599-4a1d-931b-80d196e7f873">

**Comment by minotogna** [comment]
@pengchenglai we need to switch email provider , and we're in contact with csi .

**Comment by pengchenglai** [comment]
Sure, thanks for the update.
