### ISSUE TITLE
Validation check - 4a

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#2655]
@minotogna 
Not sure why there is an error message for **Total (a+b+c+d)** since it is same value as forest area in table 1a.

Example of Indonesia(year 2015)

Forest area in table 1a:
 
![1](https://github.com/openforis/fra-platform/assets/99216009/bed526b7-adaa-49dd-9218-0f2075965f34)

Validation check error in table 4a(exceed forest area table 1a):
![2](https://github.com/openforis/fra-platform/assets/99216009/29e6bbaf-6419-4502-aa9e-68a1b0f4b7bd)

**Comment by rfontanarosa** [comment]
this issue is no longer valid and already solved in alpha-11.
