### ISSUE TITLE
Chart translations don't update on language change

### ISSUE THREAD

**Issue by sorja** [openforis/fra-platform#2657]
![image](https://github.com/openforis/fra-platform/assets/5508251/49946751-f6b0-4715-b0ff-0e2b0d56ce09)

Table 1a
ODP Chart

In screenshot:
Choose French
Refresh
Choose English
Error

**Comment by pengchenglai** [comment]
@minotogna @sorja 

Örjan and I have checked this issue, and the chart translations are now looking correct.
Plz double-check if this issue has been fixed or not.
