### ISSUE TITLE
Country Last Edit performance issue

### ISSUE THREAD

**Issue by sorja** [openforis/fra-platform#2658]
https://github.com/openforis/fra-platform/blob/2a60f3aae0262aaedc8a2ad3064ba5480375689b/src/server/repository/assessmentCycle/country/getMany.ts#L33-L41

If last_edit query replaced with `now()`, the platform has noticeably speed boost

**Comment by minotogna** [comment]
@sorja is it correct to consider this a bug ? or is it just an improvement ?

**Comment by minotogna** [comment]
@sorja fixed in #3057
