### ISSUE TITLE
Data tables; show validation error messages in tooltip opening with mouse hover

### ISSUE THREAD

**Issue by minotogna** [openforis/fra-platform#2665]

**Comment by rfontanarosa** [comment]
having some difficulties to use our integrated tooltip:

- it doesn't support html content
- it essentially surround another element, this means that we have to force it to be a td element or make it dynamic
- it will be replicated

I've found this library that should work fine. It is widely used and i think is super optimised.

https://github.com/ReactTooltip/react-tooltip

<img width="1075" alt="Screenshot 2023-05-25 alle 08 30 17" src="https://github.com/openforis/fra-platform/assets/10047945/d6191c6e-89d1-4461-860b-08e423e20318">

**Comment by sorja** [comment]
This library looks good
- small size
- actively development
👍
