### ISSUE TITLE
FRA 2025 landing page not accessible

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#2673]
@minotogna 

Few weeks ago, the landing page of [FRA 2025](https://fra-data.fao.org/assessments/fra/2025) can be opened, while it will auto-direct to FRA 2020 landing page now.

Ps: could be important for Alex as she is working on the Spainish tutorial clips some of which may start from FRA 2025 landing page.

**Comment by sorja** [comment]
@pengchenglai I just tried and it works

Are you logged in?

If you are `not logged in` and `accessing unpublished cycle` you are redirected to `default cycle` (which is 2020)

**Comment by pengchenglai** [comment]
@sorja 

I understand how it works now, but it appears that the FRA 2025 landing home page is publicly accessible at some point(not sure why). I was able to access this page without logging in(see the [video](https://unfao-my.sharepoint.com/:v:/g/personal/pengcheng_lai_fao_org/EWTmh7AtFSZHiCEY-AEnA0UBu2Q0l1UQKmvBtt_Waf45Sw?e=WVAgE4) ). Now Alex want to repeat my previous operation for the Spainish version of tutorial.

**Comment by minotogna** [comment]
@pengchenglai we agreed that in #2422 !!
