### ISSUE TITLE
Jordan calculation error table 1b

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#2695]
@minotogna 

The first row highlighted in red is **Planted forest (b=b1+b2)** while the second red line is **…of which other planted forest (b2)**. The sum of subcategories(0+29.84) is not equal to the total(46.90).

![20230530_145009](https://github.com/openforis/fra-platform/assets/99216009/5fe7876e-0e38-412b-9521-ca8c7ffe64c4)

**Comment by sorja** [comment]
@pengchenglai Was it estimated or was it entered manually?

Entering manually seem to give correct (local version of the platform):
![image](https://github.com/openforis/fra-platform/assets/5508251/40313640-7100-450e-a125-d42790ec0c97)

Testing also the estimation now

**Comment by sorja** [comment]
With estimating with a production database copy (so now my local version of the platform is a copy of the production):

![image](https://github.com/openforis/fra-platform/assets/5508251/3794d7f6-b2f3-4f39-a217-23e736fc468c)

**Comment by pengchenglai** [comment]
@sorja 
Both ways of obtaining the data seem alright. I will inform Örjan. Tks :)

By the way, is the symbol on the left-hand side of the cell indicating the method used to predict the value? For example, this symbol may represent using the "repeat the last" method. It would be helpful if there is a place where users can find the meaning of each symbol corresponding to a specific method in the final production.

**Comment by pengchenglai** [comment]
@sorja 

Why are there values of 0 here? Supposedly, it should be empty.
![242185282-3794d7f6-b2f3-4f39-a217-23e736fc468c](https://github.com/openforis/fra-platform/assets/99216009/5544388e-1d2f-4f34-9632-20712b5558bf)

**Comment by sorja** [comment]
@pengchenglai This is under investigation currently and can be followed here:
https://github.com/openforis/fra-platform/issues/2696

**Comment by pengchenglai** [comment]
@sorja 

I see, thanks!

**Comment by minotogna** [comment]
@pengchenglai users must regenerate the estimation in order to update results. (as per the issue mentioned yesterday evening). please advice if we can close this issue . thank you!

**Comment by pengchenglai** [comment]
@minotogna 
Yes,plz :)
