### ISSUE TITLE
Table 1b repeat last estimation error: Egpyt -> of which introduced species for FRA years(between 1990 and 2025) is missing.

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#2696]
@minotogna 

Table 1a(NDP issue):

NC enter one NDP and want to **repeat latest**(or choose a year to **prefill** as now) to fill the values for FRA years, for example 2025. But failed.

Not sure if this is a general or country-specific issue, plz take a look

**Comment by pengchenglai** [comment]
Table 1b(data immigration issue):

data for **…of which introduced species**  for FRA years(between 1990 and 2020)is missing.

**Comment by minotogna** [comment]
> @minotogna
> 
> Table 1a(NDP issue):
> 
> NC enter one NDP and want to **repeat latest**(or choose a year to **prefill** as now) to fill the values for FRA years, for example 2025. But failed.
> 
> Not sure if this is a general or country-specific issue, plz take a look

@pengchenglai this requires further investigation

**Comment by minotogna** [comment]
> Table 1b(data imigration issue):
> 
> data for **…of which introduced species** for FRA years(between 1990 and 2025)is missing.

@pengchenglai this will have a look. 
@sorja cc let's handle only this case now. 

The first issue mentioned above has to do with failed worker. We need to have a look at the server logs. in fact, in redis, there are a few failed jobs, (e.g. Egypt and Syria). 
we might probably create a sperate issue for that.

**Comment by minotogna** [comment]
@sorja let's check if we need to add a test case for this ?

<img width="1318" alt="image" src="https://github.com/openforis/fra-platform/assets/1138156/321d7e0d-5eb9-405b-a967-63de854efbee">
