### ISSUE TITLE
> Table 1b(data imigration issue):

### ISSUE THREAD

**Issue by minotogna** [openforis/fra-platform#2702]
> Table 1b(data imigration issue):
> 
> data for **…of which introduced species** for FRA years(between 1990 and 2025)is missing.

@pengchenglai this will have a look. 
@sorja cc let's handle only this case now. 

The first issue mentioned above has to do with failed worker. We need to have a look at the server logs. in fact, in redis, there are a few failed jobs, (e.g. Egypt and Syria). 
we might probably create a sperate issue for that.

_Originally posted by @minotogna in https://github.com/openforis/fra-platform/issues/2696#issuecomment-1568806578_

**Comment by minotogna** [comment]
@pengchenglai @sorja 
we're in front of a Error R14 (Memory quota exceeded). I have increased the dyno size on heroku for 50$ a month 👌

however, when investigating @sorja (as you already mentioned to me) 
there's a problematic query with activity_log table we might want to address

<img width="1666" alt="image" src="https://github.com/openforis/fra-platform/assets/1138156/c230e266-ea7d-4f23-a07f-f4386258fcaa">

**Comment by minotogna** [comment]
@pengchenglai this also mean we can't fix the past failed jobs. what's lost is lost. however, when they re generate the estimation, the platform will not fail anymore.

**Comment by pengchenglai** [comment]
@minotogna 
Tks, I will let Örjan know and request NCs to fill the missing data from FRA 2020 if possible.
