### ISSUE TITLE
activity log query issue 

### ISSUE THREAD

**Issue by minotogna** [openforis/fra-platform#2705]
@pengchenglai @sorja 
we're in front of a Error R14 (Memory quota exceeded). I have increased the dyno size on heroku for 50$ a month 👌

however, when investigating @sorja (as you already mentioned to me) 
there's a problematic query with activity_log table we might want to address

<img width="1666" alt="image" src="https://github.com/openforis/fra-platform/assets/1138156/c230e266-ea7d-4f23-a07f-f4386258fcaa">

_Originally posted by @minotogna in https://github.com/openforis/fra-platform/issues/2702#issuecomment-1568864894_

**Comment by sorja** [comment]
related ? / https://github.com/openforis/fra-platform/issues/2658

**Comment by minotogna** [comment]
@sorja I guess we can close this issue?

**Comment by sorja** [comment]
> @sorja I guess we can close this issue?

@minotogna 
Sure
