### ISSUE TITLE
Text box

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#2714]
@minotogna 
When copying and pasting text into the text box, the text should always stay where the cursor is entered.

Not randomly flying to the top or any other place, as shown below:
![Capture](https://github.com/openforis/fra-platform/assets/99216009/aa68beac-2492-440f-b35e-d5e40c3fd1f8)

**Comment by minotogna** [comment]
@pengchenglai cc @rfontanarosa 
We're unable to replicate . Can you please post a video on how to replicate this bug? thank you

**Comment by pengchenglai** [comment]
@minotogna @rfontanarosa 
Example： the first line is _Grov11111111e, N 2004. National report on the state of the forests._ and I want to paste _@pengchenglai cc @rfontanarosa We're unable to replicate . Can you please post a video on how to replicate this bug? thank you_ several times(see video).

Since the second paste, the text would move to the top as below:
[6337a2fb-d37c-4e28-8664-01b4abb0f0e0.webm](https://github.com/openforis/fra-platform/assets/99216009/e92f7fcd-09f5-4c8d-98b9-c1598a955a35)

Kindly let me know if something unclear, thanks!

**Comment by rfontanarosa** [comment]
now I understand. unfortunately it seems that jodit has some issues with html paste. in details, copying html links is not safe, so we configure jodit to rid of them every time the editor loose the focus.

**Comment by minotogna** [comment]
> now I understand. unfortunately it seems that jodit has some issues with html paste. in details, copying html links is not safe, so we configure jodit to rid of them every time the editor loose the focus.

We should close this issue @pengchenglai
