### ISSUE TITLE
Add “Eucalyptus sp” in table 2b

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#2715]
@minotogna 
Table 2b, the in the current list of scientific names we need to add “Eucalyptus sp”

![Screenshot 2023-06-01 130835](https://github.com/openforis/fra-platform/assets/99216009/881268d4-6948-4c01-b55e-4213a5fd4b35)

**Comment by sorja** [comment]
@pengchenglai can we have code and family also for this?

We currently have in this format:

| id | code | family | scientific\_name |
| :--- | :--- | :--- | :--- |
| 1 | 4781 | Platanaceae | Platanus mexicana |
| 2 | 4780 | Platanaceae | Platanus acerifolia |
| 3 | 4782 | Platanaceae | Platanus occidentalis |
| 4 | 4783 | Platanaceae | Platanus orientalis |
| 5 | 4727 | Piperaceae | Piper guineense |
| 6 | 4730 | Piperaceae | Piper nigrum |
| 7 | 4725 | Piperaceae | Piper aduncum |
| 8 | 4732 | Piperaceae | Piper trineuron |
| 9 | 4728 | Piperaceae | Piper longum |
| ... | ... | ...| ... |

**Comment by pengchenglai** [comment]
@sorja 
@rfontanarosa 

This is not an urgent issue. “**Eucalyptus sp**” is basically the collection of all species in the Eucalyptus genus, which belongs to the myrtle family (Myrtaceae).

This issue was proposed as some countries did not specify the species in T2b
