### ISSUE TITLE
Growing stock tables not updated

### ISSUE THREAD

**Issue by minotogna** [openforis/fra-platform#2717]
OJ: Urgent, the growing stock tables (2a) are disconnected. Users should be able to enter either m3/ha or total value and the other is calculated using the forest area in table 1a.

**Comment by minotogna** [comment]
OJ: Looks like something strange has happened in the platform. When user changes forest area in table 1a then the total forest area in table 3a is not updated. I have tried refreshing both T1a and T3a several times. Strange thing is that sometimes one year in T3a is updated but the others not. Appears to be a bit random, I do not understand…

**Comment by sorja** [comment]
> OJ: Looks like something strange has happened in the platform. When user changes forest area in table 1a then the total forest area in table 3a is not updated. I have tried refreshing both T1a and T3a several times. Strange thing is that sometimes one year in T3a is updated but the others not. Appears to be a bit random, I do not understand…

@minotogna This should work ok, could we get more details eg. country iso?
I tested this locally both manual change and estimation.
It is slow, but sooner or later the values update

Estimating the value is noticeably slow, but sooner or later the value is updated for 3a



> OJ: Urgent, the growing stock tables (2a) are disconnected. Users should be able to enter either m3/ha or total value and the other is calculated using the forest area in table 1a.

Only one of the values update, and the next one doesn't reflect the change
The issue is that the values are related to each other most likely, and dont understand that the dependant has updated.
I am trying to find a solution for this now.

**Comment by minotogna** [comment]
> > OJ: Looks like something strange has happened in the platform. When user changes forest area in table 1a then the total forest area in table 3a is not updated. I have tried refreshing both T1a and T3a several times. Strange thing is that sometimes one year in T3a is updated but the others not. Appears to be a bit random, I do not understand…
> 
> 
> 
> @minotogna This should work ok, could we get more details eg. country iso?
> 
> I tested this locally both manual change and estimation.
> 
> It is slow, but sooner or later the values update
> 
> 
> 
> Estimating the value is noticeably slow, but sooner or later the value is updated for 3a
> 
> 
> 
> 
> 
> 
> 
> > OJ: Urgent, the growing stock tables (2a) are disconnected. Users should be able to enter either m3/ha or total value and the other is calculated using the forest area in table 1a.
> 
> 
> 
> Only one of the values update, and the next one doesn't reflect the change
> 
> The issue is that the values are related to each other most likely, and dont understand that the dependant has updated.
> 
> I am trying to find a solution for this now.
> 
> 

When changing 1a or 1b, only totals should be updated

**Comment by minotogna** [comment]
> > OJ: Looks like something strange has happened in the platform. When user changes forest area in table 1a then the total forest area in table 3a is not updated. I have tried refreshing both T1a and T3a several times. Strange thing is that sometimes one year in T3a is updated but the others not. Appears to be a bit random, I do not understand…
> 
> 
> 
> @minotogna This should work ok, could we get more details eg. country iso?
> 
> I tested this locally both manual change and estimation.
> 
> It is slow, but sooner or later the values update
> 
> 
> 
> Estimating the value is noticeably slow, but sooner or later the value is updated for 3a
> 
> 
> 
> 
> 
> 
> 
> > OJ: Urgent, the growing stock tables (2a) are disconnected. Users should be able to enter either m3/ha or total value and the other is calculated using the forest area in table 1a.
> 
> 
> 
> Only one of the values update, and the next one doesn't reflect the change
> 
> The issue is that the values are related to each other most likely, and dont understand that the dependant has updated.
> 
> I am trying to find a solution for this now.
> 
> 

Ask more details to OJ and @pengchenglai  via email

**Comment by pengchenglai** [comment]
@sorja 
Maybe test for Lebanon as Örjan mentioned it takes around 1 h to link table 1 a and 3a

**Comment by sorja** [comment]
@pengchenglai When was this ran? REDIS has been updated recently, and it is likely that the calculations should be much faster now. Could you try?

**Comment by sorja** [comment]
![firefox_WRzxCIKCnl](https://github.com/openforis/fra-platform/assets/5508251/b0675ea0-6a44-437b-8cb6-315c81e05bda)

**Comment by pengchenglai** [comment]
Need to refresh the page for updating the value in T2a
<img width="167" alt="1" src="https://github.com/openforis/fra-platform/assets/99216009/7a649db3-6aec-4163-962d-d00b16a022bb">

**Comment by sorja** [comment]
@pengchenglai can you update if we agreed on something else?

- Calculations are working correctly, they are almost instant if you refresh the page
- Live updates are slow or not working for some reason (investigating)

**Comment by pengchenglai** [comment]
> @pengchenglai can you update if we agreed on something else?
> 
> * Calculations are working correctly, they are almost instant if you refresh the page
> * Live updates are slow or not working for some reason (investigating)

@sorja 

Sure, that is the current situation for table 2c linked with 1a. I will discuss it with Örjan next week to see if there are any new concerns regarding this session.

**Comment by minotogna** [comment]
@pengchenglai i understood from @sorja there's no problem with this. Can we close this issue ?

**Comment by pengchenglai** [comment]
@minotogna 

Yes, plz: just test the update of values in table 2a for the review and found it is working
