### ISSUE TITLE
platfrorm email notifications 

### ISSUE THREAD

**Issue by AlexandraFRA25** [openforis/fra-platform#2728]
I receive the platform notifications in Russian. and not in English to my email. I use the platform in English/Spanish

**Comment by pengchenglai** [comment]
@minotogna 

She means all the notifications she received were in Russian
Example:
![2](https://github.com/openforis/fra-platform/assets/99216009/25451ec3-943e-4013-832d-ec1da5f5869d)

**Comment by minotogna** [comment]
@sorja related to #1491

**Comment by sorja** [comment]
Resolved by https://github.com/openforis/fra-platform/pull/2981
