### ISSUE TITLE
Add translation for tier tables in 1 a & 2a

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#2730]
@minotogna 
@sorja 

Plz check if you have translations of the **footnotes** for the other five languages, otherwise, kindly send us an email for the translation.
<img width="720" alt="1" src="https://github.com/openforis/fra-platform/assets/99216009/d6e57347-3610-4e64-8867-8bbf48c3c82d">

**Comment by sorja** [comment]
Missing translations:

¹ Data not older than 5 years from year of submission of report (2018 or more recent for FRA 2025 country reports)
² Data older than 5 years from year of submission of report (older than 2018 for FRA 2025 country reports)
³ Compatible in terms of methods, categories and definitions used

¹ Data not older than 10 years from year of submission of report (2013 or more recent for FRA 2025 country reports)
² Data older than 10 years from year of submission of report (older than 2013 for FRA 2025 country reports)

**Comment by pengchenglai** [comment]
@sorja 

Could you please send us an email regarding this issue for the missing languages? Thank you!

**Comment by sorja** [comment]
@pengchenglai 
Message has been sent, comment was only for documentation purposes :)

**Comment by sorja** [comment]
@rfontanarosa 
@pengchenglai 

Issue has been divided in corresponding lang issues:
https://github.com/openforis/fra-platform/issues/2735
https://github.com/openforis/fra-platform/issues/2671
