### ISSUE TITLE
Top priority: upload a file in the repository

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#2732]
@minotogna 
@sorja 
@rfontanarosa 

Quote from Örjan: When I upload a file in the repository for one country then it is saved globally under the Links. There needs to be a difference between **Links** (which should be **global**) and the **repository** which should be **country-level** access.

This explains why there is this issue
#2720

**Comment by rfontanarosa** [comment]
already fixed. see https://github.com/openforis/fra-platform/pull/2752

**Comment by pengchenglai** [comment]
@rfontanarosa 

Some old issues needed to be solved
Plz see here https://github.com/openforis/fra-platform/pull/2752#issuecomment-1584210676
