### ISSUE TITLE
FRA tutorial(High priority)

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#2764]
@minotogna 
@sorja 

We could work on the issue #2420 

No.1 - https://youtu.be/JJ5mqdWyKIY

 

No.2 - https://youtu.be/BQVEIUX4x20

 

No.3 - https://youtu.be/SsGXSaNFmH4

 

No.4 - https://youtu.be/m0rOvOcU-0w

 

No.5 - https://youtu.be/DgSzHqk-GDg

 

No.6 - https://youtu.be/CbepficbybI

**Comment by minotogna** [comment]
@pengchenglai is this a different issue than #2420 ? If not , can u please close this and add the links + title (in 5 languages ) + section where to add the videos ?

thank you

**Comment by pengchenglai** [comment]
@minotogna 

This is a reminder for the previous issue since it was on hold two months ago.

Sure, will ask colleagues to add the translation and Cc you in the email

**Comment by minotogna** [comment]
> @minotogna 
> 
> 
> 
> This is a reminder for the previous issue since it was on hold two months ago.
> 
> 
> 
> Sure, will ask colleagues to add the translation and Cc you in the email

It was on hold , because we didn't have the videos

**Comment by pengchenglai** [comment]
@minotogna 

Indeed, now we have them and the request email for translation has been sent.

Video (with translated titles) info can be found [here](https://unfao-my.sharepoint.com/:x:/g/personal/pengcheng_lai_fao_org/EaKdTshlCZ1NlT8q5C_Z2gMBZJ-an9TZeDoBbnHHVl-I1Q?e=mZGx0N) if colleagues have filled them. Videos in French still waits for clearance from OCC at this stage.
