### ISSUE TITLE
[PanEuropean] Update PanEuropean Landing Page

### ISSUE THREAD

**Issue by persas** [openforis/fra-platform#2768]
As per requested in email, the landing page should look now like in the image below.

<img width="688" alt="image" src="https://github.com/openforis/fra-platform/assets/23346350/480310e2-52aa-48a1-82d0-0d042d8168ce">

[2025 Landing Page - June 2023.docx](https://github.com/openforis/fra-platform/files/11745794/2025.Landing.Page.-.June.2023.docx)

**Comment by minotogna** [comment]
@persas any chance to attach the file if they sent it?

**Comment by persas** [comment]
It's already done. I'll open the PR now @minotogna

**Comment by minotogna** [comment]
> It's already done. I'll open the PR now @minotogna 

@persas is this issue still opened ?

**Comment by persas** [comment]
It's done in this PR https://github.com/openforis/fra-platform/pull/2777
