### ISSUE TITLE
Calculation table 1a

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#2778]
@minotogna 
@sorja 

Could you please investigate if it is a rounding issue or another problem? The sum of these three categories exceeds 0.01 compared to the Total land area (c).
![MicrosoftTeams-image](https://github.com/openforis/fra-platform/assets/99216009/e3ae52c8-0e42-42c5-b9a3-3353be7032e5)

**Comment by minotogna** [comment]
> @minotogna @sorja
> 
> Could you please investigate if it is a rounding issue or another problem? The sum of these three categories exceeds 0.01 compared to the Total land area (c). ![MicrosoftTeams-image](https://user-images.githubusercontent.com/99216009/245797024-e3ae52c8-0e42-42c5-b9a3-3353be7032e5.png)

@pengchenglai (cc @rfontanarosa )
the calculation is working. what we see is a rounded result, in fact 
other wooded land = 1.275 => `34 - 17.70 - 1.275 = 15.025` that rounded is `15.03 `
