### ISSUE TITLE
[PanEuropean] Show year in error messages

### ISSUE THREAD

**Issue by atalarczyk** [openforis/fra-platform#2791]
show actual year instead of {{year}}
![image](https://github.com/openforis/fra-platform/assets/23280868/0229f398-727a-416b-9cf0-c91d9e86c305)

**Comment by persas** [comment]
I believe this is solved, but I don't see it in the version uploaded, can you run the migrations @minotogna ??

**Comment by minotogna** [comment]
> I believe this is solved, but I don't see it in the version uploaded, can you run the migrations @minotogna ??

@persas I updated the review instance this morning.

**Comment by minotogna** [comment]
@persas can we close this issue ?

**Comment by persas** [comment]
Yes,
