### ISSUE TITLE
Table 1c: missing same validation check for the last row  / add sub categories validator

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#2803]
@minotogna 
**Rubber wood** does not have the validation check:
![Screenshot 2023-06-26 172915](https://github.com/openforis/fra-platform/assets/99216009/b4659d20-5219-4d7d-85d9-06d3e5f40875)

**Comment by minotogna** [comment]
> @minotogna 
> 
> **Rubber wood** does not have the validation check:
> 
> ![Screenshot 2023-06-26 172915](https://github.com/openforis/fra-platform/assets/99216009/b4659d20-5219-4d7d-85d9-06d3e5f40875)
> 
> 
> 
> 

@pengchenglai What validation should be applied ?

**Comment by pengchenglai** [comment]
@minotogna 

**Rubber wood** does not exceed forest area(1a), same as the one applied to **Bamboos** and **Mangroves**. And the sum of these three classes should not exceed forest area(1a) (**allow +1 unit difference**  ) since each of these categories is the predominant forest type.

**Comment by minotogna** [comment]
@pengchenglai I rename the issue, because it's not fast.
