### ISSUE TITLE
Validation - table 2a Total growing stock

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#2811]
@minotogna 
For the sub-category  **…of which primary forest** and **…of which introduced species**, they should strictly match with their parent class, meaning the value should be smaller or equal to the parent according.

PS: Now it allows +1 unit difference.

<img width="775" alt="1" src="https://github.com/openforis/fra-platform/assets/99216009/34be3ada-fbe4-4a27-bde5-6234957fdf5c">

**Comment by minotogna** [comment]
> @minotogna For the sub-category **…of which primary forest** and **…of which introduced species**, they should strictly match with their parent class, meaning the value should be smaller or equal to the parent according.
> 
> PS: Now it allows +1 unit difference.
> 
> <img alt="1" width="775" src="https://user-images.githubusercontent.com/99216009/249171655-34be3ada-fbe4-4a27-bde5-6234957fdf5c.PNG">

@pengchenglai that's the common threshold applied to all subcategory validations. why should this case be different ?

**Comment by pengchenglai** [comment]
@minotogna 

Plz refer to the email sent to your gmail, which had confirmed by Örjan

**Comment by minotogna** [comment]
> @minotogna 
> 
> 
> 
> Plz refer to the email sent to your gmail, which had confirmed by Örjan

@pengchenglai this change will be applied to all subcategories validators . Ok ?

**Comment by pengchenglai** [comment]
@minotogna 

The ideal is **only** apply to the sub-categories **…of which primary forest** and **…of which introduced species**(table 2a) since they are the only subcatory of their parent, plz not apply to all subcategories validators.

**Comment by minotogna** [comment]
> @minotogna 
> 
> 
> 
> The ideal is **only** apply to the sub-categories **…of which primary forest** and **…of which introduced species**(table 2a) since they are the only subcatory of their parent, plz not apply to all subcategories validators.

@pengchenglai I mean all sub categories validator now have this threshold . Should it be removed in all cases as well ?

**Comment by pengchenglai** [comment]
@minotogna 

I totally understand and please do not remove it for all.

In fact, just to make it more clear, we should make a strict match if there is **only one** subcategory of the parent as it is the **subset**.

Following this rule:
Table 1b **…of which primary forest**
![1](https://github.com/openforis/fra-platform/assets/99216009/b2162929-e87d-4aa6-8645-9619007de708)

Table 2a **…of which primary forest** & **…of which introduced species**
![2](https://github.com/openforis/fra-platform/assets/99216009/c3977c4d-ff35-4cb3-90bf-44114a0037be)

Table 3b **…of which in protected areas**
![3](https://github.com/openforis/fra-platform/assets/99216009/48495cad-7e3f-47dd-85bf-9417c5b975a0)

Table 5b **…of which on forest**
![4](https://github.com/openforis/fra-platform/assets/99216009/0579b92e-0d9b-406b-a234-2cee30214ca8)

should not exceed the parent.

**Comment by pengchenglai** [comment]
Also, keep in mind we still need to keep other reasonable validation: for example, as the one applies to the  **…of which on forest**
![6](https://github.com/openforis/fra-platform/assets/99216009/8e384756-9f7e-4614-adb8-2ec83a585252)

**Comment by minotogna** [comment]
@pengchenglai i'm lost .

Why the threshold in other subcategories validators should remain ,

Subcategories validators sums the subcategories and the value should not exceed the parent. Why other subcategories should have the threshold?

Also , the validation of subcategories gets applied to all sub cells , even if one is empty because the overall sun is greater than the parent . 

It's possible to have multiple validators for each cell.

Please , let's make a generic and easy to understand rule for this ?

**Comment by pengchenglai** [comment]
@minotogna 

There should be **only one generic** rule for this: make a strict match if there is _only one subcategory of the parent_, as it is a subset and must be equal to or smaller than the parent, as mentioned here (https://github.com/openforis/fra-platform/issues/2811#issuecomment-1619968484).

I _am not aware_ and do not remember who has requested to applya common threshold applied for all other subcategory validators. What do you mean by that?

In my idea, it should be case-based if there are more than one variable as they could come from same data source or the different.

**Comment by minotogna** [comment]
> @minotogna
> 
> There should be **only one generic** rule for this: make a strict match if there is _only one subcategory of the parent_, as it is a subset and must be equal to or smaller than the parent, as mentioned here ([#2811 (comment)](https://github.com/openforis/fra-platform/issues/2811#issuecomment-1619968484)).
> 
> I _am not aware_ and do not remember who has requested to applya common threshold applied for all other subcategory validators. What do you mean by that?
> 
> In my idea, it should be case-based if there are more than one variable as they could come from same data source or the different.

@pengchenglai again. why a subcategory it should strictly match if other 'brother' sub categories are null? instead, from what you say, if multiple subcategories are defined no threshold ?
and why only to these specific subcategories ? 
I don't understand. the common threshold exists since the beginning of the platform .
what exactly should we do?
