### ISSUE TITLE
Update repeat last estimation prompt table 1a /1b

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#2812]
@minotogna 

We are using linear interpolation to estimate the values(years) between NDPs(shown in the video).

However, the prompt on the left side of the cells for these values(years) could be misleading as shown with **"Repeat last"**. Discussed with Anne (Örjan is on a break), it would be great if they show as **"Linear"** for the values(years) between NDPs(shown in the video) when using **Repeat last** method .
[be76daea-6463-42af-8fdc-4a5bca7c3841.webm](https://github.com/openforis/fra-platform/assets/99216009/cb12bb54-a050-4a41-bcd2-e42a45f42024)

**Comment by minotogna** [comment]
@pengchenglai this will be misleading . the cell at the moment shows the estimation the user has selected.
if the user will see something different, it might wonder why.
please, advise if you really want that. thank you

**Comment by pengchenglai** [comment]
@minotogna 

After discussing with Örjan, it would be cool we keep as now. Tks : )
