### ISSUE TITLE
Year for data source - Data sources

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#2813]
@minotogna 

We will keep the current options for year selection regarding the **Year for data source** in the Data sources. Meanwhile, we also need to **enable free text entry**. 

Reason for this:
Discussed it with colleagues: it could include several reference years, such as 1999, 2003, and 2017, for a single reference. Alternatively, it could also refer to a period of time, like table 1d.

<img width="748" alt="1" src="https://github.com/openforis/fra-platform/assets/99216009/acc4a3d9-b409-4bf6-b1d0-50846053cca2">

**Comment by minotogna** [comment]
@pengchenglai this will allow entering invalid years. 
but I will do as asked.

**Comment by minotogna** [comment]
@pengchenglai after testing this cannot be allowed. validations are impossible to perform .
do you want to convert this into a multiple options selection ?

**Comment by pengchenglai** [comment]
@minotogna 

In some cases, it will, but as said we need to find a trade-off way to allow entering a period of time

**Comment by pengchenglai** [comment]
> @pengchenglai after testing this cannot be allowed. validations are impossible to perform . do you want to convert this into a multiple options selection ?

@minotogna 
Plz set it as multiple choices for the years and also allow entering a period of time(free text entry). Since it would be bt complicated, we could not set a validation check for this.

**Comment by minotogna** [comment]
> > @pengchenglai after testing this cannot be allowed. validations are impossible to perform . do you want to convert this into a multiple options selection ?
> 
> 
> 
> @minotogna 
> 
> Plz set it as multiple choices for the years and also allow entering a period of time(free text entry). Since it would be bt complicated, we could not set a validation check for this.

@pengchenglai it cannot be both . Do you want free text or multiple choice ?

**Comment by pengchenglai** [comment]
@minotogna 

Free text would be better as mutiple choice is hard to cover all the period which user may enter later on.

**Comment by minotogna** [comment]
> @minotogna 
> 
> 
> 
> Free text would be better as mutiple choice is hard to cover all the period which user may enter later on.

@pengchenglai So no more select with year selection and no validation . Is that correct ?

**Comment by pengchenglai** [comment]
@minotogna 

Correct and agreed by Örjan(See gmail copy)
