### ISSUE TITLE
AR translation - update

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#2821]
@minotogna 
Plz update these [two translations(Severe weather events & clear tables; lines 29 and 30)](https://unfao-my.sharepoint.com/:x:/g/personal/pengcheng_lai_fao_org/ETq_fFvJac1FsFBwdXRqpKkBOzxA1biUt2ZEm3NA0HAjxw?e=oSOBbj).

<img width="240" alt="1" src="https://github.com/openforis/fra-platform/assets/99216009/329a7ca1-6ccb-42aa-bd6b-113da6cc4bc1">

**Comment by minotogna** [comment]
> @minotogna 
> 
> Plz update these [two translations(Severe weather events & clear tables; lines 29 and 30)](https://unfao-my.sharepoint.com/:x:/g/personal/pengcheng_lai_fao_org/ETq_fFvJac1FsFBwdXRqpKkBOzxA1biUt2ZEm3NA0HAjxw?e=oSOBbj).
> 
> 
> 
> <img width="240" alt="1" src="https://github.com/openforis/fra-platform/assets/99216009/329a7ca1-6ccb-42aa-bd6b-113da6cc4bc1">
> 
> 

@pengchenglai i don't have access to official online system . Can u put the content here ?

**Comment by pengchenglai** [comment]
@minotogna 

Sure

[Arabic_translation_issues.xlsx](https://github.com/openforis/fra-platform/files/11895757/Arabic_translation_issues.xlsx)
