### ISSUE TITLE
Missing validation translations

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#2822]
@minotogna 

Table 1b the error prompt is still in Eng, plz double-check if there is a missing translation for AR or other UN languages regarding the error prompts.
![1](https://github.com/openforis/fra-platform/assets/99216009/0a960ed5-fbc6-469b-a594-5d1cf2e917da)

**Comment by minotogna** [comment]
@pengchenglai there are indeed several missing translations. difficult to what has been translated. 
Can u please provide translations in Spanish, French, Arabic, Russian and Chinese for the following:

```
    subCategoryExceedsParent: 'Subcategory exceeds parent',
    forestAreaDoesNotMatchExtentOfForest: "Doesn't match Forest area (1a)",
    remainingLandExceedsExtentOfForest: 'Exceeds Remaining land area (1a)',
    valueMustBePositive: 'Value should be greater than zero',
    valueMustBeYear: 'Value should be a valid year',
    emptyField: 'This field is empty',
    mustBeEqualToTotalGrowingStock: 'The summed value should be equal to the Total Forest',
    countryReportYearGreaterThanCurrentYear: 'Value should be greater or equal than {{minValue}}',
    valueNotGreaterThan: 'Value should be not greater than {{maxValue}}',
    sumNotGreaterThan: 'Sum should not exceed {{maxValue}}',
    notEmpty: 'Value cannot be empty',
    valuesAreInconsistentWithNetChange: 'Values are inconsistent with Forest area net change',
    valuesAreInconsistent1aOr1b: 'Values are inconsistent with Areas reported in tables 1a or 1b',
    mustBeEqualToPrivateOwnership: 'Subcategories sum should be equal to Private Ownership',
    mustBeEqualToForestExpansion: 'Subcategories sum should be equal to Forest Expansion',
    mustBeEqualToPlantedForest: 'Subcategories sum should be equal to Planted Forest',
    mustBeEqualToPrimaryForest: 'Subcategories sum should be equal to Primary Forest',
    mustBeEqualToForestArea: 'Sum of Naturally regenerating forest and Planted forest not equal to the total forest',
    mustBeLessThanPrivateOwnership: 'Subcategories sum should be less than Private Ownership',
    columnEmpty: "Column '$t({{columName}})' must have a value",
    forestSumAreaExceedsExtentOfForest:
      'The sum of the reported FRA categories exceeds the forest area reported in table 1a',
    valueEqualToSum: 'Total value should be equal to sum of subcategories',
    valueEqualToSumParent:
      'The sum of subcategories {{subcategories}} is not equal to {{parentVariable}} {{parentCol}} {{parentTable}} <{{valueRounded}}>',
    landAreaExceedsTotalLandArea: 'Land area exceeds total land area (1a) ({{value}})',
    classValueNotGreaterThan: '{{name}} should be not greater than {{value}}',
    classValuesMustBeEqualTo: '{{name}} sum must be equal to {{value}}',
    valueCannotExceedMaximumValueReportedForForestArea:
      'Value cannot exceed the maximum value ({{maxForestArea}}) reported for forest area (1a)',
    valueCannotExceedMaximumValueReportedForForestAreaYear:
      'The sum of year {{year}} cannot exceed the maximum value ({{maxForestArea}}) reported for forest area (1a)',
    valueCannotExceedMaximumValueReportedForLandArea:
      'Value cannot exceed the maximum value ({{maxLandArea}}) reported for land area (1a)',
    shouldContainAtLeastOneCharacter: 'Value should contain at least one character',
    forestAreaReportedIsDifferentFromPreviousCycle:
      'Reported area ({{forestArea2025}}) differs from previously reported ({{forestArea2020}}). Please provide a comment explaining why it is different.',
```

Please, note content within `{{ }}` and `t()` are dynamic variables and should not be translated

**Comment by pengchenglai** [comment]
@minotogna 

Could you plz confirm this?

So only the content inside the quotation marks needed to be translated(content within {{ }} and t() are dynamic variables and should not be translated).

For instance, we only need to translate:

**'Subcategory exceeds parent',
"Doesn't match Forest area (1a)",
'Exceeds Remaining land area (1a)',**

for the first three rows is that the case?

**Comment by pengchenglai** [comment]
@minotogna 

Fine in this format? I will request colleagues to translate them tomorrow.

[Missing error prompt (1).xlsx](https://github.com/openforis/fra-platform/files/11938613/Missing.error.prompt.1.xlsx)

**Comment by minotogna** [comment]
> @minotogna 
> 
> 
> 
> Fine in this format? I will request colleagues to translate them tomorrow.
> 
> 
> 
> [Missing error prompt (1).xlsx](https://github.com/openforis/fra-platform/files/11938613/Missing.error.prompt.1.xlsx)
> 
> 

@pengchenglai can they use the original text format instead of excel ?

**Comment by pengchenglai** [comment]
> > @minotogna
> > Fine in this format? I will request colleagues to translate them tomorrow.
> > [Missing error prompt (1).xlsx](https://github.com/openforis/fra-platform/files/11938613/Missing.error.prompt.1.xlsx)
> 
> @pengchenglai can they use the original text format instead of excel ?

@minotogna  Would be fine for me, but tricky for other colleagues to understand
