### ISSUE TITLE
Tables 2a Auto-update value

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#2823]
@minotogna 
Plz investigate it: Not always the case that the value which needed to be converted into another unit would be auto-updated(as shown in the video it will need to refresh the webpage), although had discussed it with Miro and tried to solve this issue in #2717.
[12194adb-caaf-4adc-a2a8-6015c942e12f.webm](https://github.com/openforis/fra-platform/assets/99216009/d21ddc54-cbf1-4a37-9ed2-a1ba87de6daf)

**Comment by minotogna** [comment]
@pengchenglai is this still happening ? I can't reproduce this . do you remember if other things were happening in the meantime?

**Comment by pengchenglai** [comment]
> @pengchenglai is this still happening ? I can't reproduce this . do you remember if other things were happening in the meantime?

@minotogna 
Yes, it is still happening and needs to refresh to update the values(see another video). Nothing weird happened at the same time.
[a706670d-1ba5-4d83-bdd6-abcc574f80e0.webm](https://github.com/openforis/fra-platform/assets/99216009/055795b6-73cd-4303-b9c2-29b29eb7112f)
