### ISSUE TITLE
Chatbox NDP 1a/1b no show for messages before refreshing

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#2827]
@minotogna 

In Table 1a/1b, when attempting to enter a message for the data in NDPs, the message would not be displayed as successfully entered until you refresh the page(as video below).

[c45b4c7e-2a69-4d76-8880-fd830746ac42.webm](https://github.com/openforis/fra-platform/assets/99216009/c1676ce9-246b-4513-87e0-e6f79f1d8889)

**Comment by rfontanarosa** [comment]
@pengchenglai hi pencheng, after the refresh, is it working properly? because on fra-data-review it works fine. what is your role in that country?

**Comment by pengchenglai** [comment]
@rfontanarosa 

Ciao Roberto, indeed it works for the review at least for China when the role is NC. However, still not working for **Atlantis 18 as a NC** in the production, and do not know why.
