### ISSUE TITLE
Estimate prompt issue

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#2835]
@minotogna 

There is a big value I manually entered before the latest version update and it shows it derived from the estimation method _Repeat last_ which is a bit weird.
![Screenshot 2023-07-03 141600](https://github.com/openforis/fra-platform/assets/99216009/2df04594-1601-4339-ba5c-eed8defae4fb)

**Comment by minotogna** [comment]
@pengchenglai can u post the link to this cycle/ country / table?

**Comment by pengchenglai** [comment]
@minotogna 
Sure: https://fra-data.fao.org/assessments/fra/2025/X18/sections/forestCharacteristics

![1](https://github.com/openforis/fra-platform/assets/99216009/11c880a8-e725-468c-b00b-6c0ef9f2dbed)

**Comment by minotogna** [comment]
@pengchenglai after investigation I have no idea what happened. in fact, after editing manually a cell, the E goes away.
