### ISSUE TITLE
Missing validation check - table 2a Total growing stock

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#2836]
@minotogna 

No validation check against **Total Forest** when one of these two classes is missing **Naturally regenerating forest** and **Planted forest**.
![1](https://github.com/openforis/fra-platform/assets/99216009/611dccc1-8640-4699-a776-b7d0dfc87d67)
![2](https://github.com/openforis/fra-platform/assets/99216009/a19926d3-8779-4b4a-ac3a-fe467798517a)

**Comment by minotogna** [comment]
Validation error result appears only if both Naturally regenerating forest and Planted forest are filled. It should appear if at least one is filled and the sum of both exceed Total Forest. 
@sorja Use the new validatorSumSubCategoriesNotGreaterThanParent 

https://github.com/openforis/fra-platform/assets/1138156/8affe0f3-4e60-4537-8fb0-222b3752e6e2
