### ISSUE TITLE
Flexible match table 1d Forest area net change (a-b)

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#2838]
@minotogna 
It should also allow -1 difference for the flexible match(± 1 difference).

![4](https://github.com/openforis/fra-platform/assets/99216009/b14c930b-2c89-4ab6-ab1f-29b60ecc747a)
![6](https://github.com/openforis/fra-platform/assets/99216009/5581e32c-e2bd-4822-aa80-bac872095968)

**Comment by minotogna** [comment]
> @minotogna 
> 
> It should also allow -1 difference for the flexible match(± 1 difference).
> 
> 
> 
> ![4](https://github.com/openforis/fra-platform/assets/99216009/b14c930b-2c89-4ab6-ab1f-29b60ecc747a)
> 
> ![6](https://github.com/openforis/fra-platform/assets/99216009/5581e32c-e2bd-4822-aa80-bac872095968)
> 
> 

Sorry @pengchenglai 
What exactly should happen ?

**Comment by pengchenglai** [comment]
@minotogna 

Meaning when the difference of **Forest area net change (a-b)** and **Forest area net change from table 1a** is between -1 and 1, there should no error message. Here -1 still show the error.

**Comment by pengchenglai** [comment]
Test again: no error showing up when the difference of these two variables is greater than 1:
![8](https://github.com/openforis/fra-platform/assets/99216009/528b184c-9022-433c-9e0c-ba224eacf465)

**Comment by minotogna** [comment]
@pengchenglai  in your screenshots I see no error validation triggered on Forest area net change and Forest area net change from table 1a .
is there an issue ?

**Comment by pengchenglai** [comment]
@minotogna 

Yes, that is the issue raised up here(highlighted in yellow) as it should triggered the error validation.
