### ISSUE TITLE
Redirect bug when opening fra different cycles in different browser tabs

### ISSUE THREAD

**Issue by minotogna** [openforis/fra-platform#2841]
@AnssiSamuli 

https://github.com/openforis/fra-platform/assets/1138156/ef2b2730-7346-4a76-8d75-0c507a3a392a

**Comment by minotogna** [comment]
@sorja it is most likely better if we address this issue in the new mega change where we handle multiple assessments. Have a look at what the problem could be first and then we'll decide where to fix this.

**Comment by sorja** [comment]
@minotogna 

Unable to replicate in latest branch (taking exactly same steps as in video)

Can you verify and close?

**Comment by minotogna** [comment]
indeed @sorja . we have automagically fixed it in our current development branch :D
