### ISSUE TITLE
Data download excel files not working

### ISSUE THREAD

**Issue by minotogna** [openforis/fra-platform#2842]
AB: I have issues with the download of FRA 2020 data in the fra 2020 platform (individual xls files, not the bulk download). It does not work and bring me to the home platform page (if disconnected) or to FRA 2025 page (if I’m connected) platform.

**Comment by pengchenglai** [comment]
https://fra-data.fao.org/assessments/fra/2020/WO/dataDownload/

![1](https://github.com/openforis/fra-platform/assets/99216009/5bbde9f6-2434-45c4-86db-ff62ad40671a)

**Comment by pengchenglai** [comment]
It is the repost of #2690
