### ISSUE TITLE
Validations don't trigger correctly on first load

### ISSUE THREAD

**Issue by sorja** [openforis/fra-platform#2844]
https://github.com/openforis/fra-platform/assets/5508251/c0abbe33-83a8-46f5-8b5b-8be217debc75

Weird behavior:
- On first load (or disabling ODPs) the validations don't trigger correctly
- When refreshing page (in video: travelling to 1a and then back to 1b shows validations correctly)

Suspect: 
```
// src/client/pages/AssessmentSection/DataTable/hooks/useValidations.ts:35

        matcher: isAnyOf(
          // AssessmentSectionActions.updateNodeValues.fulfilled,
          DataActions.getTableData.fulfilled,
          DataActions.setNodeCalculations,
          DataActions.setNodeValues
        ),
```

**At this point we could evaluate if we want to move validations directly to Cell.tsx (if cell value changes => validate)**
This would avoid updating store and keep it in local memory

**Comment by minotogna** [comment]
> https://github.com/openforis/fra-platform/assets/5508251/c0abbe33-83a8-46f5-8b5b-8be217debc75
> 
> 
> 
> Weird behavior:
> 
> - On first load (or disabling ODPs) the validations don't trigger correctly
> 
> - When refreshing page (in video: travelling to 1a and then back to 1b shows validations correctly)
> 
> 
> 
> Suspect: 
> 
> ```
> 
> // src/client/pages/AssessmentSection/DataTable/hooks/useValidations.ts:35
> 
> 
> 
>         matcher: isAnyOf(
> 
>           // AssessmentSectionActions.updateNodeValues.fulfilled,
> 
>           DataActions.getTableData.fulfilled,
> 
>           DataActions.setNodeCalculations,
> 
>           DataActions.setNodeValues
> 
>         ),
> 
> ```
> 
> 
> 
> 
> 
> **At this point we could evaluate if we want to move validations directly to Cell.tsx (if cell value changes => validate)**
> 
> This would avoid updating store and keep it in local memory

@sorja you proposed a good solution to try. Can u try it when you have another boring day 😃?
