### ISSUE TITLE
Email in the profile should be fixed

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#2846]
@minotogna 

The email address should be the same as the invitation email and not be editable.
![1](https://github.com/openforis/fra-platform/assets/99216009/c1a5e073-3f85-4cef-88af-f8a406c1d583)

**Comment by minotogna** [comment]
> @minotogna 
> 
> 
> 
> The email address should be the same as the invitation email and not be editable.
> 
> ![1](https://github.com/openforis/fra-platform/assets/99216009/c1a5e073-3f85-4cef-88af-f8a406c1d583)
> 
> 

@pengchenglai Please note the user email can be different from the invitation email when a user has been invited on his google login email but is registered with a different email .

**Comment by pengchenglai** [comment]
> > @minotogna
> > The email address should be the same as the invitation email and not be editable.
> > ![1](https://user-images.githubusercontent.com/99216009/251208010-c1a5e073-3f85-4cef-88af-f8a406c1d583.JPG)
> 
> @pengchenglai Please note the user email can be different from the invitation email when a user has been invited on his google login email but is registered with a different email .

@minotogna  Indeed, would be great just to fix the email address.

**Comment by minotogna** [comment]
> > > @minotogna
> 
> > > The email address should be the same as the invitation email and not be editable.
> 
> > > ![1](https://user-images.githubusercontent.com/99216009/251208010-c1a5e073-3f85-4cef-88af-f8a406c1d583.JPG)
> 
> > 
> 
> > @pengchenglai Please note the user email can be different from the invitation email when a user has been invited on his google login email but is registered with a different email .
> 
> 
> 
> @minotogna  Indeed, would be great just to fix the email address.

@pengchenglai should we allow only admin to edit users email ?

**Comment by pengchenglai** [comment]
> > > > @minotogna
> > 
> > 
> > > > The email address should be the same as the invitation email and not be editable.
> > 
> > 
> > > > ![1](https://user-images.githubusercontent.com/99216009/251208010-c1a5e073-3f85-4cef-88af-f8a406c1d583.JPG)
> > 
> > 
> > > 
> > 
> > 
> > > @pengchenglai Please note the user email can be different from the invitation email when a user has been invited on his google login email but is registered with a different email .
> > 
> > 
> > @minotogna  Indeed, would be great just to fix the email address.
> 
> @pengchenglai should we allow only admin to edit users email ?

@minotogna  Yes, please.
