### ISSUE TITLE
Error message: non-eng letters are not recognized as characters

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#2864]
@minotogna @sorja

In the data source, when the user enters Arabic letters, it shows the errors as below(**value should contain at least one character**):
![1](https://github.com/openforis/fra-platform/assets/99216009/79c828b1-c5b3-4625-bedf-f07b66abae18)

**Comment by pengchenglai** [comment]
![1](https://github.com/openforis/fra-platform/assets/99216009/d7b6fb2f-1456-4ecb-8f7b-ff7f80eded4e)

**Comment by pengchenglai** [comment]
![2](https://github.com/openforis/fra-platform/assets/99216009/ff78258e-28af-436c-866d-f5ceea92cae8)

**Comment by pengchenglai** [comment]
@minotogna 

Plz first solve this medium-priority issue once all high-priority issues have been fixed.

**Comment by pengchenglai** [comment]
@minotogna 

We could remove this validation check at this stage and add it which is applicable for six UN languages whenever possible.

**Comment by sorja** [comment]
https://stackoverflow.com/questions/20690499/concrete-javascript-regular-expression-for-accented-characters-diacritics
