### ISSUE TITLE
Sustainable Development doesn't fetch extent of forest dependency table

### ISSUE THREAD

**Issue by minotogna** [openforis/fra-platform#2879]

**Comment by sorja** [comment]
@minotogna 
Unable to replicate

Accessing this from country landing **or** refreshing the page
http://localhost:9000/assessments/fra/2025/FIN/sections/sustainableDevelopment

results in this store:
![image](https://github.com/openforis/fra-platform/assets/5508251/3e483fdb-915a-4fc3-b559-8eb1f5c14441)

**Comment by minotogna** [comment]
> @minotogna 
> 
> Unable to replicate
> 
> 
> 
> Accessing this from country landing **or** refreshing the page
> 
> http://localhost:9000/assessments/fra/2025/FIN/sections/sustainableDevelopment
> 
> 
> 
> results in this store:
> 
> ![image](https://github.com/openforis/fra-platform/assets/5508251/3e483fdb-915a-4fc3-b559-8eb1f5c14441)
> 
> 

I hardcoded the 1a fetch for now . Can u verify it works without it ?

**Comment by minotogna** [comment]
@sorja See useGetData hook

**Comment by sorja** [comment]
Seems to be ok, I will open a PR without the added extent of forest dependency, can you try when you have time if there is still a  problem? I am unable to replicate
