### ISSUE TITLE
Enhancement - Climatic domains of the Excel calculator show appear in  descending percentage order

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#2886]
@minotogna 
Please auto-reorder the appearance of **climatic domains** in the Excel calculator (2c/2d) based on the **descending percentage values** in table 1a.
Tab 1a:
<img width="729" alt="1" src="https://github.com/openforis/fra-platform/assets/99216009/0e4b530b-a75c-4ae3-80c4-61acccdaf58d">
2c/2d:
<img width="239" alt="2" src="https://github.com/openforis/fra-platform/assets/99216009/1329f4cb-2e1d-4db6-94e8-dc716cf5cc6c">

Reason: This action will help the user to select the right Excel calculator: The current copy area of the Excel calculator does **not show** the Climatic domain used for the calculation (as shown below), which makes it hard to verify the data during the review process if users do not add detailed information in the _Analysis and processing of national data_ area.
<img width="425" alt="0" src="https://github.com/openforis/fra-platform/assets/99216009/86540f6b-a90e-46fd-ba1c-0d84e1490bd6">

**Comment by minotogna** [comment]
@pengchenglai that is a static file ,  not generated in any way from the platform.

**Comment by pengchenglai** [comment]
@minotogna 

Understand this, and there is no point in changing the file for now.

The point here is to automatically update the **appearance order** of the list below with the highest percentage appearing at the top in tab 2c/2d, so for each country, the list order might be different.
![MicrosoftTeams-image](https://github.com/openforis/fra-platform/assets/99216009/00be43f6-956b-4cbc-9812-11d60bba92e8)

For example:
In tab 1a:
<img width="729" alt="1" src="https://github.com/openforis/fra-platform/assets/99216009/0e4b530b-a75c-4ae3-80c4-61acccdaf58d">
the order of the list should be Sub-tropical, Tropical, Boreal, Temperate(the last two can be swapped in this case)

**Comment by pengchenglai** [comment]
It would be considered a medium priority if it could be implemented. Tks!

**Comment by minotogna** [comment]
@pengchenglai ok got it! I misunderstood the issue in the first instance .
