### ISSUE TITLE
Enhancement - PREFERRED WAY OF CONTACTING(profile)

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#2887]
@minotogna 

Not sure what does second "**Choose**"(in grey) mean in PREFERRED WAY OF CONTACTING of the profile setting.
![1](https://github.com/openforis/fra-platform/assets/99216009/fa9b0951-a078-407d-8b1f-118a2576bfcd)

Consider this as **quite low priority** if we need to remove the second  "**Choose**".

**Comment by minotogna** [comment]
@pengchenglai it was asked to us to let the user choose 2 ways of being contacted .
The second is disabled until the the first is selected .

**Comment by pengchenglai** [comment]
@minotogna 

Right and the second option seems not working even  if the first one is selected
<img width="458" alt="2" src="https://github.com/openforis/fra-platform/assets/99216009/99103ad7-7f3a-4352-b001-bf1f99116c43">

**Comment by sorja** [comment]
Supports only primary and secondary phone

Hidden if selection is other than pm
