### ISSUE TITLE
Validation check 1d

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#2890]
@minotogna 

Only the first column has been highlighted not the others do not sure if it is the delay or the missing the validation. Plz double check, tks!

<img width="791" alt="10" src="https://github.com/openforis/fra-platform/assets/99216009/b982e71b-c520-4e9f-bd8a-2a5e890ec053">

**Comment by pengchenglai** [comment]
Consider as medium-high priority

**Comment by minotogna** [comment]
@pengchenglai the validation seems to be working fine

**Comment by pengchenglai** [comment]
@minotogna 

Why is only the first mismatch highlighted, while the other four mismatches are shown as normal?
![1](https://github.com/openforis/fra-platform/assets/99216009/1edcca63-9c3b-4934-90bc-0235819abd15)

**Comment by pengchenglai** [comment]
@minotogna

The first issue have been posted here(I forget😂):https://github.com/openforis/fra-platform/issues/2838#issuecomment-1621462289

Another issue is that validation check is not valid for Forest expansion (a=a1+a2) which should equal to _…of which afforestation (a1)_ + …of which natural expansion (a2) when a=0,a1=a2=1
![1](https://github.com/openforis/fra-platform/assets/99216009/f158720e-352b-470c-8899-5067b4e24b15)

**Comment by pengchenglai** [comment]
@minotogna 

Seems each column have different validation check: if one of a1 or a2 is missing, the validation for whether Forest expansion (a=a1+a2) = …of which afforestation (a1) + …of which natural expansion (a2) should be deactivited.
![4](https://github.com/openforis/fra-platform/assets/99216009/7e902d34-2ab8-4f08-9668-e91b8eaf18c5)

**Comment by pengchenglai** [comment]
@minotogna 

These are the issues exist before the update
