### ISSUE TITLE
Prefilled data- Total -  Primary forest by climatic domain(tab 1b)

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#2893]
@minotogna 

The data source for the **Total** of the _Primary forest by climatic domain_ is from FRA 2020, explaining why 2025 data is missing. Not sure why the data source is not from the first table-FRA 2025.

One more concern is that the validation check is activated and highlights the **Total** even though there is no data entry.

![1](https://github.com/openforis/fra-platform/assets/99216009/13a49ee0-d238-40c0-9730-6e2f12a9e491)
![2](https://github.com/openforis/fra-platform/assets/99216009/25ea0d35-ccec-45c2-a0a5-20d08f889297)

**Comment by minotogna** [comment]
@pengchenglai 
> The data source for the Total of the Primary forest by climatic domain is from FRA 2020, explaining why 2025 data is missing. Not sure why the data source is not from the first table-FRA 2025.

Is this the case in production? Please note, here data might be different because during testing might have changed. 

> One more concern is that the validation check is activated and highlights the Total even though there is no data entry.

Is it the same in production? If yes, it's an issue already existing, and it will be fixed separately .

**Comment by minotogna** [comment]
> @pengchenglai
> 
> > The data source for the Total of the Primary forest by climatic domain is from FRA 2020, explaining why 2025 data is missing. Not sure why the data source is not from the first table-FRA 2025.
> 
> Is this the case in production? Please note, here data might be different because during testing might have changed.
> 
> > One more concern is that the validation check is activated and highlights the Total even though there is no data entry.
> 
> Is it the same in production? If yes, it's an issue already existing, and it will be fixed separately .

I confirm point 2 already exists in production. it will be address as separate issue, not part of the big performance updates

**Comment by sorja** [comment]
@pengchenglai 
Section `1b`
Table `Primary forest by climatic domain`
Variable `Total`

Did I understand correctly that this value should be taken from above table?
We currently have the formula

```
primaryForestBoreal + primaryForestTemperate + primaryForestSubTropical + primaryForestTropical
```

but would it make more sense to take the value from above table?

**Comment by pengchenglai** [comment]
@sorja 

Yes, that is the concern for this variable `Total` as the value should be taken from the `…of which primary forest` in the above table. 

PS: In the case of all values for `primaryForestBoreal, primaryForestTemperate, primaryForestSubTropical, and primaryForestTropical ` are avaliable, use the `Total` value to check if it is equal to `primaryForestBoreal + primaryForestTemperate + primaryForestSubTropical + primaryForestTropical` and highlisght it if there is a difference.

**Comment by sorja** [comment]
@pengchenglai 
@minotogna 

I am highlighting in this message what will be implemented so it's easier for me to follow.
If you disagree or want something differently, let me know:

- [ ] Total calculation = calculated from current table (table2)
- [ ] Total validation = against above table (table1)
- [ ] Extra feature: OJ: _It could be further improved so that if the sum of the subcategory (e g tropical) is the same as the total the we could generate 0 (zeroes) for all the other domains (e g boreal, temperate, etc)_


Thanks,

**Comment by pengchenglai** [comment]
@sorja 

Sounds reasonable! Thank you:)

Regarding point 3, as we allow for a ±1 unit difference to account for rounding and other issues(point 2), if zeros are generated, they should also be changeable. For example, one could re-enter 0.01 for **…of which boreal primary forest**(to replace 0) in 2025.
![1](https://github.com/openforis/fra-platform/assets/99216009/6e1248a8-1eed-4a59-a58a-5e92d9bf9573)
