### ISSUE TITLE
Enhancement- unknown should show as 0.00 - tab 4a

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#2895]
@minotogna 
When the **unknown**(d) is 0.00, it should show the value 0.00 in tab 4a instead of being empty.

Tab 1a:
![2](https://github.com/openforis/fra-platform/assets/99216009/4686d309-d474-4c90-bdcf-f68315f0dff5)
Tab 4a:
![1](https://github.com/openforis/fra-platform/assets/99216009/da0c6af0-a55e-497f-8c31-5585f5fb6b51)

**Comment by pengchenglai** [comment]
@minotogna @sorja @rfontanarosa 

This is a high priority issue now, plz fix it asap. Tks!

**Comment by sorja** [comment]
@pengchenglai please always include the country of the screenshots

**Comment by pengchenglai** [comment]
@sorja 

Sure, China in the review

<img width="949" alt="1" src="https://github.com/openforis/fra-platform/assets/99216009/58ae6dee-b8c9-49f8-946f-ed6133c23d3d">
