### ISSUE TITLE
Translation(Spanish)

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#2906]
@minotogna @AlexandraFRA25 
**Is your feature request related to a problem? Please describe.**
Update the Spanish translation for hours/days/weeks ago
![1](https://github.com/openforis/fra-platform/assets/99216009/d8d81d48-bb77-483d-90d2-2ff99eb122d8)
![2](https://github.com/openforis/fra-platform/assets/99216009/725298de-8027-4abf-975e-4615fba5653b)
![3](https://github.com/openforis/fra-platform/assets/99216009/eb12defe-d268-478f-a402-ce2fc7f82070)

**Describe the solution you'd like**
X _hours ago_ should be **Hace** X **hora**;
X _days ago_ should be **Hace** X **días**;
X _weeks ago_ should be **Hace** X **semana**.

**Comment by AlexandraFRA25** [comment]
Hi colleagues,

I think the following solution will work better

Describe the solution you'd like
X hours ago should be Hace X horas;
X days ago should be Hace X días;
X weeks ago should be Hace X semanas.
1 hour ago -  Hace 1 hora
1 day ago – Hace 1 día
1 week ago – Hace 1 semana
From: pengchenglai <notifica
***@***.***>
Sent: 04 August 2023 10:07
To: openforis/fra-platform ***@***.***>
Cc: Zmachynskaya, Alexandra (NFO) ***@***.***>; Mention ***@***.***>
Subject: [openforis/fra-platform] Translation(Spanish) (Issue #2906)


@minotogna<https://github.com/minotogna> @AlexandraFRA25<https://github.com/AlexandraFRA25>
Is your feature request related to a problem? Please describe.
Update the Spanish translation for hours/days/weeks ago
[1]<https://user-images.githubusercontent.com/99216009/258359572-d8d81d48-bb77-483d-90d2-2ff99eb122d8.JPG>
[2]<https://user-images.githubusercontent.com/99216009/258359596-725298de-8027-4abf-975e-4615fba5653b.JPG>
[3]<https://user-images.githubusercontent.com/99216009/258360851-eb12defe-d268-478f-a402-ce2fc7f82070.JPG>

Describe the solution you'd like
X hours ago should be Hace X hora;
X days ago should be Hace X días;
X weeks ago should be Hace X semana.
