### ISSUE TITLE
User edit required personal info: several popup waring 

### ISSUE THREAD

**Issue by minotogna** [openforis/fra-platform#2930]
**Describe the bug**
While the user edits its required personal info, several popup waring **Please complete your personal information before continuing** appears

**To Reproduce**
1. Go to a country and invite a NC/ANC/C
2. Go to invitation page and accept invitation 
4. Enter the data

**Expected behavior**
Only one  popup waring  **Please complete your personal information before continuing** should appear when accessing the page should appear 

**Screenshots**

https://github.com/openforis/fra-platform/assets/1138156/e50beffb-e52a-46ad-83e9-7d77245f2f67

**Comment by sorja** [comment]
@minotogna 
Unable to replicate with Firefox and Chrome

Can you verify this still exists in latest development?

**Comment by minotogna** [comment]
> @minotogna Unable to replicate with Firefox and Chrome
> 
> Can you verify this still exists in latest development?

@sorja just tested on review, and it doesn't happen
