### ISSUE TITLE
Reviewer should able to see the PREFERRED WAY OF CONTACTING

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#2940]
@minotogna 
**Is your feature request related to a problem? Please describe.**
Reviewers cannot see the PREFERRED WAY OF CONTACTING for NCs and collaborators, which could be improved for better communication during the review process.
![1](https://github.com/openforis/fra-platform/assets/99216009/4cf60e3d-db7b-49f0-be7e-f249b217ef5e)

**Describe the solution you'd like**
Add one more section to the panel, titled **Preferred Way of Contacting** in the Dashboard (as highlighted in yellow), which is only visible to **reviewers and admins**.
![1](https://github.com/openforis/fra-platform/assets/99216009/46b0661f-504e-4ec6-aad7-e2e195094304)

**Describe alternatives you've considered**
Additionlly, we could add **Preferred Way of Contacting** in the _Manage collaborators_(as highlighted in yellow) for **NCs**.
![Capture2](https://github.com/openforis/fra-platform/assets/99216009/03b71e27-12d9-4bf0-b137-16faacbb0a43)

**Comment by minotogna** [comment]
@pengchenglai i wouldn’t add a new section as user informations can be found under manage collaborators one .

proposed solutions 
1. Add a new column in the table 
2. Open user info page through a link (the same that admin uses to edit user ) but for reviewers will be in read only mode .

I prefer # 2.
Please let me know what you think

**Comment by pengchenglai** [comment]
@minotogna 

Yes, the second solution is better. Anyway, we just need a way to find preferred contact methods of NCs, alternate NCs, and collaborators for reviewers.

**Comment by sorja** [comment]
@sorja Note to self:


Reviewer can VIEW ONLY (Read only)

Reviewer can only see C, NC, ANC

Can't see other reviewers
