### ISSUE TITLE
User invitation: wrong assessment redirect after accepting invitation 

### ISSUE THREAD

**Issue by minotogna** [openforis/fra-platform#2944]
**Describe the bug**
User has been invited to panEuropean Cyprus and after having accepted the invitation it gets redirected to fra 2025 landing page .

**To Reproduce**
1. Go to a country and invite a user NC or C or ANC
2. Copy the invitation link and open a new browser to accept invitation.
3. Click on accept invitation 
4. See user has been redirected to fra 2025

**Expected behavior**
At step 4, user should be redirected to invited assessment / cycle / country page

**Video**

https://github.com/openforis/fra-platform/assets/1138156/23118775-c8b0-43aa-a477-1b060b726bca

**Comment by sorja** [comment]
- accept invitation / login (local, google) => country (last invited country role)
- move useUserRedirect to country and check for country role not latest role

**Comment by sorja** [comment]
Admin login:
Last cycle of default assessment
