### ISSUE TITLE
High priority: Page turns blank when switching between countries

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#2976]
@minotogna 

**Describe the bug**
When switching between countries, reviewers/admins need to refresh the page to access the next country.

**To Reproduce**
See video below:
[3d84bc01-8f51-4505-9abd-e881975c5849.webm](https://github.com/openforis/fra-platform/assets/99216009/de06b1a3-339a-44b4-8413-48ce8571f2c2)

https://github.com/openforis/fra-platform/assets/99216009/de06b1a3-339a-44b4-8413-48ce8571f2c2

**Expected behavior**
No need to refresh the page to switch between countries.

**Priority**
High

**Comment by minotogna** [comment]
@pengchenglai in the bug template there are steps to fill , especially the go to '' where we would highly appreciate if you post the url and describe the steps 
Thank you 😊

**Comment by minotogna** [comment]
@pengchenglai this might have already been fixed in review. can u please verify ? thank you

**Comment by pengchenglai** [comment]
> @pengchenglai this might have already been fixed in review. can u please verify ? thank you

@minotogna 

I only have one country in the review. Could you plz send invitations to my fao email for some  countries in the review?

Tks!

**Comment by minotogna** [comment]
> > @pengchenglai this might have already been fixed in review. can u please verify ? thank you
> 
> 
> 
> @minotogna 
> 
> 
> 
> I only have one country in the review. Could you plz send invitations to my fao email for some  countries in the review?

@pengchenglai you are now admin on review instance . Feel free to invite anyone . Please note on review emails are disabled

**Comment by pengchenglai** [comment]
@minotogna 

Great, thank you!

But I am not sure how it works: I use fao email to log in and it seems I am still the NC
![1](https://github.com/openforis/fra-platform/assets/99216009/5d3c2339-a1e5-4796-8960-c7d02cc1b7c2)

**Comment by minotogna** [comment]
> @minotogna 
> 
> 
> 
> Great, thank you!
> 
> 
> 
> But I am not sure how it works: I use fao email to log in and it seems I am still the NC
> 
> ![1](https://github.com/openforis/fra-platform/assets/99216009/5d3c2339-a1e5-4796-8960-c7d02cc1b7c2)
> 
> 

@pengchenglai are you on review ? I don't see your fao email there

**Comment by pengchenglai** [comment]
@minotogna 
Yes, I am. Just sent you a message in Slack, tks!

**Comment by pengchenglai** [comment]
@minotogna 

That is right: it has been fixed, thanks!


[10911ae5-4062-403f-92c5-2bcebfea5b6c.webm](https://github.com/openforis/fra-platform/assets/99216009/859e699e-38ac-478a-9292-216282f57abc)

https://github.com/openforis/fra-platform/assets/99216009/859e699e-38ac-478a-9292-216282f57abc

**Comment by pengchenglai** [comment]
@minotogna 

Could you plz deploy the change as some countries have mentioned this issue?

Thank you :)

**Comment by minotogna** [comment]
> @minotogna 
> 
> 
> 
> Could you plz deploy the change as some countries have mentioned this issue?
> 
> 
> 
> Thank you :)

@pengchenglai sure. As soon as there's no traffic in prod I will update it

**Comment by minotogna** [comment]
> @minotogna 
> 
> 
> 
> Could you plz deploy the change as some countries have mentioned this issue?
> 
> 
> 
> Thank you :)

Production just updated @pengchenglai . Yesterday ARG was on fire all day 😅😊
