### ISSUE TITLE
Make comments that reviewers receive the notification

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#2978]
@minotogna 

**Describe the bug**
Chiara receives the notification when making comments(to the **Comments** area) to the **Bahamas** report in the **production**.

**Screenshot**
![1](https://github.com/openforis/fra-platform/assets/99216009/f88545f4-904c-48d9-8f04-5aecd881a02e) 

**To Reproduce**
 Not sure as I tried to replicate it(in the **review**), but it doesn't work in the same way (no messages were sent to NC, aNCs, or reviewers in my case for China). Could you please double-check for **Bahamas in the production**?

**Expected behavior**
1. For _comments_, the notification should **NOT** be sent to _anyone_ as previously agreed.
2. _Reviewers_ should _not_ receive the notification when they are the person sending the message, instead the **NCs** and **aNCs** should receive it. Likewise, NC or aNCs send a message in the message board, reviewer(s) should receive the notification not the sender.

**Comment by pengchenglai** [comment]
Note this is for the **Comments area, not the message board**

**Comment by minotogna** [comment]
This is strange . Unable to replicate .
Please double check this issue is still valid

**Comment by pengchenglai** [comment]
Me neither for the latest update, seems not an issue closing for now.
