### ISSUE TITLE
High priority - no notification was sent when leaving messages in the message board

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#2979]
@minotogna 
**Describe the bug**
The email of NC did not receive the notification when a message was left in the message board for **China in the review**( as an example).

**To Reproduce**
1. Log in as a reviewer
2. Send a message to the NC of China in the message board(NC did not open the platform at the meantime)
3. Check the email box of the NC
4. No email notification, including Spam(even after few hours)

**Expected behavior**
NC of China should receive the email notification

**Screenshots**
![1](https://github.com/openforis/fra-platform/assets/99216009/cac7e27f-e17d-462b-afc6-1c09a081d644)
![Capture](https://github.com/openforis/fra-platform/assets/99216009/9039daf8-ca3a-42bc-9463-59954bd4ea10)

**Priority**
High

**Comment by minotogna** [comment]
Already fixed . Please double check in production, just deployed

**Comment by pengchenglai** [comment]
@minotogna 

Great, could you plz invite my fao email as the reviewer for Atlantis 18 in the production? I could have a try for this issue and #2978.

Thank you!

**Comment by pengchenglai** [comment]
Orjan just invited me, tks!

**Comment by pengchenglai** [comment]
Works great!
