### ISSUE TITLE
High priority - remove Table data contains errors from table 1a warning

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#2982]
@minotogna 
**Is your feature request related to a problem? Please describe.**
As discussed during the latest FRA meeting,  we decided to remove **Table data contains errors** for the warning in tab 1a as it could be a bit confusing.

**Screenshots**
Remove  **Table data contains errors** (highlighted with a green underline)
![MicrosoftTeams-image](https://github.com/openforis/fra-platform/assets/99216009/afdb65c0-14a0-4491-9184-0ede41adf370)

**Comment by minotogna** [comment]
> @minotogna 
> 
> **Is your feature request related to a problem? Please describe.**
> 
> As discussed during the latest FRA meeting,  we decided to remove **Table data contains errors** for the warning in tab 1a as it could be a bit confusing.
> 
> 
> 
> **Screenshots**
> 
> Remove  **Table data contains errors** (highlighted with a green underline)
> 
> ![MicrosoftTeams-image](https://github.com/openforis/fra-platform/assets/99216009/afdb65c0-14a0-4491-9184-0ede41adf370)
> 
> 
> 
> 

@pengchenglai should the text be removed to all tables or only 1a? From what you wrote it seems only 1a

**Comment by pengchenglai** [comment]
@minotogna 

Yes, only for table 1a which mainly concerns the forest area here as NC would consider they have to report the exact same data as for FRA 2020 to avoid the error(message).

**Comment by minotogna** [comment]
> @minotogna 
> 
> 
> 
> Yes, only for table 1a which mainly concerns the forest area here as NC would consider they have to report the exact same data as for FRA 2020 to avoid the error(message).

@pengchenglai please note that sentence will be removed even if there are other errors in table 1a.

**Comment by pengchenglai** [comment]
@minotogna 

Understand. Well, it will still work since the cells with issues would be still highlighted in red and people would notice them. Thank you!

**Comment by minotogna** [comment]
Only ´Data tables contains error’ should be hidden , not the rest of the sentence
