### ISSUE TITLE
Error message when send a message in the message board in the production

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#2983]
@minotogna 
**Describe the bug**
See the screenshot, plz double check if there is an issue.

**To Reproduce**
1. Invited as the reviewer for Atlantis 18
2. Send a message to the NC

**Screenshots**
![1](https://github.com/openforis/fra-platform/assets/99216009/7fcaf57d-f4b8-4339-b766-6265701c7283)

**Comment by minotogna** [comment]
> @minotogna 
> 
> **Describe the bug**
> 
> See the screenshot, plz double check if there is an issue.
> 
> 
> 
> **To Reproduce**
> 
> Steps to reproduce the behavior:
> 
> 1. Invited as the reviewer for Atlantis 18
> 
> 2. Send a message to the NC
> 
> 
> 
> **Screenshots**
> 
> <img width="953" alt="1" src="https://github.com/openforis/fra-platform/assets/99216009/1c25c1d5-550f-4786-81a2-93ada3b74066">
> 
> 
> 
> 

@pengchenglai what's the issue sorry ?

**Comment by pengchenglai** [comment]
@minotogna 

duplicate key......

This one what does it means

**Comment by minotogna** [comment]
> @minotogna 
> 
> 
> 
> duplicate key......
> 
> 
> 
> This one what does it means

@pengchenglai i meant I can't replicate without instructions or video . Can you please elaborate more ? Thank you

**Comment by pengchenglai** [comment]
@minotogna 

Weird, I cannot reproduce it either. Closing it for now. Thanks!

**Comment by minotogna** [comment]
> @minotogna 
> 
> 
> 
> Weird, I cannot reproduce it either. Closing it for now. Thanks!

@pengchenglai ok 👍
