### ISSUE TITLE
High priority - missing data in FRA_years csv file 

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#2988]
@minotogna 

**Describe the bug**
Data for FRA years are missing 

**To Reproduce**
1. Go to 'https://fra-data.fao.org/assessments/fra/2020/WO/data-download/'
2. Click on 'Bulk Download
[ZIP](https://fra-data.fao.org/api/file/bulk-download?assessmentName=fra&cycleName=2020&countryIso=WO)
3. Unzip the file
4.  Open FRA_years csv file 
![1](https://github.com/openforis/fra-platform/assets/99216009/ad62f1a4-293f-4b35-b92b-0681f53d613e)

**Expected behavior**
With data from the platform
![2](https://github.com/openforis/fra-platform/assets/99216009/24a9e9ed-244d-47b4-8cb2-abd29dd6ec63)

**Screenshots**
current issue:
![1](https://github.com/openforis/fra-platform/assets/99216009/09cf4848-92d8-4f5f-8995-d362bfb8107c)

**Comment by minotogna** [comment]
Resolved by #2987
