### ISSUE TITLE
Fix the country in the user profile

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#2994]
@minotogna 
**Is your feature request related to a problem? Please describe.**
There is a country info in the user profile, which can be changed into any other country from the list.

**Describe the solution you'd like**
Fix the country(as it should be) in the user profile.
![1](https://github.com/openforis/fra-platform/assets/99216009/a5420a2f-9581-4cae-ae92-6e917365cf40)

**Priority**
Very low

**Comment by minotogna** [comment]
@pengchenglai unable to replicate. please provide a video

**Comment by minotogna** [comment]
@pengchenglai it works.
https://github.com/openforis/fra-platform/assets/1138156/2ce4d779-b3fa-43b0-91ba-4e172bac2db1

**Comment by minotogna** [comment]
@pengchenglai the country form input, is the country of user's address. this was requested.
Not sure I fully understand this issue.
Please advice

**Comment by pengchenglai** [comment]
@minotogna 

Great, now I understand the purpose. Plz help to remove Atlantis(1-20) countries from the list if possible.

![1](https://github.com/openforis/fra-platform/assets/99216009/4bbc40a0-a347-4107-924b-d0aba3b64eda)

**Comment by minotogna** [comment]
> @minotogna 
> 
> 
> 
> Great, now I understand the purpose. Plz help to remove Atlantis(1-20) countries from the list if possible.
> 
> 
> 
> ![1](https://github.com/openforis/fra-platform/assets/99216009/4bbc40a0-a347-4107-924b-d0aba3b64eda)
> 
> 
> 
>  

@pengchenglai Atlantis has been requested to be part of the assessment Fra 2025.
We either completely remove it or we don't .

**Comment by pengchenglai** [comment]
Then we will keep them
