### ISSUE TITLE
High priority - Upload a file in the links and the last previous file is removed

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#2996]
@minotogna 

**Describe the bug**
Upload a new file in the links and the last previous file is removed or replaced. Not sure what exactly has happened, plz investigate it and **upload the file** ([**GeospatialToolsGuidelines.pdf**](https://fra-data.review.fao.org/api/file/assessment/0d1ed701-8a6e-44f8-84de-3c75f76141ae?countryIso=AFG&assessmentName=fra&cycleName=2025)) in the production.

**To Reproduce**
1. Upload a new file([INBAR estimates of bamboo areas.xlsx](https://fra-data.fao.org/api/file/assessment/783d9774-f1c5-440a-853b-83b1c4739c32?countryIso=KAZ&assessmentName=fra&cycleName=2025)) in the links(as the admin in the production)
2. Last file is gone([GeospatialToolsGuidelines.pdf](https://fra-data.review.fao.org/api/file/assessment/0d1ed701-8a6e-44f8-84de-3c75f76141ae?countryIso=AFG&assessmentName=fra&cycleName=2025))

**Expected behavior**
Do not remove or replace the last previous file when uploading a new file.

**Screenshots**
In the Review:
![1](https://github.com/openforis/fra-platform/assets/99216009/daf12781-03b5-460a-9bc8-b8fcb73b5f33)

In the Production:
![2](https://github.com/openforis/fra-platform/assets/99216009/8d74bce8-45f3-4df8-906e-9e450e40f332)

**Priority**
High

**Comment by minotogna** [comment]
@pengchenglai I just uploaded the files and it worked. I couldn't replicate it.
 Please provide a video if you still have an issues.

**Comment by pengchenglai** [comment]
@minotogna 

Will let you know if the issue appears again since I only saw the result of the previous operation(not sure about the cause).
