### ISSUE TITLE
High priority - Error messages are printed out for FRA 2020 report

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#2999]
@minotogna 
**Describe the bug**
Error messages are printed out for FRA 2020 report.

**To Reproduce**
Example of Benin:
1.Go to https://fra-data.fao.org/assessments/fra/2020/BEN/print/
2.Check 1b

**Expected behavior**
Errors should be hidden for the public access.

**Screenshots**
![1](https://github.com/openforis/fra-platform/assets/99216009/46ab80e6-e824-4562-be1d-8e31427dd0a6)

**Comment by pengchenglai** [comment]
PS:

It seems to take quite some time to fetch the data (more than three minutes for me) and also shows errors.

**Comment by minotogna** [comment]
- [ ] Errors should be visible as tooltip (when user is logged in and has edit permissions)
- [x] Errors should never be visible in print view and when there's no user logged in

@pengchenglai regarding speed it's really a combination of internet / computer performances. 
we'll address this later on.
