### ISSUE TITLE
Country navigation panel - not always direct to the last selection

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#3012]
@minotogna 

**Describe the bug**
FRA 2025 navigation pane when I select a country and then go back to select another country then the list always starts from the top. It would be good if the list started from the last country selected instead. Think that it is in that way for the Pan-European reporting

**To Reproduce**
Steps to reproduce the behavior (example of Pan-European reporting):
1. Select a country from the country navigation panel
See the videos below:
[55f79f24-6de2-40b0-b356-2b952fd0e69a.webm](https://github.com/openforis/fra-platform/assets/99216009/40631f8a-0938-4c7c-beb5-b268860e683f)

https://github.com/openforis/fra-platform/assets/99216009/40631f8a-0938-4c7c-beb5-b268860e683f

**Comment by minotogna** [comment]
@pengchenglai can you please mention operating system and browser? thank you

**Comment by pengchenglai** [comment]
@minotogna 

Win 10 and Chrome.

**Comment by sorja** [comment]
@pengchenglai could you be so kind to email me the videos?
I am unable to view the videos

I tried the steps you posted, did I replicate incorrect?

![chrome_txySseyaNn](https://github.com/openforis/fra-platform/assets/5508251/7a7868ff-5254-4b83-96ea-72729f5702df)

**Comment by pengchenglai** [comment]
@minotogna 

Just send you the video and FRA 2025 seems ok. Plz try with the pan-European(FRA 2020).

**Comment by sorja** [comment]
@pengchenglai 

![chrome_gnQtzubEYq](https://github.com/openforis/fra-platform/assets/5508251/5dc40a03-2ff3-494b-9931-e5482033e90f)

**Comment by pengchenglai** [comment]
@sorja 

I tried it seems still same for me if I open one table of a country and switch into another for FRA 2020 and pan-EU.

PS: Just send you the email.

**Comment by minotogna** [comment]
@pengchenglai which version of Chrome are you using ?
Also, can you please inspect the browser and see if any message appears? (right click in the page and select inspect)

**Comment by pengchenglai** [comment]
@minotogna @sorja 
I just tested FRA 2025 again, and it works perfectly for me without any delays or lack of reaction when jumping to the country from the selection list. However, the issue still exists for FRA 2020 and pan-EU (please see the video I sent).

I am using the latest version of Chrome. Yes, I do have some warnings and messages that appear(see below).
![1](https://github.com/openforis/fra-platform/assets/99216009/1a45c24e-f80b-4b17-99b8-a13ca3443fb0)
![2](https://github.com/openforis/fra-platform/assets/99216009/db35bd99-9abd-4f1c-bdee-e54210088549)
![3](https://github.com/openforis/fra-platform/assets/99216009/aea128a6-1f1d-4475-be0e-0ed27077a26f)

**Comment by minotogna** [comment]
@pengchenglai this is very strange. not sure what's happening. does it happen on all computers at HQ ?

**Comment by pengchenglai** [comment]
@minotogna 

Not sure why: on my PC, both Edge(also includes FRA 2025) and Chrome failed. I tried other PCs it works in Edge and Firefox, but not Chrome.

Maybe we could hold on to this issue and I will try it again on the office computers next week if possible.

**Comment by pengchenglai** [comment]
@minotogna 

Have tried it in FAO and my personal laptop and both cases are working now.

In case it would be mentioned at some point in the future, we could reopen the issue.

**Comment by minotogna** [comment]
> @minotogna
> 
> Have tried it in FAO and my personal laptop and both cases are working now.
> 
> In case it would be mentioned at some point in the future, we could reopen the issue.

great @pengchenglai . thank you !
