### ISSUE TITLE
Enhanced security - User account should auto-check out when the browser is closed

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#3031]
@minotogna 
**Is your feature request related to a problem? Please describe.**
Sometimes, users may forget to sign out of their accounts when closing the platform, and it appears that by default, the system will keep them logged in for the platform, which could be a concern if users log in from a publicly accessible computer.

**Describe the solution you'd like**
User account should auto-logged out when the browser is closed. This also means that the user has to input the account number and password after a certain period of inactivity.

**Comment by minotogna** [comment]
@pengchenglai many users find annoying to log in every time on a browser 
See google , Microsoft etc… they never log you out when browser is closed .
