### ISSUE TITLE
Text change in table 1d

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#3033]
@minotogna 
**Describe the solution you'd like**
Change the text _Forest area net change from table 1a_ to _Forest area net change **calculated** from table 1a_ .

**Priority**
Low

**Comment by minotogna** [comment]
@pengchenglai could you also provide translations in all different languages?
Thank you

**Comment by pengchenglai** [comment]
@minotogna 

Yes, I would ask colleagues for the translations.

**Comment by pengchenglai** [comment]
@minotogna 

For AR

.تم حساب تغيير مساحة الغابات من الجدول 1أ

**Comment by pengchenglai** [comment]
For CH, ES, FR, and RU respectively:

从表1a计算得出的森林面积净变化;
Cambio neto de la extensión de bosque calculado a partir de la tabla 1a;
Changement net de la superficie de forêt calculée à partir du tableau 1a ;
Чистое изменение площади лесов рассчитано на основе таблицы 1а
