### ISSUE TITLE
High priority -  NDP cell value cannot be 0

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#3037]
@minotogna 
**Describe the bug**
This only happens when all the area of national classes for that category are 0 (and no way to enter 0% to update the value), for example:
  NDP cell value(**... of which introduced species**) cannot be 0 when using NDP( for Saint Lucia) in tab 1b

**To Reproduce**
1. Create NDP
2.  All the national classes for that category are 0(example plantation forest)
3.  The overall shows as **empty(Dash)** instead of 0

**Expected behavior**
The value should be calculated as **zero** when all percentages for that catergory is 0%(not empty neither dash).

**Screenshots**
![1](https://github.com/openforis/fra-platform/assets/99216009/5ab0be3d-8e8b-4703-a744-4f33287c180e)

![2](https://github.com/openforis/fra-platform/assets/99216009/bad0b9c0-0c57-4fb4-b422-780020876315)

**Priority**
High

**Comment by sorja** [comment]
@pengchenglai 

Could you be so kind to share a full screen screenshot of the ODP?

Can you specify all cases and what the correct values would be?

**Comment by pengchenglai** [comment]
@sorja 

Sure, cut into text and data part:
![1](https://github.com/openforis/fra-platform/assets/99216009/79e95b59-62db-4e96-afae-b74f42a38031)
![2](https://github.com/openforis/fra-platform/assets/99216009/8cbac58c-f532-4cac-9306-ec7eb94a9ec4)

**Comment by pengchenglai** [comment]
@sorja 
1. When the values of **Area (1000 ha)** for national classes are all **0**, then the Total should be **0**;


2. When the values of **Area (1000 ha)** for national classes **not all** **0**(meaning at least for one national class the value is bigger than 0), and A.there are values for **all percentage cells**, for example for _…of which primary forest_, then the Total should be calculated;
B. and there are **only some** values for percentages, for example for _…of which primary forest_, then the Total should **not be calculated -keep as empty**(#3038).

**Comment by sorja** [comment]
Thank you @pengchenglai

I think I understand all 3 cases now:

Correct me if I am wrong

# 1


The image below is showing **correct** result for **Total** ...of which introduced: 0.00
The image below is showing **incorrect** result for **Total** ...of which primary forest, this should be `-`

![image](https://github.com/openforis/fra-platform/assets/5508251/a1fdd539-c157-4e23-96d6-cdfb66084277)

# 2a

The image below is showing **correct** result for **Total** ...of which introduced: 0.01
The image below is showing **correct** result for **Total** ...of which primary forest: 0.24

![image](https://github.com/openforis/fra-platform/assets/5508251/0fd0e1f1-2c81-45ff-afeb-0d7dabcad1bd)


# 2b


The image below is showing **incorrect** result for **Total** ...of which introduced, this should be `-`
The image below is showing **incorrect** result for **Total** ...of which primary forest, this should be `-`

![image](https://github.com/openforis/fra-platform/assets/5508251/117258ac-0200-4dd4-9ae4-b8ee842ef6fb)

**Comment by sorja** [comment]
@pengchenglai 
The above is the 'odp' part

Let's agree also on table 1b:

In the following image 
`…of which primary forest` is empty, and it should show `-` in the ODP view meaning that one or more value for `…of which primary forest` is empty

![image](https://github.com/openforis/fra-platform/assets/5508251/c1e671a7-64e3-4ad6-b714-fda92b33cdb0)

**Comment by pengchenglai** [comment]
@sorja 
Yes, that are all correct if one or more percentages of national class(es) for one FRA 2025 sub-category is(are) missing, the cell should keep empty in both NDP page and main 1b page.

Thank you:)
