### ISSUE TITLE
Value should show as empty when percentage for one national class is missing

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#3038]
@minotogna 

**Describe the bug**
Value should show as empty when percentage for one national class is missing(empty) in tab 1b

**To Reproduce**
1. Create NDP
2. Enter percentage for all the national classes and left one missing in tab 1b
3. The sum shows a value

**Expected behavior**
The sum should show as **empty** as not sure the overall value with the value of one national class is missing.

**Screenshots**
![1](https://github.com/openforis/fra-platform/assets/99216009/da93dd60-f914-427f-bf66-fcc36921819b)

**Comment by sorja** [comment]
![image](https://github.com/openforis/fra-platform/assets/5508251/d519cc5f-d13c-4926-b7da-1d3cb11fb0c1)
Issue resolved previously

If it persists, please re-open the issue @pengchenglai 

Thank you

**Comment by pengchenglai** [comment]
@sorja 

You are right, tks!
