### ISSUE TITLE
High priority - review platform is disabled

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#3058]
@minotogna @sorja 

**Describe the bug**
High priority - review platform is denied for access and editing

**To Reproduce**
1. Log in as an any role(such as a collaborator, admin)
2. See error
(see the video sent in the slack)

**Screenshots**
![1](https://github.com/openforis/fra-platform/assets/99216009/19384fe7-e293-4054-b7b0-fd70ba82a19a)

**Comment by minotogna** [comment]
@pengchenglai it is now working
