### ISSUE TITLE
Unable to login on smaller resolutions

### ISSUE THREAD

**Issue by sorja** [openforis/fra-platform#3074]
**Describe the bug**
When screen resolution is under 1200 px width, you are unable to login

**To Reproduce**
1. Go to /
2. Zoom in, change resolution or resize window

**Expected behavior**
User is able to log in

**Fix**
Evaluate if allowing 1024 is feasible

**Additional context**
_Coming later_

**Comment by minotogna** [comment]
@sorja login on small device is disabled on purpose

**Comment by sorja** [comment]
Issue was on laptop with resolution:
1366 x 768

**Comment by minotogna** [comment]
@sorja this is how it looks like at 1366 x 768. what exactly is the issue ?

![Image](https://github.com/openforis/fra-platform/assets/1138156/ae9f2dee-d865-4d0d-bdf4-3e71f46b8387)

**Comment by sorja** [comment]
I suspect the user had resolution of aforementioned, but probably had zoomed in

We can close the issue, as there has been only a single report about this and it was resolved by zooming out to 80%

**Comment by minotogna** [comment]
zooming is not our problem luckily :D
