### ISSUE TITLE
User activities synchronization Issue

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#3089]
@minotogna 
**Describe the bug**
In the case of **Brunei Darussalam**:
The last edited time in the drop-down menu is not aligned with the last activities recorded on the platform.

**To Reproduce**
See screenshots.

**Expected behavior**
The timeline of the drop-down menu aligns with the time of the last activities.

**Screenshots**
![1](https://github.com/openforis/fra-platform/assets/99216009/ded7ccca-41d6-4061-836d-6900384c3ee8)
![2](https://github.com/openforis/fra-platform/assets/99216009/bae34fcc-e85a-4737-835b-54f4cdd15fd0)

**Priority**
Low

**Comment by minotogna** [comment]
@pengchenglai for performance reasons, the activity timestamp you see in the menu is synchronised every 24 hours.

**Comment by pengchenglai** [comment]
@minotogna 

I will wait for bit longer time then and will let you know if the timeline does not update tomorrow. FYI, the sreenshots above was took yesterday, and after 1 day seems still not update yet.
![2](https://github.com/openforis/fra-platform/assets/99216009/03a818ce-a709-4e00-9063-46f3fed0ab21)
