### ISSUE TITLE
Cannot add a new NDP in the review

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#3094]
@minotogna 
**Describe the bug**
Please double check if it is an issue: Have we disabled some functions in the review? Unable to add a new NDP in the review, although it is working in the production.

**To Reproduce**
1. Add a NDP for table 1a
2. Click on 'done editing'
3. Did not add the NDP

**Screenshots**(see video below)
[98d4ee2c-f771-416f-bc8a-5e98d350af79.webm](https://github.com/openforis/fra-platform/assets/99216009/d79f8ad6-68fa-4bdc-9595-3e7fdb269461)

https://github.com/openforis/fra-platform/assets/99216009/d79f8ad6-68fa-4bdc-9595-3e7fdb269461

**Comment by minotogna** [comment]
@pengchenglai we're testing some big change which includes huge serve side performance improvements. The version deployed to review is a work in progress .

**Comment by pengchenglai** [comment]
> @pengchenglai we're testing some big change which includes huge serve side performance improvements. The version deployed to review is a work in progress .

@minotogna Good to know, thank you :)
