### ISSUE TITLE
Add a Download CSV File button for NDP

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#3095]
@minotogna 
**Is your feature request related to a problem? Please describe.**
Some countries may want to retain data of NDP, especially for the reclassification percentage that they may keep it as a local copy for future reference.

**Describe the solution you'd like**
Plz add a Download CSV File button(function) for these three tables of NDP(see below the screenshots).

**Screenshots** :
![1](https://github.com/openforis/fra-platform/assets/99216009/11ad6702-89f1-426c-9cb1-4113fdf346c9)
![2](https://github.com/openforis/fra-platform/assets/99216009/923e6c44-ead4-4903-bc0f-fb2c18c4d5a1)
![3](https://github.com/openforis/fra-platform/assets/99216009/9e47d505-6ab1-43a2-92c8-7d8aeb3200e1)

**Additional context**
Also add an additional column **Reference year for the data** which index the year

Thank you

**Comment by minotogna** [comment]
@pengchenglai where should the reference year column be placed exactly ?

**Comment by pengchenglai** [comment]
@minotogna 

In the downloaded CSV file find a suitable place to put the reference year column. For example, the last column could be named "Reference year" and it has one value (that year) in the first row of that column.

Alternatively, we could just indicate the year in the CSV filename, such as FRA2025_NDP2010.csv, where NDP2010 shows that it is a NDP for the year 2010.

**Comment by minotogna** [comment]
@pengchenglai , maybe better in the file name ? I link this idea. would it be ok?

**Comment by pengchenglai** [comment]
@minotogna 

Sure, the filename is fine and easy to implement.
