### ISSUE TITLE
High priority - improve printing performance for FRA 2025 (Loader)

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#3096]
@minotogna 
**Is your feature request related to a problem? Please describe.**
When using printing functions, it can eventually show the data correctly, but takes _quite a while_ to load the data.

**Describe the solution you'd like**
Please help improve the performance when possible.

**Screenshots**(example)
![Capture](https://github.com/openforis/fra-platform/assets/99216009/d23a7cc4-ea44-46a6-adfa-b256a8ff7dd7)
![1](https://github.com/openforis/fra-platform/assets/99216009/f91210a3-240e-47b5-ab46-9523a8a412c8)
![2](https://github.com/openforis/fra-platform/assets/99216009/d65fae48-4174-4955-bd40-acdd39c84267)

**Priority**
High

**Comment by minotogna** [comment]
- [ ] Add Loader over blank screen with text 'Generating Report' for those 10/15 seconds waiting time

**Comment by minotogna** [comment]
@pengchenglai are we happy with current performances and we can close this issue ?

**Comment by minotogna** [comment]
or @pengchenglai do we still need to add a loader ?

**Comment by pengchenglai** [comment]
@minotogna 

Absolutely, thank you!
