### ISSUE TITLE
panEuropean -> Enable print function on the pan-European platform as on the FRA platform

### ISSUE THREAD

**Issue by persas** [openforis/fra-platform#3125]

**Comment by yaguzmang** [comment]
@minotogna do we have a bit more context on this? I set up a user for PanEu and tried to access the unavailable /print route, so I take it there is no implementation at all. Please correct me if I am wrong.

**Comment by minotogna** [comment]
@yaguzmang it must be enabled from the toolbar.

![Image](https://github.com/openforis/fra-platform/assets/1138156/fdc3f98c-4674-4b08-a4a5-28ab30cb2ce1)
