### ISSUE TITLE
Unhandled Thrown Error!

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#3145]
@minotogna 

If it takes a few minutes, please investigate.
**Describe the bug**
See below the error:
![1](https://github.com/openforis/fra-platform/assets/99216009/e055ed50-01ce-4fef-9299-b0803d2b1efe)

Not sure of the reason: after refreshing the page, it disappeared.

**Comment by minotogna** [comment]
@pengchenglai unable to reproduce.
Do you remember the steps to be able to reproduce this?

**Comment by pengchenglai** [comment]
@minotogna 

It randomly popped up. I will reopen this issue in case it could be somehow reproducible.
