### ISSUE TITLE
User removal button

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#3148]
@minotogna 
**Is your feature request related to a problem? Please describe.**
Add a button for the admin to remove a user

**Further action**
Add another button for admin/NC to re-invite a user in case the user does not accept the invitation on time.

![1](https://github.com/openforis/fra-platform/assets/99216009/1f2bfe2d-ab6d-4f40-9dab-4f1bc8e64d5e)

**Comment by minotogna** [comment]
@pengchenglai users won't  be removed , we'll lose all the activities history . They will be removed , I'll open another task

**Comment by pengchenglai** [comment]
@minotogna 

Great, thank you!
