### ISSUE TITLE
NWFP validating with empty cells

### ISSUE THREAD

**Issue by minotogna** [openforis/fra-platform#3158]
Validation should not be triggered when cells have empty values 
https://fra-data.fao.org/assessments/fra/2025/LSO/sections/nonWoodForestProductsRemovals

![Image](https://github.com/openforis/fra-platform/assets/1138156/29078077-6986-41ef-abef-d2dd70e60930)

**Comment by pengchenglai** [comment]
#3155

**Comment by pengchenglai** [comment]
Users may select the "blank" for NWFP category
