### ISSUE TITLE
Urgent - Algeria Tab 1b

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#3160]
@minotogna @sorja 

**Describe the bug**
NDP page with detailed national classes can show the values(0) for **…of which primary forest** and **…of which introduced** species. But not in the main tab 1b page for **…of which primary forest** and **…of which introduced**.(see the screenshot below).

**To Reproduce** 
Tried to reproduce the issue in the review, but works fine. Could you plz check it in the production? Tks!

**Expected behavior**
Show the 0s in the main table of 1b

**Screenshots**
![1](https://github.com/openforis/fra-platform/assets/99216009/6d893dd4-479e-4d76-b74e-2602b4dfffd7)

**Comment by sorja** [comment]
Resolved with ( https://github.com/openforis/fra-platform/pull/3153 ) latest version of the platform

@minotogna 
@pengchenglai
