### ISSUE TITLE
Image in the editing box

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#3167]
@minotogna 

**Describe the bug**
The images do not show up correctly

**To Reproduce**
1. Go to Indonesia - table - Original data
2. See error(it shows up the image when clicking the "edit')

**Expected behavior**
Show up the images normally

**Screenshots**
![1](https://github.com/openforis/fra-platform/assets/99216009/fb4e4e4b-6110-4fa7-9798-351cde80ff9a)
![2](https://github.com/openforis/fra-platform/assets/99216009/1b6ece0a-8886-4722-acf2-70c7f348021e)

**Comment by minotogna** [comment]
@pengchenglai uploading images shouldn't be allowed. How did you put it there ?

**Comment by pengchenglai** [comment]
@minotogna 
It is already there, perhaps migrate from FRA 2020. Plz check Indonesia 2025 production

**Comment by minotogna** [comment]
@pengchenglai some editor/reviewer should remove it manually .

**Comment by pengchenglai** [comment]
@minotogna 

Ok, I will ask Samy to do it later
