### ISSUE TITLE
Possible misconfiguration in production db

### ISSUE THREAD

**Issue by sorja** [openforis/fra-platform#3176]
**Describe the bug**
```
FATAL:  no pg_hba.conf entry for host "[1(removed)9](https://...)", user "postgres", database "postgres", no encryption
```

**To Reproduce**
1. Go to prod papertrail (eg. see email)

**Possible solution**
1. https://dba.stackexchange.com/a/84002

**Comment by minotogna** [comment]
@sorja When does it happen ?

**Comment by sorja** [comment]
> @sorja When does it happen ?

The papertrail log is spammed full of this error message.
If this is counted towards our quota, I suspect this is causing the over quota issue we get notified about

**Comment by minotogna** [comment]
it seems to external hacking. we can't do much about it .
