### ISSUE TITLE
NDPs do not show up for FRA 2020

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#3178]
@minotogna @sorja 

**Describe the bug**
NDPs do not show up for FRA 2020

**To Reproduce** (example)
1. Go to 'FRA 2020 - Bangladesh -tab 1b'
2. Click on NDP '2000'
3. See error

**Expected behavior**
NDP shows up properly.

**Screenshots**
![1](https://github.com/openforis/fra-platform/assets/99216009/b0e4ebf7-d4f6-43ab-ad4d-b185d192694d)
![2](https://github.com/openforis/fra-platform/assets/99216009/1de540e7-6f42-46fb-9f0d-2e7e27f2edea)

**Comment by sorja** [comment]
https://fra-data.fao.org/assessments/fra/2020/BGD/sections/forestCharacteristics

@minotogna Fixed

@pengchenglai If issue persist,let us know

**Comment by pengchenglai** [comment]
@minotogna @sorja 

All good, tks!
