### ISSUE TITLE
The text should be fully visible in the National Data

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#3179]
@minotogna 
**Is your feature request related to a problem? Please describe.**
The text should be fully visible in the National Data.

**Screenshots**
![image](https://github.com/openforis/fra-platform/assets/99216009/041d1875-0740-42f8-8cfc-bb9f99a5c1ee)

**Comment by sorja** [comment]
![image](https://github.com/openforis/fra-platform/assets/5508251/50f3fe82-484f-4c73-aac3-68c66225887f)

@pengchenglai 
Can you verify this is working as expected in review instance?

Thanks

**Comment by sorja** [comment]
I noticed now that this bug must have reintroduced itself, I am opening a PR

**Comment by pengchenglai** [comment]
@sorja 

It has been fixed in the review. Thank you!
