### ISSUE TITLE
Add a comment box for the Name of currency in tab 7

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#3184]
@minotogna 

**Is your feature request related to a problem? Please describe.**
Add a comment box for the **Name of currency**

**Screenshot**
![image](https://github.com/openforis/fra-platform/assets/99216009/099c0fcc-48e6-4cce-8ab5-11ec4abd05ec)

**Comment by pengchenglai** [comment]
@minotogna 
Plz add another chatbox for tab 2d, tks:
![image](https://github.com/openforis/fra-platform/assets/99216009/d67661c3-bc79-45d2-883f-ce7f52ef6a6f)

**Comment by minotogna** [comment]
@pengchenglai this is a bit tricky. we need to rethink at the metadata.
we have some other higher priority tasks to work on, we'll get back to this later. is that ok ?

**Comment by pengchenglai** [comment]
@minotogna 

Sure, please handle the most urgent issues first. Thank you!
