### ISSUE TITLE
Update the user guideline

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#3196]
@minotogna 

**Is your feature request related to a problem? Please describe.**
Update the user guide

**Describe the solution you'd like**
Similar to what has been done to the tutorials(https://fra-data.fao.org/assessments/fra/2025/tutorials/), creating a public accessible page to view the user guide for all languages for FRA 2025

**Additional context**
Guideline files:
AR:https://www.fao.org/3/cc4690ar/cc4690ar.pdf
CH:https://www.fao.org/3/cc4690zh/cc4690zh.pdf
EN:https://www.fao.org/3/cc4690en/cc4690en.pdf
ES:https://www.fao.org/3/cc4690es/cc4690es.pdf
FR:https://www.fao.org/3/cc4690fr/cc4690fr.pdf
RU:https://www.fao.org/3/cc4690ru/cc4690ru.pdf

**Comment by minotogna** [comment]
Wouldn't it be better to have only one user guide page and in thevpage separate by tutorials and user guide ?
@pengchenglai @AnssiSamuli @sorja

**Comment by pengchenglai** [comment]
@minotogna 

You mean the new User Guide page will have two separate sections called **'Guidelines and Specifications'** and **'Tutorial'**('Tutorial' tab in the bottom of main FRA reporting page will be remove accordingly)? 

If that is the case, it sounds to be a more practical solution applied for each UN languages.

**Comment by pengchenglai** [comment]
@minotogna 

Update for the 'report misconduct' page:

en:https://www.fao.org/contact-us/report-misconduct/en
ar:https://www.fao.org/contact-us/report-misconduct/ar
zh:https://www.fao.org/contact-us/report-misconduct/zh
fr:https://www.fao.org/contact-us/report-misconduct/fr
ru:https://www.fao.org/contact-us/report-misconduct/ru
es:https://www.fao.org/contact-us/report-misconduct/es

**Comment by minotogna** [comment]
@pengchenglai can u please provide translations for 'Guidelines and Specifications'

**Comment by minotogna** [comment]
@pengchenglai Also, the link at the bottom, what should say ?

**Comment by pengchenglai** [comment]
@minotogna 

Namely, the 'User guide' (could be combined with an icon of a book and a video). Something like "User guide(📖/▶)'.

**Comment by pengchenglai** [comment]
@minotogna 

The translations were copied from working paper 193.
@samym392 AR: المبادئ التوجيهية والمواصفات
CH:准则和规范
EN: Guidelines and Specifications
FR: Lignes directrices et spécifications
RU: Руководство и спецификации
SP: Directrices y Especificaciones

**Comment by minotogna** [comment]
@pengchenglai at the moment we already have user guide available to download from the footer, and I just checked. the files are different from what linked in the issue. what should we use ?

**Comment by pengchenglai** [comment]
@minotogna 

We should use the links for different languages I provided above(in _Additional context - Guideline files_) since the PDFs have been officially released on the [FRA website](https://www.fao.org/forest-resources-assessment/en/).

FYI, we have updated some information in Working Paper 193, Guidelines and Specifications, so it may not perfectly match the previous version. Nevertheless, could you please share the user guide that can be downloaded from the footer? I will double-check it.

PS:
Please note that if it is downloaded from the current platform, you will see that **it is for [FRA 2020](https://github.com/openforis/fra-platform/files/13306098/User_Guide_FRA_Platform.pdf), not FRA 2025**.

**Comment by minotogna** [comment]
@pengchenglai the user guide is available from the footer if you log in

**Comment by pengchenglai** [comment]
@minotogna 

This one [User_Guide_FRA_Platform.pdf](https://github.com/openforis/fra-platform/files/13306687/User_Guide_FRA_Platform.pdf) is for FRA 2020 and as Örjan previously mentioned in the email, is outdated and needs to be updated.

**Comment by pengchenglai** [comment]
So we should use the links of PDFs, which are available in FRA website.

**Comment by minotogna** [comment]
So @pengchenglai can you please mention all the needed updates for fra 2020 and 2025?

Thank you

**Comment by pengchenglai** [comment]
> @minotogna
> 
> Update for the 'report misconduct' page:
> 
> en:https://www.fao.org/contact-us/report-misconduct/en ar:https://www.fao.org/contact-us/report-misconduct/ar zh:https://www.fao.org/contact-us/report-misconduct/zh fr:https://www.fao.org/contact-us/report-misconduct/fr ru:https://www.fao.org/contact-us/report-misconduct/ru es:https://www.fao.org/contact-us/report-misconduct/es

@minotogna 

'report misconduct' which needs to be updated for **both FRA 2020 and FRA 2025**.

**Comment by minotogna** [comment]
> > @minotogna
> 
> > 
> 
> > Update for the 'report misconduct' page:
> 
> > 
> 
> > en:https://www.fao.org/contact-us/report-misconduct/en ar:https://www.fao.org/contact-us/report-misconduct/ar zh:https://www.fao.org/contact-us/report-misconduct/zh fr:https://www.fao.org/contact-us/report-misconduct/fr ru:https://www.fao.org/contact-us/report-misconduct/ru es:https://www.fao.org/contact-us/report-misconduct/es
> 
> 
> 
> @minotogna 
> 
> 
> 
> 'report misconduct' which needs to be updated for both FRA 2020 and FRA 2025.

Ok, @pengchenglai so no updates to user guide or guidelines ? Right ?

**Comment by pengchenglai** [comment]
@minotogna 

Another one is new designed footer for the 'User guide' (which could be combined with an icon of a paper and a video) for **FRA 2025**. Something like "User guide(📄/▶)'.

We merge 'Guidelines and Specifications' and tutorials into one page of 'User guide'and in this page there are two parts as you suggested on one page for all UN languages.

Plus [two new videos](https://unfao.sharepoint.com/sites/NFO/Shared%20Folders/Forms/AllItems.aspx?id=%2Fsites%2FNFO%2FShared%20Folders%2FFOA%2DFRA%2FFRA%2FReporting%2FPlatformTutorials&p=true&ct=1699536932644&or=OWA%2DNT&cid=c3b3383a%2D845c%2D29c9%2D02fc%2D62846f960619&ga=1) shared previously(also see the email **New functionalities** ) needed to be added to the playlist of the tutorials.

**Comment by pengchenglai** [comment]
> > > @minotogna
> > 
> > 
> > > 
> > 
> > 
> > > Update for the 'report misconduct' page:
> > 
> > 
> > > 
> > 
> > 
> > > en:https://www.fao.org/contact-us/report-misconduct/en ar:https://www.fao.org/contact-us/report-misconduct/ar zh:https://www.fao.org/contact-us/report-misconduct/zh fr:https://www.fao.org/contact-us/report-misconduct/fr ru:https://www.fao.org/contact-us/report-misconduct/ru es:https://www.fao.org/contact-us/report-misconduct/es
> > 
> > 
> > @minotogna
> > 'report misconduct' which needs to be updated for both FRA 2020 and FRA 2025.
> 
> Ok, @pengchenglai so no updates to user guide or guidelines ? Right ?

We will need to update it and merge the tutorials into the user guide page as you suggested and mentioned above. @minotogna

Only these two things need to be updated at this stage.

**Comment by minotogna** [comment]
@pengchenglai this issue is bit complicated to read, I have created two new issues to summarise what todo.
See #3285 and #3284 . Please comment in those issues if you see anything to update. 
Thank you
