### ISSUE TITLE
Urgent - validation for Forest (a) in tab 1a is removed

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#3199]
@minotogna 

**Describe the bug**
Validation for Forest (a) in tab 1a is removed

**Expected behavior**
Add validation check for Forest (a) in tab 1a is removed

**Screenshots**
![image](https://github.com/openforis/fra-platform/assets/99216009/58486cbf-e191-45f2-811e-f2d15447241d)

**Comment by minotogna** [comment]
@pengchenglai what validation ?

**Comment by pengchenglai** [comment]
@minotogna 

Forest area reported for FRA 2025 should compared with what has reported for FRA 2020.

Now the validation is not there.
