### ISSUE TITLE
Old issue - Text copied will jump to the top

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#3201]
@minotogna 
**Describe the bug**
When copying the text after some texts have already been entered, the new text will jump to the top(see the video below).

**To Reproduce**

[2ec9470d-9c3b-4344-9945-7de3a3ce3b0f.webm](https://github.com/openforis/fra-platform/assets/99216009/6f9868a0-c686-4fd7-b460-6faa1fde354c)

**Comment by minotogna** [comment]
@pengchenglai (cc @sorja )
there's no much we can do about this with current editor
https://github.com/jodit/jodit-react/issues/217

**Comment by pengchenglai** [comment]
@minotogna 

Let's see if it will be fixed, or we may make a change during the next reporting period. 

I will let colleagues know about this issue and how to solve it (copy all the content in a single time) in case anyone has asked.
