### ISSUE TITLE
Links & Repository per cycle + UI Updates

### ISSUE THREAD

**Issue by minotogna** [openforis/fra-platform#3214]
- [ ] Links & repository (both) must be per cycle 
- [ ] current data belongs to fra 2025
- [ ] for fra 2020 restore data from legacy schema 
- [ ] current static files (*1) must be inserted into database, no static files anymore 
- [ ] Add rowIndex for future manual sorting of rows 
- [ ] Update NSO SDG Contact information file for 2025 (see file in private email)
- [ ] Use new table UI and api format 
- [ ] Translate current files 

*1 current static files

![Image](https://github.com/openforis/fra-platform/assets/1138156/bbed7753-1cdc-41f8-98fc-2793af0aea27)

**Comment by sorja** [comment]
@minotogna 

```
public.file:
columsn:
file_name
uuid
file
```

```
assessmentCycle.repository

id,
uuid
file_uuid [reference to public.file]
link [external link to file or url]
props [rowIndex, public/hidden]

```


------------------

can edit file if can toggle lock

either add a file or insert a link

--------------------



User story:

- Click `add` bottom right of the table
- Open panel right
- Title
- Link or File
- Click `save` -> close panel right and refresh the panel

**Comment by minotogna** [comment]
Note to @minotogna and @sorja for when I get back and review the UI:
let's add a badge for displaying private / public
