### ISSUE TITLE
The writing box is still hard to read if writing a long text

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#3221]
@minotogna 

**Is your feature request related to a problem? Please describe.**
The main text output reading part of the chatbox is nice. However, the issue is that it is still very difficult to read the entire input text in the writing box, as shown in the screenshot and video.
![image](https://github.com/openforis/fra-platform/assets/99216009/f4181d35-f679-44de-b163-aced193ff739)

https://github.com/openforis/fra-platform/assets/99216009/6eb2bfc1-4efc-4162-b197-682de2271fc3

**Describe the solution you'd like**
The writing box should be freely stretchable within the frame of the chatbox. Alterative solution is to allow the writing box inside the chatbox to be proportionally stretched along with the main chatbox.

**Additional context**
If possible to implement, the chatbox should be allowed to move to any place on the screen, avoiding covering important data, as currently, the entire chatbox is stretchable _only in a small area._

**Comment by pengchenglai** [comment]
@minotogna 

High priority issue.

**Comment by minotogna** [comment]
- [ ] Replace input component with common TextArea component 
- [ ] Check how to calculate textarea height on resize dialog
