### ISSUE TITLE
Zeros are partially removed from the previous bug

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#3222]
@minotogna @sorja 

**Describe the bug**
Previous bug of tab 1b has been fixed(https://github.com/openforis/fra-platform/issues/3198#issuecomment-1786303909) and most zeros are removed, but not the sub-classes of **'Primary forest by climatic domain,'** in which the cells should also be empty. I can no longer manually remove the zeros as the report has been accepted.

**To Reproduce**
1. Go to 'Production- Bangladesh'
2. Click on 'Table 1b - Primary forest by climatic domain'

**Expected behavior**
Auto-filled zeros due to the previous bug(https://github.com/openforis/fra-platform/issues/3198#issuecomment-1786303909) should be removed as what have been done for the total.

**Screenshots**
Before the bug has been fixed(https://github.com/openforis/fra-platform/issues/3198#issuecomment-1786303909) : 
![image](https://github.com/openforis/fra-platform/assets/99216009/1f4bf4ae-f759-464c-b391-daa44fb79928)

Current situation:
![image](https://github.com/openforis/fra-platform/assets/99216009/a350f099-5c31-44a9-a167-77d3a1dcb974)

**Comment by sorja** [comment]
@pengchenglai what do you propose?

Let's talk about cell C1 which refers to `of which boreal primary forest` and year `1990` but the same applies to all cells.


We currently set a `default` (NOTE: Not calculated!) value for C1 (& other) cell
The logic to set a default value is this:
If C1 has no value and each of the primaryForest(Boreal,Temperate,SubTropical,Tropical) sum equal to primary forest set it to 0

So, if we change the logic, I think there is possibility we will have logical mismatch?

User enters values for both tables
User decides to update upper table and removes or clears the value for primary forest in the first table before entering the new value
I don't think we should clear the value in between?


CC: @minotogna 

Let me know and let me know if you wanna have a call


& I think we should check with OJ also

& I think the bottom table obviously should not show 0, can we set the country back to edit mode..?


-------------

<details>
<summary> Here is the `canIf` calculation check -> which checks if we should set the value to 0</summary>
'!primaryForestByClimaticDomain.primaryForestSubTropical &&

equalsWithTolerance((

Number(primaryForestByClimaticDomain.primaryForestBoreal || 0) +
Number(primaryForestByClimaticDomain.primaryForestTemperate || 0) +
Number(primaryForestByClimaticDomain.primaryForestSubTropical || 0) +
Number(primaryForestByClimaticDomain.primaryForestTropical || 0)),

forestCharacteristics.primaryForest)'

</details>


----------------

**Comment by pengchenglai** [comment]
@sorja The country report has been sent back to edit mode. Will talk with Monica and see if we could correct it manually
 
If I understand this logic(_If C1 has no value and each of the primaryForest(Boreal,Temperate,SubTropical,Tropical) sum equal to primary forest set it to 0_) correctly, it means:
In the case of _…of which primary forest = 0_ in the first tab, if a user does not re-write the default cell, then the sum of all sub-classes = 0(meaning each of sub-class also =0)

I have tested in the Altantis 18(see below) and this rule does not consider one situation like what happened to Bangladesh:
If _…of which primary forest =_ 0 for a NDP year in the first tab, then by default each of sub-class =0 in the second table. When the user has removed the 0 for _…of which primary forest =_, 0 for all of sub-classes does not removed.

**Comment by pengchenglai** [comment]
![image](https://github.com/openforis/fra-platform/assets/99216009/2a44760d-fd44-4e04-a1f8-c9f869bf593d)

**Comment by pengchenglai** [comment]
This means one conditional rule should be added:
if the value for **…of which primary forest** has been re-written from 0, then all corresponding cells(sub-classes and Total) should be updated automatically. Meaning if the data has been re-written from 0(could be empty or a value >0) for _…of which primary forest_, the cells of sub-classes should be empty and allow users to enter the data for these cells in the second table.

**Comment by pengchenglai** [comment]
If it is complex to fix, I suggest to avoid the complication we remove this rule(for now) that auto-apply 0 for each sub-class **but do keep values for the Total** in the second table as the same values of _…of which primary forest_ in the first table. The reason is that reviewers could add 0s manually for sub-classes during review anyway.

**Comment by pengchenglai** [comment]
@minotogna @sorja 

Thanks for the update, have sent the admin an email to confirm the deployment(https://github.com/openforis/fra-platform/pull/3429#issue-2095595574) and will answer you back on Slack.

The fix is good to go!
