### ISSUE TITLE
Translations for two new FRA tutorials 

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#3230]
@minotogna 

**Is your feature request related to a problem? Please describe.**
As requested in this issue, we need to add two new tutorials on the platform(https://github.com/openforis/fra-platform/issues/3196#issuecomment-1803839425). Please find the title translations for the [videos](https://unfao-my.sharepoint.com/:x:/g/personal/pengcheng_lai_fao_org/EXILzpdxNrRKtx-r5YE2m3cB-YxYHCZNiPF3gzMkOQEQaA?e=ZBQVON)here using FAO credentials, thank you!

**Comment by pengchenglai** [comment]
Please note that the **Manual** needs to be replaced by the **Tutorial** for Spanish titles of tutorials(See reason below).

![image](https://github.com/openforis/fra-platform/assets/99216009/7a33f6cd-ae84-4d56-86b1-f454e5f24c59)



Reason for the replacement: 

Both words are correct,  but may have some differences.
See the definition (from Spanish translated to English), maybe it doesn´t apply literally for English, but in Spanish, it is the difference between a Manual or Tutorial:

 

**Manual**:

A manual is generally a written document that provides detailed information about the operation of a device, software or system.

Manuals are usually longer and designed to provide a complete reference.

They are useful for gaining a deep and detailed understanding of a topic.

 

 

**Tutorial**:

A tutorial is more interactive and practical. It usually involves practical steps and examples to guide the user through a specific process or task.

Tutorials are more visual and can be easier to follow for hands-on learners.

They are usually shorter and focus on specific tasks.

**Comment by minotogna** [comment]
<pre ccp_infra_version="3" ccp_infra_timestamp="1701696902056" ccp_infra_user_hash="1042815483" ccp_infra_copy_id="" data-ccp-timestamp="1701696902056" style="font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration: none; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0);">
EN
--
The FRA platform user tutorial - How to add a reference link for a national data point
The FRA platform user tutorial - How to add a reference link for national data

</pre>



<pre ccp_infra_version="3" ccp_infra_timestamp="1701696914528" ccp_infra_user_hash="1042815483" ccp_infra_copy_id="88222e6a-d46a-4b76-9698-ad2a64384a94" data-ccp-timestamp="1701696914528" style="font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration: none; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0);">
AR
--
البرنامج التعليمي لمنصة الفرا - كيفية إضافة رابط مرجعي لنقطة البيانات الوطنية؟
البرنامج التعليمي لمنصة الفرا - كيفية إضافة رابط مرجعي للبيانات الوطنية؟

</pre>


<pre ccp_infra_version="3" ccp_infra_timestamp="1701696923897" ccp_infra_user_hash="1042815483" ccp_infra_copy_id="000d3b8b-3193-45f8-9d63-5bea633e9b6b" data-ccp-timestamp="1701696923897" style="font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration: none; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0);">
ES
--
Tutorial del usuario de la plataforma FRA -  Cómo agregar un enlace de referencia para un punto de datos nacional
Tutorial del usuario de la plataforma FRA - Cómo agregar un enlace de referencia para datos nacionales

</pre>


<pre ccp_infra_version="3" ccp_infra_timestamp="1701696930272" ccp_infra_user_hash="1042815483" ccp_infra_copy_id="" data-ccp-timestamp="1701696930272" style="font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration: none; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0);">
RU
--
Руководство пользователя платформы ОЛР - Как добавить ссылку для национальной точки данных
Руководство пользователя платформы ОЛР - Как добавить ссылку на национальные данные

</pre>


<pre ccp_infra_version="3" ccp_infra_timestamp="1701696936800" ccp_infra_user_hash="1042815483" ccp_infra_copy_id="7ca30b53-987e-4ea9-96e0-7a6cc32b6bd7" data-ccp-timestamp="1701696936800" style="font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration: none; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0);">
ZH
--
全球森林资源评估平台用户教程 - 如何为国家数据点添加参考链接
全球森林资源评估平台用户教程 - 如何为国家数据添加参考链接

</pre>


<pre ccp_infra_version="3" ccp_infra_timestamp="1701696948115" ccp_infra_user_hash="1042815483" ccp_infra_copy_id="3f384503-bdec-40dd-ab49-13e827c9f1a9" data-ccp-timestamp="1701696948115" style="font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration: none; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0);">
FR
--
Tutoriel pour l'utilisateur de la plateforme FRA -  Comment ajouter le lien d'une référence pour un point de données national
Tutoriel pour l'utilisateur de la plateforme FRA -  Comment ajouter le lien d'une référence pour des données nationales

</pre>

**Comment by minotogna** [comment]
@pengchenglai this is now part of #3285
