### ISSUE TITLE
Statistical factsheets updates

### ISSUE THREAD

**Issue by minotogna** [openforis/fra-platform#325]
- [x] The legend for the pie chart Forest area % of land area should be changed, suggest deleting the “% of land area” and only showing “Forest area”
- [x] The title “Primary Forest Area % of Total Land Area (2020)” Should read “Primary forest % of forest area (2020)” 
- [x] The title “Natural and Plantation Forest Area” Should read “Naturally regenerating forest and planted forest (1990-2020)
- [x] For the tables “Row name” can be replaced by “FRA variables”
- [ ] If information is missing then suggest still displaying the FRA variable rows but leaving the cells blank, think the current statistical factsheets remove the row if data is not available

TO INVESTIGATE ONLY:
 For world and Region suggest dropping the decimals, it is an overkill displaying 2 decimals for total and %-ages. Is it possible to set a parameter that regulates if value is greater than 100 then not display decimals?

**Comment by sorja** [comment]
- [ ] If information is missing then suggest still displaying the FRA variable rows but leaving the cells blank, think the current statistical factsheets remove the row if data is not available

Ignoring this for now
