### ISSUE TITLE
High priority - Printing issue - blank page at the end & default file name & PDF downloading tab

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#3270]
@minotogna 

**Describe the bug**
Plz look at these two issues: 1. There is one blank page at the end of the printed PDF file; 2.the default name for the report is 'FRA platform,' which ideally should be renamed as '[Country Name] - FRA 2025 Report'. Thank you!

**To Reproduce** (Video using FAO ID to access)
https://unfao.sharepoint.com/:v:/s/NFO/EWjt3MUC5TBDkmAinpvKbTwBe8gbccicB_jcuf8C7eSesA?e=kZ9wQc

**Expected behavior**
No blank pages in the country report and the default file name is renamed

**Comment by minotogna** [comment]
@pengchenglai I always suggest not to upload the videos in Sharepoint. as you're aware we are not always covered by contract making impossible to access those videos

**Comment by pengchenglai** [comment]
@minotogna 

Correct, but it contains latest data so I will shared it in the slack

**Comment by pengchenglai** [comment]
@minotogna 

One other issue Lars has mentioned is that it creates many blank pages for the Nicaragua report (I will share the link with you on Slack) using the same(similar) option as shown in the video, which is linked to the **Firefox** browser used(another video). Could you please have a look?

**Comment by pengchenglai** [comment]
@minotogna 
As users may have different default settings for printing(which may result in part of the report being cut off due to the margin issue). To avoid this issue, we could add one more tab on the webpage of the printed report to allow users to **download the PDF report** in A4.

![image](https://github.com/openforis/fra-platform/assets/99216009/15f942d5-1bfa-4490-bcd2-168af9c3e517)

**Comment by minotogna** [comment]
@pengchenglai at the moment, it is not possible to download pdf file. to discuss later on the final format with AP and ÖJ.

**Comment by pengchenglai** [comment]
@minotogna 

Alright, plz keep this issue posted later.
