### ISSUE TITLE
Urgent(old issue recurring) - zeros do not show up in the main table 1b

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#3273]
@sorja 

**Describe the bug**
See production Bahrain 2000 and 2023 table 1b(see the email)
The NDP page shows the sum result of 0, but not in the main table of 1b

**Comment by sorja** [comment]
@minotogna

**Comment by minotogna** [comment]
> @minotogna

@sorja it seems the value in the ODP isn't shown in the table 1b. wasn't this fixed already ?

**Comment by sorja** [comment]
@minotogna Investigating
Local version is showing correct result with 1:1 imported data

**Comment by minotogna** [comment]
> @minotogna Investigating
> 
> Local version is showing correct result with 1:1 imported data
> 
> 
> 
> 

@sorja Did you regenerate the cache locally ?
