### ISSUE TITLE
Clear Table 

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#3278]
@minotogna 
**Describe the bug**
table 2a(example Curaçao): Using **clear table** function to remove all the value for the first table, the values do not disapper (at least) immediately for the corresponding cells in the second table(refresh the page would be the same).

**Expected behavior**
Corresponding values should disapper more or less at the same time.

**Priority**
Medium

**Screenshots**
![image](https://github.com/openforis/fra-platform/assets/99216009/077b11bf-eaa8-445f-9b6e-97aec3755dec)

**Comment by sorja** [comment]
@pengchenglai does this bug still persist?
I am trying in review and local and the values instantly clear

Let me know

**Comment by pengchenglai** [comment]
@sorja Yes, the issue is still there for Curaçao.
![image](https://github.com/openforis/fra-platform/assets/99216009/139a5ee1-2d28-45d4-bc67-a4767eceefd5)

**Comment by sorja** [comment]
@pengchenglai 
I cannot find anything from REDIS cache server either (queue or data)
Could you please be so kind to try one more time and see if console (F12) or network (F12) give you any errors?

Thanks

**Comment by pengchenglai** [comment]
@sorja 

Good to know there is no technical issue for this table. Since I cannot make any updates for now as the Curaçao report has been accepted, let us keep this issue open, and I will talk to the admin and change the report manually later when back in the office.

**Comment by minotogna** [comment]
@pengchenglai can I try in prod ?

**Comment by minotogna** [comment]
@pengchenglai I cannot try in production as there is data. after the tests I have conducted it is working, I'm unable to replicate the issue.
I'm closing this for now, if anything similar happens again, please open a new issue .
