### ISSUE TITLE
Guidelines and specifications + Tutorials 

### ISSUE THREAD

**Issue by minotogna** [openforis/fra-platform#3285]
### **FRA 2020**

- [x] Footer -> Leave User Guide as it is (i.e. visible only to logged users)
- [x] Footer ->  Remove Tutorial link page

### **FRA 2025**

- [x] Footer ->  Remove Tutorial link page
- [x] Footer -> User Guide link should open 'tutorial' page and be visible only to logged users
- [x] Tutorial Page -> Separate Tutorial page into two sections (same style as it now only Tutorial section)
  - **Guidelines and specifications** (see note 1 at the bottom)
    - **Add one row 'User Guide'** that opens user guide 2025 file (see note 2 at the bottom)
  - ~~**Tutorials**~~
    - ~~Leave all rows as they are, plus **add two new provided tutorials** ([link here]~~(https://unfao.sharepoint.com/sites/NFO/Shared%20Folders/Forms/AllItems.aspx?id=%2Fsites%2FNFO%2FShared%20Folders%2FFOA%2DFRA%2FFRA%2FReporting%2FPlatformTutorials&p=true&ct=1699536932644&or=OWA%2DNT&cid=c3b3383a%2D845c%2D29c9%2D02fc%2D62846f960619&ga=1)) (see note 3 for translations)

### **panEuropean 2020/2025**

- [x] Footer -> Remove User Guide and Tutorials link from footer 

**Note 1: Guidelines and specifications Translations**
> AR: المبادئ التوجيهية والمواصفات
> CH:准则和规范
> EN: Guidelines and Specifications
> FR: Lignes directrices et spécifications
> RU: Руководство и спецификации
> SP: Directrices y Especificaciones

**Note 2: User guide 2025 file**
> AR:https://www.fao.org/3/cc4690ar/cc4690ar.pdf
> CH:https://www.fao.org/3/cc4690zh/cc4690zh.pdf
> EN:https://www.fao.org/3/cc4690en/cc4690en.pdf
> ES:https://www.fao.org/3/cc4690es/cc4690es.pdf
> FR:https://www.fao.org/3/cc4690fr/cc4690fr.pdf
> RU:https://www.fao.org/3/cc4690ru/cc4690ru.pdf

**Note 3: New two tutorials Translations**

> EN
> --
> The FRA platform user tutorial - How to add a reference link for a national data point
> The FRA platform user tutorial - How to add a reference link for national data
> 
> AR
> --
> البرنامج التعليمي لمنصة الفرا - كيفية إضافة رابط مرجعي لنقطة البيانات الوطنية؟
> البرنامج التعليمي لمنصة الفرا - كيفية إضافة رابط مرجعي للبيانات الوطنية؟
> 
> 
> ES
> --
> Tutorial del usuario de la plataforma FRA -  Cómo agregar un enlace de referencia para un punto de datos nacional
> Tutorial del usuario de la plataforma FRA - Cómo agregar un enlace de referencia para datos nacionales
> 
> RU
> --
> Руководство пользователя платформы ОЛР - Как добавить ссылку для национальной точки данных
> Руководство пользователя платформы ОЛР - Как добавить ссылку на национальные данные
> 
> ZH
> --
> 全球森林资源评估平台用户教程 - 如何为国家数据点添加参考链接
> 全球森林资源评估平台用户教程 - 如何为国家数据添加参考链接
> 
> FR
> --
> Tutoriel pour l'utilisateur de la plateforme FRA -  Comment ajouter le lien d'une référence pour un point de données national
> Tutoriel pour l'utilisateur de la plateforme FRA -  Comment ajouter le lien d'une référence pour des données nationales

**Comment by yaguzmang** [comment]
>  - **Guidelines and specifications** (see note 1 at the bottom)
>    - **Add one row 'User Guide'** that opens user guide 2025 file (see note 2 at the bottom)

For the translation of 'User Guide', should I just use the one we have 'footer.userGuide' or should I move it?

**Comment by minotogna** [comment]
> > * **Guidelines and specifications** (see note 1 at the bottom)
> >   
> >   * **Add one row 'User Guide'** that opens user guide 2025 file (see note 2 at the bottom)
> 
> For the translation of 'User Guide', should I just use the one we have 'footer.userGuide' or should I move it?

maybe we can move it to common.userGuide 
What do you think?
