### ISSUE TITLE
Text of  Type of data source - National Data disappeared

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#3296]
@minotogna 

**Describe the bug**
If it is not too time-consuming, please check why the text of the '**National Forest Inventory (NFI)**' has suddenly disappeared under the '**Type of Data Source - National Data**' for  Japan Table 1a, as no one has edited it.

**Screenshots**
![1](https://github.com/openforis/fra-platform/assets/99216009/0314c3ed-518c-4e24-b5cd-d1e503ca374c)
![2](https://github.com/openforis/fra-platform/assets/99216009/a962df50-76e9-48d4-8818-730d0e42e9b5)

**Comment by minotogna** [comment]
@sorja can you please have a look at this at your earliest convenience? (check also in the activity log if something happened)
