### ISSUE TITLE
Progress bar for uploading large file

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#3311]
@minotogna 

**Is your feature request related to a problem? Please describe.**
There is no prompt for uploading a large file. Thus, the user may not know whether or when the file has been uploaded.

https://github.com/openforis/fra-platform/assets/99216009/139d6970-6f46-41e3-a0fd-7639b087cf46

**Describe the solution you'd like**
Add a progress bar for a large file(in the case of this video the file size is 64 M and takes around 25s.  The uploading speed is between 2M and 3M)

**Comment by minotogna** [comment]
@pengchenglai this all will be resolved in #3214
