### ISSUE TITLE
Validation check tab 1a

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#3353]
@minotogna
 
**Describe the bug**
No warning is given for forest area that does not match what has been reported for FRA 2020. Please double-check if the validation check for the forest area (against reported data during FRA 2020) has been removed or not.
![image](https://github.com/openforis/fra-platform/assets/99216009/7cd5624b-9535-4733-9e8a-91a9c13e5641)

**Comment by sorja** [comment]
@pengchenglai which country is this?

**Comment by pengchenglai** [comment]
@sorja 

For all the countries I suppose, for example, the Democratic People's Republic of Korea and the British Virgin Islands.

**Comment by minotogna** [comment]
@sorja this is a bit tricky. there's something deep to analyse carefully . let me take this 🤯

**Comment by minotogna** [comment]
TODO for future refactor:

ExpressionEvaluator.Context refactor -> use only assessments (not assessment and cycle) with assessmentName and cycleName
