### ISSUE TITLE
Add admin and reviewers as recipients when sending the report for approval

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#3363]
@minotogna 

**Describe the bug**
Other reviewers and the admin can't know what has been left when sending reports with comments for approval(see screenshots).

**Expected behavior**
By default, the admin and all reviewers for this country should receive a copy of the comments left when the report is sent for approval.
**Screenshots**
![image](https://github.com/openforis/fra-platform/assets/99216009/b33b95da-a93f-49c5-a2c0-df00fdeee165)

**Comment by pengchenglai** [comment]
@minotogna the admin and all reviewers **for this country** .

**Comment by minotogna** [comment]
TODO:

- [x] When updating status to 'Approval' -> Admin and reviewers should always appear before collaborators list, and they should always receive the email (they cannot be opt out)
- [x] When updating status to 'ANY' step, below collaborators list,  add checkbox (and BE feature) Send copy to self (be default it is checked.
- [ ]

**Comment by yaguzmang** [comment]
@minotogna this is almost ready for PR. Just one question to confirm: 
You mentioned in your first point that now Admins and Reviewers should appear before collaborators. Can the collaborators still be opt out (only them)?
