### ISSUE TITLE
ODP: Can't re-enable disabled ODPs

### ISSUE THREAD

**Issue by sorja** [openforis/fra-platform#3365]
**Describe the bug**
Bug:
https://github.com/openforis/fra-platform/blob/9a7a83ab8540fa450be9b46ec6f59316a1b572d0/src/client/pages/Section/SectionHeader/ForestCharacteristics/ForestCharacteristics.tsx#L23-L26

`hasOriginalDataPointData` is always `false` if ODPs disabled: ODPs are not fetched
Check if this is correct

So we currently return 'null' and not the button if the ODP has no data (...=doesn't have the data that is never fetched in the first place!)

**To Reproduce**
1. Go to any country with odps, section 1b
2. Click on 'Don't use ODPs'
3. Refresh
4. See error (button is not there)

**Expected behavior**
Button is there

**Comment by minotogna** [comment]
@sorja unable to reproduce. can u provide a video with use case ?

**Comment by sorja** [comment]
> @sorja unable to reproduce. can u provide a video with use case ?

Unable to replicate, maybe it was solved
