### ISSUE TITLE
GeoFRA- burned area

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#3378]
@minotogna 

**Describe the bug**
FYI, it seems not a real value(much smaller) for the year **2022** regarding the **MODIS burned area** for _**all the countries**_, examples China and Brazil.
![image](https://github.com/openforis/fra-platform/assets/99216009/dcf758d9-e298-4ece-a912-b4706d8ecfad)

**Comment by minotogna** [comment]
@pengchenglai is the earth engine app ?

**Comment by pengchenglai** [comment]
@minotogna 
Yes, it is an issue of 2022 data for _Estimated yearly burned area 2002-2022 (MODIS)_.

**Comment by minotogna** [comment]
@pengchenglai , if it doesn't concern the Platform, can I close this?

**Comment by pengchenglai** [comment]
Sure
