### ISSUE TITLE
Download an excel file from the Repository

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#3396]
@minotogna 
**Describe the bug**
Not possible to download an Excel file from the repository.

**To Reproduce** (example of Democratic People's Republic of Korea production)
1. Go to 'Repository'
2. Click on 'Dem People's Rep of Korea_Area from centroid_tab1.xlsx'
3. Download

**Expected behavior**
No error

**Screenshots**

![1](https://github.com/openforis/fra-platform/assets/99216009/bb1d30fe-9f02-403a-8f87-1a0be31f8e7a)
![2](https://github.com/openforis/fra-platform/assets/99216009/1de62fbd-0bb4-40f6-8d9b-5e8843eb67ab)
![3](https://github.com/openforis/fra-platform/assets/99216009/2e56d50b-ed6c-4f2f-8950-d7aae4283ec4)

**Comment by sorja** [comment]
@pengchenglai NVM
I am able to replicate with other browser

Thanks for reporting!

**Comment by pengchenglai** [comment]
@sorja  Thank you!
