### ISSUE TITLE
Country Contacts and User form -> Permissions and Organisation link

### ISSUE THREAD

**Issue by minotogna** [openforis/fra-platform#3408]
- [x] Make user and contact  organization column with link (use WYSWYGLinks but without repository)
- [x] Contacts table : for admin only : add link to edit user 
- [x] Country user edit form (for admin only): add select to change role 
- [x] User edit form role fields :  User can edit his own role info only if country is in editing status (admin can always edit user and user role info)
- [x] User invitation : split first name and surname 
- [x] Contacts edit permissions : Can be edited according to same permissions as editing table data

**Comment by sorja** [comment]
I think this is already in place:
> Contacts edit permissions : Can be edited according to same permissions as editing table data`

with this:

`express.put(ApiEndPoint.CycleData.Contacts.one(), AuthMiddleware.requireEditTableData, updateContact)`

Let me know if there needs to be a change for this

@minotogna

**Comment by minotogna** [comment]
> I think this is already in place:
> 
> > Contacts edit permissions : Can be edited according to same permissions as editing table data`
> 
> 
> 
> with this:
> 
> 
> 
> `express.put(ApiEndPoint.CycleData.Contacts.one(), AuthMiddleware.requireEditTableData, updateContact)`
> 
> 
> 
> Let me know if there needs to be a change for this
> 
> 
> 
> @minotogna 

@sorja have you checked ui as well ?

**Comment by sorja** [comment]
> > I think this is already in place:
> > > Contacts edit permissions : Can be edited according to same permissions as editing table data`
> > 
> > 
> > with this:
> > `express.put(ApiEndPoint.CycleData.Contacts.one(), AuthMiddleware.requireEditTableData, updateContact)`
> > Let me know if there needs to be a change for this
> > @minotogna
> 
> @sorja have you checked ui as well ?

@minotogna 

I will add a video in the main PR of current flow including all above.

Reply to above:

I tested it by:
- Creating a new collaborator and logging in in another window/session
- Selecting 'none' as collaborator permissions in admin session
- Expected and result: No editing possibilities in section 0
- Selecting 'all' as collaborator permissions in admin session
- Expected and result: Can edit and add new collaborators in section 0

Let me know if there are any other tests or steps you would like me to take

No permissions:

https://github.com/openforis/fra-platform/assets/5508251/72bd17ce-69d6-4305-b553-604d4609e615

All permissions:

https://github.com/openforis/fra-platform/assets/5508251/04cba14b-c31c-4ae9-ac91-80c345902f84

**Comment by minotogna** [comment]
> > > I think this is already in place:
> 
> > > > Contacts edit permissions : Can be edited according to same permissions as editing table data`
> 
> > > 
> 
> > > 
> 
> > > with this:
> 
> > > `express.put(ApiEndPoint.CycleData.Contacts.one(), AuthMiddleware.requireEditTableData, updateContact)`
> 
> > > Let me know if there needs to be a change for this
> 
> > > @minotogna
> 
> > 
> 
> > @sorja have you checked ui as well ?
> 
> 
> 
> @minotogna 
> 
> 
> 
> I will add a video in the main PR of current flow including all above.
> 
> 
> 
> Reply to above:
> 
> 
> 
> I tested it by:
> 
> - Creating a new collaborator and logging in in another window/session
> 
> - Selecting 'none' as collaborator permissions in admin session
> 
> - Expected and result: No editing possibilities in section 0
> 
> - Selecting 'all' as collaborator permissions in admin session
> 
> - Expected and result: Can edit and add new collaborators in section 0
> 
> 
> 
> Let me know if there are any other tests or steps you would like me to take
> 
> 
> 
> No permissions:
> 
> 
> 
> https://github.com/openforis/fra-platform/assets/5508251/72bd17ce-69d6-4305-b553-604d4609e615
> 
> 
> 
> All permissions:
> 
> 
> 
> https://github.com/openforis/fra-platform/assets/5508251/04cba14b-c31c-4ae9-ac91-80c345902f84
> 
> 
> 
> 

Looks good @sorja 👍
