### ISSUE TITLE
Tab 1a National Data - Data sources unable to edit

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#3418]
@minotogna 

**Describe the bug**
An error page appears when trying to edit Tab 1a National Data - Data sources for Israel.

**To Reproduce**
1. Go to Israel - Tab 1a National Data - Data sources
2. Click on 'Edit'
3. See error page

**Expected behavior**
Allow editing

**Screenshots**
![image](https://github.com/openforis/fra-platform/assets/99216009/9f939e64-ccae-4d30-a073-224a9a22d90f)
![image](https://github.com/openforis/fra-platform/assets/99216009/c9fb6373-ebd4-4e16-b5a9-9cb3f8f70e94)

**Comment by sorja** [comment]
Interesting, I found single entity that was malford to a record of `Record<Number, String>` that resembles an array of characters.
`[<, p, >, F, o, r,e,s,...`

Only for this country

Weird

Please let me know if you can find any other similar issues (shouldn't exist)

**Comment by pengchenglai** [comment]
@sorja 

Tks! Sure, for now only Israel had the issue.
