### ISSUE TITLE
Remove contact table session(Report preparation and contact persons) for desk studies

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#3423]
@minotogna 

**Is your feature request related to a problem? Please describe.**
If a country report is assigned(accepted) as a desk study(also means no NC, collaborators), then remove the contact table session(Report preparation and contact persons).

![image](https://github.com/openforis/fra-platform/assets/99216009/c2cfc0c0-0b52-44b3-91ea-6f02c4770763)

**Comment by minotogna** [comment]
@pengchenglai this is already the case. See for example https://fra-data.fao.org/assessments/fra/2025/ARE/print/

**Comment by pengchenglai** [comment]
@minotogna 

Great to know, thanks! I found the issue: some countries are designated as DS, but the admin did not assign it to them. I will inform him about it.
