### ISSUE TITLE
Urgent -- Dot status not updating in the table list

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#3505]
@minotogna  @sorja 

**Describe the bug**
The dot in the table list remains blue even after all comments inside this table session are solved; 

Similarly, the dot stays orange even after all comments have been read or solved(see this point below in the screenshot).

**To Reproduce**
Plz check production Atlantis 18 Tables 1a and 1b for details(common issue for **countries**)

**Expected behavior** (for the dots in the table list)
The dot in the list is removed when all issues for this table are solved by this user.

The dot turns blue from orange if all comments have been read by this user.

Show an orange dot for other users when there is a new comment made by this user.

**Screenshots**
![image](https://github.com/openforis/fra-platform/assets/99216009/91d6ead5-9af9-47fb-bc81-a5d5c64761b7)

**Comment by minotogna** [comment]
@pengchenglai it seems it's resolved now. Can you please verify ?

**Comment by pengchenglai** [comment]
@minotogna 

Try for some features for that part is fine.

But for table 1a / 1b the problem is persisted when I solved all the comments and the dots still there and are orange for Atlantis 18: https://fra-data.fao.org/assessments/fra/2025/X18/sections/forestCharacteristics

![image](https://github.com/openforis/fra-platform/assets/99216009/2667a342-5818-462f-957a-bb87a76a481a)

**Comment by minotogna** [comment]
> @minotogna 
> 
> 
> 
> Try for some features for that part is fine.
> 
> 
> 
> But for table 1a / 1b the problem is persisted when I solved all the comments and the dots still there and are orange for Atlantis 18: https://fra-data.fao.org/assessments/fra/2025/X18/sections/forestCharacteristics
> 
> 
> 
> ![image](https://github.com/openforis/fra-platform/assets/99216009/2667a342-5818-462f-957a-bb87a76a481a)
> 
> 

@pengchenglai can you please detail the problem ?

**Comment by pengchenglai** [comment]
@minotogna  

Sure,to Reproduce:
1. Go to Atlantis 18(https://fra-data.fao.org/assessments/fra/2025/X18/home/messageBoard);
2. **Solved all** the existing comments of tab 1a/ 1b;
3. the _dots_ in the table list _still show as orange_ while by theory they **should be removed**, right?
![image](https://github.com/openforis/fra-platform/assets/99216009/1ebac7cb-f342-4958-8ad5-f3ca5fba698a)

**Comment by minotogna** [comment]
ok @pengchenglai , we'll have a look!
