### ISSUE TITLE
Urgent - appearance of the error message in the empty text box(National Data etc)

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#3511]
@minotogna 

**Describe the bug**
Error messages appear for the empty text boxes.

**To Reproduce**
Go to any country, find an empty text box of National Data and Analysis and processing of national data:
![image](https://github.com/openforis/fra-platform/assets/99216009/61ad09c6-782d-4a16-a72a-f401b9ce084f)

**Comment by minotogna** [comment]
@pengchenglai this was requested a while ago by ÖJ and it has been like that in fra 2020.
There was a bug now that didn't show the message and it has been fixed.
If you want to change the behaviour please talk to ÖJ and let us know. 
Thank you

**Comment by pengchenglai** [comment]
@minotogna 

As confirmed by the email, kindly reopen this issue when possible. Thank ya!

**Comment by minotogna** [comment]
@pengchenglai in the email it seems that only certain sections should be 'error free' or all of them ?

**Comment by pengchenglai** [comment]
@minotogna 
These four parts, tks!

National Data:  **National classification and definitions** and **Original data**

Analysis and processing of national data: **Estimation and forecasting** and **Reclassification into FRA 2025 categories**

![image](https://github.com/openforis/fra-platform/assets/99216009/287cabf4-34ea-4d54-955b-a54b3f0b336f)

**Comment by minotogna** [comment]
ok @pengchenglai !
