### ISSUE TITLE
Text replacement - tab 2b

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#3516]
@minotogna @sorja 

**Is your feature request related to a problem? Please describe.**
Replace ''growing stock composition'' with ''Forest growing stock composition'' in four places(see below) on the platform for all UN languages.

**Screenshot**
Table list:
![image](https://github.com/openforis/fra-platform/assets/99216009/76d9c845-5a2a-40f2-b54c-b8231e509f71)

Table name:
![image](https://github.com/openforis/fra-platform/assets/99216009/1c9621c6-38c6-4ec2-a55f-ede5920822c2)

T &D(2 loctions):
![image](https://github.com/openforis/fra-platform/assets/99216009/9f61decb-17cd-4307-a1e1-19a827fed781)
![image](https://github.com/openforis/fra-platform/assets/99216009/e7f97811-5f86-4137-ba1b-f62b891e8841)

Q & A(
![image](https://github.com/openforis/fra-platform/assets/99216009/7d4b0d3a-db03-4e7e-b51f-235f9b88bcb8)
):
![image](https://github.com/openforis/fra-platform/assets/99216009/b3950c49-64cc-4d4b-aba3-014c3e5f2bfc)

**Comment by pengchenglai** [comment]
The translations will be shared here later.

**Comment by pengchenglai** [comment]
Eng: Forest growing stock composition

Ar: تكوين مخزون الأشجار الحيّة بالغابات

CH: 森林立木蓄积量组成

Fr: Composition du matériel sur pied de la forêt

ES: Composición de las existencias forestales en formación

@minotogna

**Comment by minotogna** [comment]
> Eng: Forest growing stock composition
> 
> 
> 
> Ar: تكوين مخزون الأشجار الحيّة بالغابات
> 
> 
> 
> CH: 森林立木蓄积量组成
> 
> 
> 
> Fr: Composition du matériel sur pied de la forêt
> 
> 
> 
> ES: Composición de las existencias forestales en formación
> 
> 
> 
> @minotogna 
> 
> 

@pengchenglai Russian is missing

**Comment by pengchenglai** [comment]
@minotogna 

See the reply in the slack.

**Comment by yaguzmang** [comment]
> 
> See the reply in the slack.

@pengchenglai Can you please share with me the Russian translation? I believe I don't access to that reply in Slack.

**Comment by pengchenglai** [comment]
@yaguzmang 

Thanks for asking. No Russian translation needs to be replaced.
