### ISSUE TITLE
Bug appears when switching between countries for FRA2020

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#3519]
@minotogna 

If you have time to investigate:

**Describe the bug**
There is an error showed up when switching between countries for FRA2020

**To Reproduce** (I cannot reproduce with my laptop)
Reported by Erica, may be linked with the local environment. The browser version has the issue:
Chrome is up to date
Version 121.0.6167.185 (Official Build) (64-bit)

![image](https://github.com/openforis/fra-platform/assets/99216009/1b5c4494-f9c9-43ac-91dd-80c4ddc6ac33)

**Priority**
Very low priority

**Comment by minotogna** [comment]
> @minotogna 
> 
> 
> 
> If you have time to investigate:
> 
> 
> 
> **Describe the bug**
> 
> There is an error showed up when switching between countries for FRA2020
> 
> 
> 
> **To Reproduce** (I cannot reproduce with my laptop)
> 
> Reported by Erica, may be linked with the local environment. The browser version has the issue:
> 
> Chrome is up to date
> 
> Version 121.0.6167.185 (Official Build) (64-bit)
> 
> 
> 
> ![image](https://github.com/openforis/fra-platform/assets/99216009/1b5c4494-f9c9-43ac-91dd-80c4ddc6ac33)
> 
> 
> 
> **Priority**
> 
> Very low priority

@pengchenglai can you please let us know from which country and to which country she's navigating ?
Thank you

**Comment by pengchenglai** [comment]
@minotogna 

Actually, in her case when she chooses any country and tries to navigate to another country in the FRA2020 user interface the error occurs.

**Comment by pengchenglai** [comment]
But when she logs out and accesses it as a visitor, it works.

**Comment by minotogna** [comment]
Thanks @pengchenglai . We'll have a look
