### ISSUE TITLE
Add tab info when removing the linked reference from repo

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#3524]
@minotogna 

**Is your feature request related to a problem? Please describe.**
Not sure which table the user should go to when trying to remove the reference since the info is missing here.

For example, the below should show as • **5a** Disturbances (Data sources)
![image](https://github.com/openforis/fra-platform/assets/99216009/5bf611ea-390e-4c08-aea5-a39c852a6352)

**Describe the solution you'd like**
Add table info when trying to remove the reference from the data source, so users would know which table they should go to remove the reference from there and then do it in the repo.

**Comment by minotogna** [comment]
@pengchenglai we're completely reworking the repository . users won't be able to delete these items when in use and there will be a message showing where it's used.
I close this now. wait a few more days to see the new repository . https://github.com/openforis/fra-platform/issues/3214

**Comment by pengchenglai** [comment]
@minotogna 

Good to know!
