### ISSUE TITLE
Urgent - Copy & paste data issue

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#3559]
@minotogna @sorja @yaguzmang 

**Describe the bug**
Copy data from excel and paste it into the table on the platform. Only few are actually pasted(See the video and reason below).

**To Reproduce**

https://github.com/openforis/fra-platform/assets/99216009/492efcff-b274-40ff-aac1-073e92df5a89

**Expected behavior**
All the data can be pasted into the platform, no matter how many digits the original data has.

**Comment by pengchenglai** [comment]
I found that the reason is that some numbers have more than two digits (3), so they cannot be accepted by the platform. However, there is no warning or indication of this issue.

Is there any way to work around this issue? Possible for users to copy numbers with more than two digits and paste them into the platform, which only retains two digits for the figures?

**Comment by minotogna** [comment]
Ok @pengchenglai we're going to take a look .
In case the user will paste values with more then 2 digits , figures will be rounded to 2 digits .

**Comment by pengchenglai** [comment]
@minotogna 

Sure, thank you :)
