### ISSUE TITLE
Hide comment dots for viewer

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#3577]
@minotogna 

**Is your feature request related to a problem? Please describe.**
It is better to hide the comment dots for viewers, as they cannot access the comments, which may lead to confusion.

**Describe the solution you'd like**
Hide comment dots for viewer

**Comment by pengchenglai** [comment]
![image](https://github.com/openforis/fra-platform/assets/99216009/28d0990e-4385-4609-b242-83ea611161a2)

**Priority**
Low

**Comment by minotogna** [comment]
### 1.
in useReviewSummaryListener, user show subscribe to socket events if he has edit permissions.


![Image](https://github.com/openforis/fra-platform/assets/1138156/724d51cd-7dde-476c-9834-19719d4e0b71)

### 2.
in useReviewStatusListener, the same


![Image](https://github.com/openforis/fra-platform/assets/1138156/2ef2487d-14ad-4f36-a3c2-82264269bd6c)
