### ISSUE TITLE
Urgent - send a auto-reminder for reviewer(s)

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#3597]
@minotogna @sorja 

**Is your feature request related to a problem? Please describe.**
Some reports have been under review for many weeks, which should not be the case.

**Describe the solution you'd like**
As discussed with the admin, if a country report has been under review for more than **one week,** then a reminder to the reviewer(s) for that country should be sent, something like the below:

'Dear XX,

The FRA country report of XX has been “In review” since (_date when status changed to “In review”_). Please provide your comments and send the report back to “Editing”, or proceed with approval if there are no further issues.

Thank you.'

Every week after the first reminder email, if there is no update for the country that is under review, then this email should be sent again.

**Comment by minotogna** [comment]
@pengchenglai could you please post the translations here in a comment as well ?
Thank you

**Comment by pengchenglai** [comment]
@minotogna 

Email content was updated and no translation is needed.
