### ISSUE TITLE
NDP: user defined total percentage for primary forest

### ISSUE THREAD

**Issue by minotogna** [openforis/fra-platform#3611]
In NDP view, allow users to enter total percentage:

- [ ] In current total row, add text input for entering total primary forest percentage:
  - [ ] it is enabled if all sub classes value are empty 
  - [ ] it is disabled if at least on sub class is populated and calculated based on sub classes percentages 
- [ ] Below current total row, add new row with only right cell to display calculated primary forest area (it can be calculated based on total percentage)

**Comment by pengchenglai** [comment]
Example:
![image](https://github.com/openforis/fra-platform/assets/99216009/3ab48412-7f3c-4a80-a7c5-21d26907cb04)
