### ISSUE TITLE
Urgent - tab 2a growing stock -'clear table' issue

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#3624]
@minotogna @sorja 

**Describe the bug**
Using 'clear table', the values were initially removed from both tables. 

However, upon refreshing one of the tables, the values reappeared in one of these two tables, and it is impossible to remove them again using the 'clear table' function( possible to remove them one by one).

**To Reproduce**(example of Atlantis 18)
1. Go to tab 2a growing stock and have values for these two tables
2. Click on 'clear table'
3. Wait for the values to be removed
4. Re-fresh the page
5. Values showed up in one of these two tables
6. Impossible to remove these re-appeared values by clicking on 'clear table'

**Expected behavior**
Values are completely removed when clicking on 'clear table', which should remain valid after refreshing the page.

**Video**
https://github.com/openforis/fra-platform/assets/99216009/37cdf06d-6376-49ea-8686-68754f80cff3

**Comment by minotogna** [comment]
@pengchenglai It's really strange what was happening . Still under investigation. This however should not affect other counties .
I had reset these tables now , could you please try to replicate ?

**Comment by pengchenglai** [comment]
@minotogna 

Thanks! Seems ok in the production. You might also consider resetting the tables for the review.

**Comment by pengchenglai** [comment]
@minotogna 

Thank you! 2a and 2c are fine for production, **but 2d may need to be reset**. Please also consider resetting 2a, 2c, and 2d for the review when possible.

**Comment by minotogna** [comment]
> @minotogna 
> 
> 
> 
> Thank you! 2a and 2c are fine for production, **but 2d may need to be reset**. Please also consider resetting 2a, 2c, and 2d for the review when possible.

Actually @pengchenglai there's a bug indeed . When using ‘clear table’ on the table with all calculated cells , leaves the cache in an inconsistent state . It contains the mirror table data , while in reality it has been cleared as consequence .
Fix is on its way

**Comment by pengchenglai** [comment]
> > @minotogna
> > Thank you! 2a and 2c are fine for production, **but 2d may need to be reset**. Please also consider resetting 2a, 2c, and 2d for the review when possible.
> 
> Actually @pengchenglai there's a bug indeed . When using ‘clear table’ on the table with all calculated cells , leaves the cache in an inconsistent state . It contains the mirror table data , while in reality it has been cleared as consequence . Fix is on its way

Excellent, thanks for fixing the cache issue :)
