### ISSUE TITLE
Urgent - Metadata lost - Data sources

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#3634]
**Describe the bug**
Although some cells in the data might have been left empty, some metadata might have been lost during the update, as it is unlikely that we could accept the reports while leaving them empty. Could you please investigate? If this is the case for the latter, please fix it systematically as soon as possible.

**Expected behavior**
Retrieve the metadata lost 

**Screenshots**
https://fra-data.fao.org/assessments/fra/2025/JPN/sections/extentOfForest
https://fra-data.fao.org/assessments/fra/2025/BGD/sections/growingStockComposition
https://fra-data.fao.org/assessments/fra/2025/BGD/sections/designatedManagementObjective
https://fra-data.fao.org/assessments/fra/2025/KHM/sections/carbonStock
https://fra-data.fao.org/assessments/fra/2025/KHM/sections/specificForestCategories

**Comment by pengchenglai** [comment]
@minotogna @sorja

**Comment by minotogna** [comment]
@pengchenglai please see email, it doesn't seem to be an issue on our side
