### ISSUE TITLE
A reminder should be sent after seven calendar days

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#3640]
@minotogna 

**Describe the bug**
A reminder for reviewers to facilitate the reviewing process should be sent after one week of submission.

**To Reproduce**
Lao 

**Screenshots**
![image](https://github.com/openforis/fra-platform/assets/99216009/fffd22c3-eb90-4021-8baf-6a4db820610b)

**Priority**
Low

**Comment by minotogna** [comment]
@sorja dont we have this feature already implemented ?

**Comment by sorja** [comment]
> @sorja dont we have this feature already implemented ?

Yes

**Comment by pengchenglai** [comment]
@sorja @minotogna 

Yes, the issue is that this email was sent just after **one day instead of one week**.

**Comment by sorja** [comment]
> @sorja @minotogna
> 
> Yes, the issue is that this email was sent just after **one day instead of one week**.

I found the error, thanks!
