### ISSUE TITLE
Copy and paste issue

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#3648]
@minotogna 

**Describe the bug**
Colleagues have been troubled by this issue for a very long time: copying and pasting tables or text into the text box has failed multiple times to place it in the right position.

I know there was an investigation done in the past. Could you please keep an eye on it and see if there is a new solution? At the very least, we need to revise it before(for) FRA 2030.

**Comment by minotogna** [comment]
> @minotogna 
> 
> 
> 
> **Describe the bug**
> 
> Colleagues have been troubled by this issue for a very long time: copying and pasting tables or text into the text box has failed multiple times to place it in the right position.
> 
> 
> 
> I know there was an investigation done in the past. Could you please keep an eye on it and see if there is a new solution? At the very least, we need to revise it before(for) FRA 2030.

Hi @pengchenglai can u please provide a specific use case ? The other day I was testing pasting the whole tables 1a/1b/2a and it was working nicely.
Thank you

**Comment by pengchenglai** [comment]
@minotogna 

Sure, plz see the video below:

https://github.com/openforis/fra-platform/assets/99216009/8ea5f85d-15cf-4981-a48f-4e3563918e15

**Comment by pengchenglai** [comment]
@minotogna @yaguzmang 

Also when clicking 'Done', it would auto-create an extra space row between text and table, could you plz check it when possible(see below), thank you!

https://github.com/openforis/fra-platform/assets/99216009/59d8a04d-440a-4298-8cfd-a7abd544f63a
