### ISSUE TITLE
Tables 1d/2a: add subcatogory validator

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#3656]
@minotogna 

**Describe the bug**
Subclasses can be greater than the parent without the warnings(see below the screenshot).

**Describe the solution you'd like**
Add warnings if this situation occurs for tables 1d and 2a
**Screenshots**
1.
![image](https://github.com/openforis/fra-platform/assets/99216009/d702bca3-810f-410f-b6b1-87faa9c22ffa)

2.
![image](https://github.com/openforis/fra-platform/assets/99216009/1825f54b-585f-43bb-b54a-dcc12a0cabca)

**Comment by sorja** [comment]
_I might remember incorrectly, BUT_
I think it was requested that when one or more values for sub categories are missing, we do not show the error.

I will change it back to what it was before (error as requested here)

**Comment by minotogna** [comment]
> _I might remember incorrectly, BUT_
> 
> I think it was requested that when one or more values for sub categories are missing, we do not show the error.
> 
> 
> 
> I will change it back to what it was before (error as requested here)

That's true @sorja .

@pengchenglai can we have only one final strategy please ?
I have the impression we go back and forth with this .
Thank you for your understanding

**Comment by pengchenglai** [comment]
@sorja 
Yes, in that case(1), if one value is missing or more values are missing, we do not calculate the sum to see if it matches.

Here is another issue(2) in the subclass, the value can be greater than the parent. In this case, we do not need to calculate the sum, right? We need to verify if the subclass, which has the data, is bigger than the parent or not. If so, then highlight it.

![image](https://github.com/openforis/fra-platform/assets/99216009/e60077f3-abe0-4ea9-a00c-8cfbadae4088)

**Comment by pengchenglai** [comment]
The same needs to be implemented for tables 1d and 2a.

**Comment by pengchenglai** [comment]
> > _I might remember incorrectly, BUT_
> > I think it was requested that when one or more values for sub categories are missing, we do not show the error.
> > I will change it back to what it was before (error as requested here)
> 
> That's true @sorja .
> 
> @pengchenglai can we have only one final strategy please ? I have the impression we go back and forth with this . Thank you for your understanding

@minotogna 
Sure, just first let's make it clear if we are talking about the same issue as what has been requested is 1, which works well. We need to focus on is 2, which same rule does not work for tables 1d and 2a(second table).

**Comment by sorja** [comment]
@pengchenglai Do you recall if we have similar validator somewhere in the platform already?

I think I found an example, this is what we want for given variables, right?

![image](https://github.com/openforis/fra-platform/assets/5508251/c3919652-8ef5-4a2e-863d-0e5069f5f272)

**Comment by pengchenglai** [comment]
> @pengchenglai Do you recall if we have similar validator somewhere in the platform already?
> 
> I think I found an example, this is what we want for given variables, right?
> 
> ![image](https://private-user-images.githubusercontent.com/5508251/317249801-c3919652-8ef5-4a2e-863d-0e5069f5f272.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1NDQ5MzEsIm5iZiI6MTcxMTU0NDYzMSwicGF0aCI6Ii81NTA4MjUxLzMxNzI0OTgwMS1jMzkxOTY1Mi04ZWY1LTRhMmUtODYzZC0wZTUwNjlmNWYyNzIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjdUMTMwMzUxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YWM0ZDI2OWI3ODg4Mjk4MDA1MjdkMTdjNzcwOGI3ZjE0MTk5Zjg0OGZlMzhjYWMyN2E2YzUzMzVkZGU4YWRhYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.wcZ2-hSZ5N_uLIIjimYFrsM-DH13KeEFiLRgwNMqg1U)

@sorja Yes, we have this check already implemented for 3b and 4a.
