### ISSUE TITLE
Introduction link (potential) issue

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#3671]
@minotogna 

**Describe the bug**
Please check the introduction link (suppose having been correctly inserted) of Bonaire, Sint Eustatius and Saba as it redirects to the report itself(see below).

https://fra-data.fao.org/assessments/fra/2025/BES/sections/contactPersons

**To Reproduce**

https://github.com/openforis/fra-platform/assets/99216009/41be0541-6fec-4f1b-ad01-7bb0e05e2c8e

**Comment by sorja** [comment]
@pengchenglai
**this link never worked**

it was incorreclty added in FRA 2020 and it was migrated from there (same incorrect link was migrated to fra 2020 -> 2025)
