### ISSUE TITLE
FRA 2020 report: image display

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#3706]
**Describe the bug**
There is an issue with displaying image(s) for FRA 2020.

**Screenshot**
Example: Morocco table 1b
![image](https://github.com/openforis/fra-platform/assets/99216009/8868af42-c804-49ce-b181-53691dbb8a9f)

**Comment by pengchenglai** [comment]
@minotogna

**Comment by sorja** [comment]
@pengchenglai 
After looking into this I can conclude that there is no such file.
The reason why, is unknown

Marocco has only three files which can be found in links and repository.
Links and repository contains an image file, could it be it?

**Comment by pengchenglai** [comment]
@sorja 

Thanks for the exploration. Talked with Anne and it is this file for the image:
![image](https://github.com/openforis/fra-platform/assets/99216009/ce685cd4-f733-4abd-8ab8-bd7bbae1916a)

**Comment by sorja** [comment]
@pengchenglai  ( cc @minotogna )
I have found the issue, thanks again for reporting and confirming the above.

I have found a few sections and countries with incorrect data, which I will fix.
In case you are curious and want to verify the fix after it's deployed, here are the errornouss countries and sections:

# Fra 2020

| country\_iso | section\_name | name |
| :--- | :--- | :--- |
| RWA | forestCharacteristics | originalData |
| GAB | forestAreaWithinProtectedAreas | originalData |
| GAB | designatedManagementObjective | originalData |
| MAR | forestCharacteristics | dataSources |
| CPV | extentOfForest | generalComments |
| X04 | contactPersons | introductoryText |
| RWA | extentOfForest | originalData |
| RWA | contactPersons | introductoryText |

# Fra 2025

| country\_iso | section\_name | name |
| :--- | :--- | :--- |
| RWA | forestCharacteristics | originalData |
| CPV | forestCharacteristics | originalData |
| CPV | extentOfForest | generalComments |
| RWA | extentOfForest | originalData |
| RWA | contactPersons | introductoryText |
| GAB | forestAreaWithinProtectedAreas | originalData |
| MAR | forestCharacteristics | dataSources |


If you happen to find anything else than what is listed above, please let me know.

Thanks!

**Comment by minotogna** [comment]
> @pengchenglai  ( cc @minotogna )
> 
> I have found the issue, thanks again for reporting and confirming the above.
> 
> 
> 
> I have found a few sections and countries with incorrect data, which I will fix.
> 
> In case you are curious and want to verify the fix after it's deployed, here are the errornouss countries and sections:
> 
> 
> 
> # Fra 2020
> 
> 
> 
> | country\_iso | section\_name | name |
> 
> | :--- | :--- | :--- |
> 
> | RWA | forestCharacteristics | originalData |
> 
> | GAB | forestAreaWithinProtectedAreas | originalData |
> 
> | GAB | designatedManagementObjective | originalData |
> 
> | MAR | forestCharacteristics | dataSources |
> 
> | CPV | extentOfForest | generalComments |
> 
> | X04 | contactPersons | introductoryText |
> 
> | RWA | extentOfForest | originalData |
> 
> | RWA | contactPersons | introductoryText |
> 
> 
> 
> # Fra 2025
> 
> 
> 
> | country\_iso | section\_name | name |
> 
> | :--- | :--- | :--- |
> 
> | RWA | forestCharacteristics | originalData |
> 
> | CPV | forestCharacteristics | originalData |
> 
> | CPV | extentOfForest | generalComments |
> 
> | RWA | extentOfForest | originalData |
> 
> | RWA | contactPersons | introductoryText |
> 
> | GAB | forestAreaWithinProtectedAreas | originalData |
> 
> | MAR | forestCharacteristics | dataSources |
> 
> 
> 
> 
> 
> If you happen to find anything else than what is listed above, please let me know.
> 
> 
> 
> Thanks!

Nice @sorja 
What was the original resin for this ?

**Comment by sorja** [comment]
> > @pengchenglai  ( cc @minotogna )
> > I have found the issue, thanks again for reporting and confirming the above.
> > I have found a few sections and countries with incorrect data, which I will fix.
> > In case you are curious and want to verify the fix after it's deployed, here are the errornouss countries and sections:
> > # Fra 2020
> > | country_iso | section_name | name |
> > | :--- | :--- | :--- |
> > | RWA | forestCharacteristics | originalData |
> > | GAB | forestAreaWithinProtectedAreas | originalData |
> > | GAB | designatedManagementObjective | originalData |
> > | MAR | forestCharacteristics | dataSources |
> > | CPV | extentOfForest | generalComments |
> > | X04 | contactPersons | introductoryText |
> > | RWA | extentOfForest | originalData |
> > | RWA | contactPersons | introductoryText |
> > # Fra 2025
> > | country_iso | section_name | name |
> > | :--- | :--- | :--- |
> > | RWA | forestCharacteristics | originalData |
> > | CPV | forestCharacteristics | originalData |
> > | CPV | extentOfForest | generalComments |
> > | RWA | extentOfForest | originalData |
> > | RWA | contactPersons | introductoryText |
> > | GAB | forestAreaWithinProtectedAreas | originalData |
> > | MAR | forestCharacteristics | dataSources |
> > If you happen to find anything else than what is listed above, please let me know.
> > Thanks!
> 
> Nice @sorja What was the original resin for this ?

**Issue:**
I am not exactly sure where to pinpoint the exact step where it went wrong, but it seems we migrated data from `_legacy` schema to our new cycle based schemas and forgot to migrate the description file urls.
The `fileRepository` url is from the first verion of `FRA`, later on we used `api/file/assessment`.
This is also the reason why we have errors in both cycles, as we migrated the 2020 data to 2025.

**Resolution:**
On quick glance, it seems we are in luck. The file names are 1:1 to what is found by `url/:id` from `_legacy.repositry`.
Replacing the broken url with our new cycle based repository, results in working image:

![image](https://github.com/openforis/fra-platform/assets/5508251/dce363d8-8714-45a3-a5a2-c10b118a682f)
_Example: Replace broken url with working (correct file) url in db._

**Comment by minotogna** [comment]
Thanks @sorja . It makes sense . Good it is now fixed

**Comment by pengchenglai** [comment]
@sorja 

Thank youuu!
