### ISSUE TITLE
Urgent issue - FRA 2025: print report - hidden text

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#3707]
@minotogna @sorja @yaguzmang 
**Describe the bug**
If the table is really big or the text is long, the content is likely to be hidden when printing out the reports. And sometimes, the table is corrupted.
**To Reproduce** (example China/ Morocco)
1. Click the print tab
2. Using ctrl +P to print the report
3. save as a pdf and open the report
5. See error

**Expected behavior**
The table should be able to adjust its size to fit the page and show the full text.

**Screenshots**
Content hidden:
![image](https://github.com/openforis/fra-platform/assets/99216009/ab7ac394-47c2-4306-b35e-c2ec1c77f962)
![image](https://github.com/openforis/fra-platform/assets/99216009/8a759391-7bbd-4199-ae30-c68583f7137e)
Table corruption:
![image](https://github.com/openforis/fra-platform/assets/99216009/8819ace0-ef16-4f48-8c48-4cb70204a6c9)

**Comment by minotogna** [comment]
@pengchenglai we print at 70% resolution .
Official pdf print will come later , we cannot control how users print from their browsers, otherwise it's madness to control all cases

**Comment by pengchenglai** [comment]
@minotogna 
Great, thank you plz prioritize this as most countries are under the final validation process and it is essential that we send them a copy finalized report.
