### ISSUE TITLE
Link issue

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#3728]
@minotogna 

**Describe the bug**
Plz investigate and (try to) fix the issues of invalid links, which always redirect to the report itself, from the FRA 2020 country reports. Not sure if it is because something went wrong during the data migration.

**To Reproduce**
1. Click the link: https://fra-data.fao.org/assessments/fra/2020/BES/sections/contactPersons
2. click [1] as showed in the image below:
![image](https://github.com/openforis/fra-platform/assets/99216009/a8baab75-50eb-4eaf-9e72-f141790b4f95)

**Comment by sorja** [comment]
@pengchenglai Thanks for reporting this

On my first look, it might be that our previous text editor supported adding **footnotes** 
https://www.drupal.org/docs/8/modules/footnotes/adding-footnotes-to-content-via-the-ckeditor-toolbar

On quick check, our new text editor found in the Platform doesn't support this.

I will investigate further

cc @minotogna 


Edit:

I have found a solution to enable the footnote in-page link.


https://github.com/openforis/fra-platform/assets/5508251/483fd6b2-5f54-40d1-89bd-8bf45d5000a0




Here is a list of countries and sections that had used the footnote feature:

| country\_iso | name |
| :--- | :--- |
| IDN | originalData |
| IDN | originalData |
| IDN | originalData |
| IDN | originalData |
| IDN | originalData |
| IDN | originalData |
| DEU | nationalClassificationAndDefinitions |
| DEU | reclassification |
| RWA | originalData |
| MSR | introductoryText |
| MAR | introductoryText |
| MAR | dataSources |
| MRT | originalData |
| MAR | dataSources |
| MAR | estimationAndForecasting |
| DEU | nationalClassificationAndDefinitions |
| MAR | dataSources |
| ZMB | introductoryText |
| KHM | originalData |
| KHM | originalData |
| SXM | introductoryText |
| BES | introductoryText |
| COL | introductoryText |
| ZAF | introductoryText |
| RWA | originalData |
| CUW | introductoryText |
| AIA | introductoryText |
| NRU | introductoryText |
| BHR | introductoryText |
| BMU | introductoryText |
| IMN | introductoryText |
| LBY | introductoryText |
| LIE | introductoryText |
| ABW | introductoryText |
| TKL | introductoryText |
| LSO | introductoryText |
| RWA | introductoryText |

**Comment by pengchenglai** [comment]
@sorja 
 
I see these links serving as footnotes instead of directing users using external links to the stored location of the publication.

So the fix will also apply to FRA 2025, where some footnotes may be inherited from FRA 2020.
