### ISSUE TITLE
Image display issue

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#3742]
@minotogna @sorja 

**Describe the bug**
One cannot see the image but the person such as the admin who has permission to access the country could see it.

**To Reproduce** (Morroco)
https://fra-data.fao.org/assessments/fra/2020/MAR/sections/forestCharacteristics

**Expected behavior**
It can show the image properly with or without users logged in and to those who do (not) have permission to access.

**Screenshots**
Log in:
![image](https://github.com/openforis/fra-platform/assets/99216009/40ccb61d-5407-4961-8de9-f03d5b3e4c28)

Log out:
![image](https://github.com/openforis/fra-platform/assets/99216009/bf17c0b6-6943-40c9-b489-a7613ffe1fc9)

**Comment by minotogna** [comment]
@sorja that's most likely due to missing repository item permission . the cycle is 2020 and therefore anyone should be able to see the repository item image
