### ISSUE TITLE
GEO: Calculate aligned tree cover area percentage of selected layers

### ISSUE THREAD

**Issue by yaguzmang** [openforis/fra-platform#3753]
From @pengchenglai: 
>is there any possibility that we have the feature in the geo-spatial tool that allows users to see the aligned tree cover area(percentage) between different (selected) sources, which may also include user-uploaded GEE ID?

~~TODO:~~
- [ ] ~~Check how we currently calculate custom agreement areas.~~
- [ ] ~~Implement a similar logic to calculate the aligned tree cover area percentage of selected layers.~~

**Comment by yaguzmang** [comment]
@minotogna Just had a call with Pengcheng, and this functionality is covered by the ESTIMATE CUSTOM AGREEMENT AREA button, so there is no need to implement an extra feature. We can close this issue.

<img src="https://github.com/openforis/fra-platform/assets/41337901/79c1571c-6fa7-4319-ae0c-5bc12c17b754" alt="drawing" width="300"/>

**Comment by pengchenglai** [comment]
@yaguzmang @minotogna 

Yes, it does work, as demonstrated in the call, but when I try it, there is an error:
![image](https://github.com/openforis/fra-platform/assets/99216009/f31e2692-d2ee-456f-a645-5890134d3f7e)

**Comment by yaguzmang** [comment]
@pengchenglai I will look into it

**Comment by yaguzmang** [comment]
I was able to reproduce in the review platform (with another country):


![Image](https://github.com/openforis/fra-platform/assets/41337901/a12d2920-06f4-47d8-b2f3-9511dbd39bb8)


It seems to be related to the allowed computations that can be done at the same time in GEE. After waiting for a bit, I made the request again and got back the result:

![Image](https://github.com/openforis/fra-platform/assets/41337901/225c9671-e9a1-4969-9956-d8811373d03b)

**Comment by pengchenglai** [comment]
It might work for a country with a relatively smaller land area, but for medium-sized and larger countries, the same approach does not seem to work and might exceed the computational power regardless of the waiting time.
![image](https://github.com/openforis/fra-platform/assets/99216009/d8cf3029-22e9-422e-9a4e-6d9d2a8f61b4)

**Comment by pengchenglai** [comment]
@yaguzmang

**Comment by minotogna** [comment]
> It might work for a country with a relatively smaller land area, but for medium-sized and larger countries, the same approach does not seem to work and might exceed the computational power regardless of the waiting time.
> 
> ![image](https://github.com/openforis/fra-platform/assets/99216009/d8cf3029-22e9-422e-9a4e-6d9d2a8f61b4)
> 
> 

@pengchenglai @yaguzmang 
We need to talk on how to fix this . Maybe some big machine with cloud computing , but must be done outside the platform ?

**Comment by yaguzmang** [comment]
> We need to talk on how to fix this . Maybe some big machine with cloud computing , but must be done outside the platform ?

Would revising the way we calculate these areas be an option? From the [documentation](https://developers.google.com/earth-engine/guides/debugging), if we adjust scales we could improve the speed:
![image](https://github.com/openforis/fra-platform/assets/41337901/ad89421f-41a1-4064-80ac-9c03626ce48c)

> "This silly example is just for demonstration. The purpose of this error is to ask you whether you really want to reduce 80300348117 (that's 80 billion) pixels." 

Noting that changing the scale would affect accuracy.

**Comment by pengchenglai** [comment]
@yaguzmang 

Possible to try removing the validation of waiting time? Maybe it can help,  like below:

var area1 = ee.Number(calculateArea(agreement6to9)).format('%,.2f').**evaluate**(function (result) {
  print('Agreement 6+ layers', result + ' ha')});

**Comment by minotogna** [comment]
@yaguzmang @pengchenglai can I close this issue ?

**Comment by yaguzmang** [comment]
@pengchenglai Unfortunately you last suggestion wouldn't fix the issue for big countries. The only options I see would be to have a cloud computing machine as Mino suggested, or reduce the accuracy significantly.

**Comment by pengchenglai** [comment]
@yaguzmang I see the situation: if using cloud computing is not feasible, then we could consider reducing the resolution to the extent that a medium-sized country(in terms of land area), such as the DRC, could be computed to get a rough estimate.

**Comment by minotogna** [comment]
Hi @yaguzmang @pengchenglai 
I'm closing this issue. I don't see a way out at the moment.
