### ISSUE TITLE
Table 7 data entry 

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#3789]
**Is your feature request related to a problem? Please describe.**
It is hard to read the text when users enter texts for the cells.
![image](https://github.com/openforis/fra-platform/assets/99216009/765ca6fa-92b7-449c-a40a-77b074285519)

**Describe the solution you'd like**
Enable text wrapping so that when users write, long texts are automatically separated into several lines while they are still editing.

**Comment by pengchenglai** [comment]
@minotogna

**Comment by pengchenglai** [comment]
Depending on the resolution, reading even a long word in the **Key Species** column may not be possible.

**Comment by minotogna** [comment]
@pengchenglai issue resolved .

**Comment by pengchenglai** [comment]
@minotogna 

Thank you, one more question: Has it not been deployed for the review yet, as it seems the words are not being separated into several lines when writing a long text?
![image](https://github.com/user-attachments/assets/5f267bca-f774-4c6d-9aba-e38a095c777a)

**Comment by minotogna** [comment]
> @minotogna 
> 
> 
> 
> Thank you, one more question: Has it not been deployed for the review yet, as it seems the words are not being separated into several lines when writing a long text?
> 
> ![image](https://github.com/user-attachments/assets/5f267bca-f774-4c6d-9aba-e38a095c777a)
> 
> 

@pengchenglai is that what you wanted ?
The issue was about the size, that's what I fixed .It wasn't specified the input should be multiline .
Please , create a new issue and please specify what the exact request is .
Thank you

**Comment by minotogna** [comment]
@pengchenglai i have simply misunderstood the issue . Sorry .

**Comment by minotogna** [comment]
@pengchenglai it is now fixed.

**Comment by pengchenglai** [comment]
@minotogna 

Thank you. Maybe the width of the **NWFP category** column could be slightly wider, as some of the text has been hidden, as shown below.
![image](https://github.com/user-attachments/assets/9ad884b3-fd20-4172-a59b-d77e119efe8b)


Of course, it is related to the resolution of the page, and the above page is captured at default resolution(100%).

**Comment by minotogna** [comment]
> @minotogna 
> 
> 
> 
> Thank you. Maybe the width of the **NWFP category** column could be slightly wider, as some of the text has been hidden, as shown below.
> 
> ![image](https://github.com/user-attachments/assets/9ad884b3-fd20-4172-a59b-d77e119efe8b)
> 
> 
> 
> 
> 
> Of course, it is related to the resolution of the page, and the above page is captured at default resolution(100%).

@pengchenglai thats tricky with current table implementation. Plus this is an unrealistic case . 

We'll see what we can do when we will refactor the data table component (it is in the pipeline , there will also be horizontal scroll )

If in the meantime you see problems with production data , let me know .

Does this work for you?

**Comment by pengchenglai** [comment]
@minotogna 

Sounds good, thanks!
