### ISSUE TITLE
Admin Manage collaborators page - csv download

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#3798]
@minotogna 

**Describe the bug**
The CSV download of all platform user info only contains the information for the first page.

**To Reproduce**
1. Go to the Admin Manage Collaborators page 
2. Click on 'CSV'
3. Open the CSV file

**Expected behavior**
It should include info of all platform users,

**Screenshots**
![image](https://github.com/openforis/fra-platform/assets/99216009/95971a5d-a105-4e87-ac34-8acadd0e6e14)

**Comment by minotogna** [comment]
- [x] Admin->Manage Collaborators: Refactor using common Table components/api

**Comment by minotogna** [comment]
- [x] Create generic CSV server side download

https://github.com/vitaly-t/pg-promise/wiki/Learn-by-Example#streaming
