### ISSUE TITLE
Low priority - contact table - enhancement

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#3800]
@minotogna 

**Is your feature request related to a problem? Please describe.**
Sometimes, countries like Austria have already provided the contact table in the introduction, making the contact table generated by the platform unnecessary.

**Describe the solution you'd like**
Make the contact table section below(includes the title) an optional feature for the admin (by default, we have this section, and admin could hide it if necessary)
![image](https://github.com/openforis/fra-platform/assets/99216009/59f9b4eb-87b4-4d6a-a115-8257239b2c55)

**Comment by minotogna** [comment]
@pengchenglai the ideal would be to have only one source of data , I.e. only one place where the contacts are generated .
In my opinion this task is a hack that will lead to inconsistency of the data .
Are you really sure we want this ?

**Comment by minotogna** [comment]
@pengchenglai can I close this issue ?

**Comment by pengchenglai** [comment]
Hi @minotogna, have you made this option available? For a few countries, such as Austria(https://fra-data.fao.org/assessments/fra/2025/AUT/sections/contactPersons), the contact info has been manually entered by the NC in the intro. 

For this reason, it would be great to have this feature available for admins only. This has been requested by Örjan.

**Comment by minotogna** [comment]
> Hi @minotogna, have you made this option available? For a few countries, such as Austria(https://fra-data.fao.org/assessments/fra/2025/AUT/sections/contactPersons), the contact info has been manually entered by the NC in the intro. 
> 
> 
> 
> For this reason, it would be great to have this feature available for admins only. This has been requested by Örjan.
> 
> 
> 
> 

No @pengchenglai . See my previous comments please .
I propose to have only one place to have the contacts . Not two places

**Comment by pengchenglai** [comment]
I understand the situation, @minotogna. However, we cannot change (remove) the content(contact table) entered by the NC and change the reports that have been approved. In the case of Austria, the manually entered contact table has more people than the system-generated contact table.

To keep the contact table in one place for Austria, I am afraid that the preferred solution for this reporting cycle is to **_enable admins to hide the system-generated contact table_**(thus, it should be implemented as a feature that applies to other reports if they encounter this situation) and **_keep the contact table that users manually entered_** as it gets approved already, more people and more detailed info.

**Comment by minotogna** [comment]
> I understand the situation, @minotogna. However, we cannot change (remove) the content(contact table) entered by the NC and change the reports that have been approved. In the case of Austria, the manually entered contact table has more people than the system-generated contact table.
> 
> To keep the contact table in one place for Austria, I am afraid that the preferred solution for this reporting cycle is to **_enable admins to hide the system-generated contact table_**(thus, it should be implemented as a feature that applies to other reports if they encounter this situation) and **_keep the contact table that users manually entered_** as it gets approved already, more people and more detailed info.

ok @pengchenglai I understand. I will implement this.

**Comment by pengchenglai** [comment]
@minotogna 

Thank you very much! Would be more than great if the function would also hide (start at) **Report preparation and contact persons**.
![image](https://github.com/user-attachments/assets/382acf9e-67aa-4980-be1e-a149bdae201e)

**Comment by minotogna** [comment]
> @minotogna
> 
> Thank you very much! Would be more than great if the function would also hide (start at) **Report preparation and contact persons**. ![image](https://private-user-images.githubusercontent.com/99216009/352501634-382acf9e-67aa-4980-be1e-a149bdae201e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5OTE5MDgsIm5iZiI6MTcyMTk5MTYwOCwicGF0aCI6Ii85OTIxNjAwOS8zNTI1MDE2MzQtMzgyYWNmOWUtNjdhYS00OTgwLWJlMWUtYTE0OWJkYWUyMDFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI2VDExMDAwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUzNzU2MjQwMjM5ZTViYTc1YmFmMzQzNGRlMGM4Yzk4YjBiMGM1ZDA0NWIwODU2MTMwOWEwNmM2M2EyOWRmMWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.R5Qyva4VnfHtHVfoFnMVwfscWPEm0T4pk-_8r5cHUYM)

@pengchenglai If there's no Report preparations and contact person, but only Show button (when it's hidden), will he understand what;s to show?

That label will be completely hidden in the print view.

**Comment by minotogna** [comment]
Also, @pengchenglai non admin users, when it's hidden, won't see that at all.
