### ISSUE TITLE
FRA 2020 Sierra Leone

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#3818]
@minotogna

**Describe the bug**
Data(**Other land** & **Total land area** ) does not show up on the main page.

**To Reproduce**
https://fra-data.fao.org/assessments/fra/2020/SLE/sections/extentOfForest

**Screenshots**
![image](https://github.com/openforis/fra-platform/assets/99216009/65d3dc39-6ee4-4590-b6e7-39ceee8f384f)

 1976 NDP:
![image](https://github.com/openforis/fra-platform/assets/99216009/b4bb2b53-d63b-4bc0-b1b8-fb9fed94ee5d)

**Comment by sorja** [comment]
@pengchenglai Could you be so kind as to check whether some other country that has an NDP before 1980 has the same problem?

Thank you

**Comment by pengchenglai** [comment]
> @pengchenglai Could you be so kind as to check whether some other country that has an NDP before 1980 has the same problem?
> 
> Thank you

@sorja 

Sure, it would be great if you could share the list of countries with a NDP before 1980. I lost track of the countries after checking more than twenties.
