### ISSUE TITLE
BulkDownload:getContentVariables->Get metadata from existing controller

### ISSUE THREAD

**Issue by minotogna** [openforis/fra-platform#3967]
BulkDownload:getContentVariables->Get metadata from existing controller
@sorja we can address this in a separate issue ?

_Originally posted by @minotogna in https://github.com/openforis/fra-platform/pull/3965#discussion_r1775502033_

**Comment by sorja** [comment]
I would like to use Redis to fetch all header rows, but I noticed we persist only rows with a `variableName`, which excludes all header rows.
I update Redis to include also the headers

Let me know in case -

@minotogna
