### ISSUE TITLE
Heroku prod:: migration public run fails

### ISSUE THREAD

**Issue by minotogna** [openforis/fra-platform#3968]
```
24-09-25T18:50:49.524293+00:00 app[web.4]: 
2024-09-25T18:50:49.528480+00:00 app[web.4]: sh: 1: ts-node: not found
2024-09-25T18:50:49.536493+00:00 app[web.4]: ERROR: "migration-public:run" exited with 127.
```

**Comment by sorja** [comment]
Opening the discussion:
The issue here is that the migrations are written in `ts` and we try to run them uncompiled (to js).
Our package.json lists `ts-node`, `typescript` etc as `devDependencies`.
And our heroku build pack supports only Node (javascript)

**Comment by minotogna** [comment]
why review instance wasn't failing ?

**Comment by sorja** [comment]
> why review instance wasn't failing ?

The only difference I found from build logs is that in `production` environment `NPM_CONFIG_PRODUCTION=true` and in `review` environment `NPM_CONFIG_PRODUCTION=false`

```
PRODUCTION:

-----> Creating runtime environment
       
       NPM_CONFIG_PRODUCTION=true
       NPM_CONFIG_LOGLEVEL=error
       USE_YARN_CACHE=true
       NODE_VERBOSE=false
       NODE_ENV=production
       NODE_MODULES_CACHE=true
```

```
REVIEW
-----> Creating runtime environment
       
       NPM_CONFIG_PRODUCTION=false
       NPM_CONFIG_LOGLEVEL=error
       USE_YARN_CACHE=true
       NODE_VERBOSE=false
       NODE_ENV=production
       NODE_MODULES_CACHE=true
```

https://devcenter.heroku.com/articles/nodejs-support#using-npm-install

**Comment by minotogna** [comment]
Nice @sorja 
So by putting to false that env , we should be able to make it work ? 
in case , can u open a draft pr (with this issue number) ? I will test the deploy afterwards

**Comment by sorja** [comment]
We can do that, but we should make sure it does not have any side effects
I will open a draft pr anyway

**Comment by sorja** [comment]
> We can do that, but we should make sure it does not have any side effects I will open a draft pr anyway

It seems that is simply an environmental variable in Heroku:

![image](https://github.com/user-attachments/assets/27e362b2-9e2e-4a9b-bc91-b8d6fcb49795)


Feel free to try it out @minotogna

**Comment by minotogna** [comment]
> > We can do that, but we should make sure it does not have any side effects I will open a draft pr anyway
> 
> 
> 
> It seems that is simply an environmental variable in Heroku:
> 
> 
> 
> ![image](https://github.com/user-attachments/assets/27e362b2-9e2e-4a9b-bc91-b8d6fcb49795)
> 
> 
> 
> 
> 
> Feel free to try it out @minotogna 

Yes @sorja I understood that from your previous comment . We must , however, enable again the run of public migrations . That's why I suggested to open a draft pr . Does it make sense?

**Comment by sorja** [comment]
> > > We can do that, but we should make sure it does not have any side effects I will open a draft pr anyway
> > 
> > 
> > It seems that is simply an environmental variable in Heroku:
> > ![image](https://private-user-images.githubusercontent.com/5508251/372828319-27e362b2-9e2e-4a9b-bc91-b8d6fcb49795.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc4NjcyNDYsIm5iZiI6MTcyNzg2Njk0NiwicGF0aCI6Ii81NTA4MjUxLzM3MjgyODMxOS0yN2UzNjJiMi05ZTJlLTRhOWItYmM5MS1iOGQ2ZmNiNDk3OTUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMDJUMTEwMjI2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjE1ZjMwODZhZDQ1YThkOTg1OGIzYzhiMGY5YjMxY2NmNjVkMGI1YjM2ODRjYTJjOGFkMTVhZWUzNzA4MGVkNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.FfZT7KgvT_aDqXDl_0w9rrUhDyqOFH4LUJbY2Xg0GLU)
> > Feel free to try it out @minotogna
> 
> Yes @sorja I understood that from your previous comment . We must , however, enable again the run of public migrations . That's why I suggested to open a draft pr . Does it make sense?

Sure, I will open draft for public migrations on start

**Comment by sorja** [comment]
Side thought:
If we enable ts on prod, then, do we need to compile the server to js?

**Comment by minotogna** [comment]
> Side thought: If we enable ts on prod, then, do we need to compile the server to js?

performances and memory usage are better in node compared to ts-node.
