### ISSUE TITLE
High priority - cannot access country data for viewer 

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#4023]
@minotogna 

**Describe the bug**
As the viewer, one cannot see any data for the access-granted country (see video below). Seems fine for the reviewers to see the country data, but not sure for collaborator or NC, plz check the error message below.

**To Reproduce**
[49b9f5ed-0320-44b4-b8bd-675e148bf77b.webm](https://github.com/user-attachments/assets/f1acd523-5c93-494f-a90e-9334cbeb8e8a)

**Screenshots**
![image](https://github.com/user-attachments/assets/78f8fb94-75a4-49d6-b216-084c5fb80d81)

**Comment by pengchenglai** [comment]
@sorja @minotogna 

Is it possible to deploy the fix asap, guys? 

One NC has reported a similar case today, as shown below:
![image](https://github.com/user-attachments/assets/cbd756d9-14d7-4bcd-9604-59dda5aa0741)

**Comment by minotogna** [comment]
> @sorja @minotogna 
> 
> 
> 
> Is it possible to deploy the fix asap, guys? 
> 
> 
> 
> One NC has reported a similar case today, as shown below:
> 
> ![image](https://github.com/user-attachments/assets/cbd756d9-14d7-4bcd-9604-59dda5aa0741)
> 
> 
> 
> 

It has been deployed . Yesterday @sorja fixed it

**Comment by pengchenglai** [comment]
@minotogna 
Great to know, I will let the NC try again.

**Comment by pengchenglai** [comment]
@minotogna @sorja 
![image](https://github.com/user-attachments/assets/d2e6fb0e-d840-4878-a31b-4bced74881aa)

The issue is still there. Could you plz have a look at your earliest convenience?

**Comment by pengchenglai** [comment]
https://fra-data.fao.org/assessments/fra/2025/URY/sections/growingStockComposition/

Access as a viewer.
