### ISSUE TITLE
Split User Role / Invitation

### ISSUE THREAD

**Issue by minotogna** [openforis/fra-platform#4032]
Where necessary, add relevant comments in the user invitation flow

- [x] Split db, types and datamigration
- [x] Country collaborators page: split collaborators and invitations tables (2 tables, add plus button on top of invitations table)
- [x] Update country status change confirm pop up
- [x] Remove deprecated component: `componentsUserList`
- [x] Verify user invitation process (check API/Controller/Repository)
- [x] Verify admin invitation page
- [x] View
- [x] Verify admin collaborators page (invitation are also included in the users list)
- [x] Verify introduction contact user list
- [x] Country summary materialized : Invitations count
- [x] Country Home Page update to single list
- [x] Verify edit user (and user role props) works
  - [x] Test editing collaborator with admin
  - [x] Test inviting new collaborator, accepting invitation and update information after redirect, after `Edit profile`
- [x] Update UI as in given layout (Slack)
- [x] Admin add or remove multiple roles
- [ ] Add user download buttons (country home / collaborators) (separate PR)
------

- [ ] Setup E2E testing
  - [ ] Init DB:
    - [ ] Controller OUTPUT: Metadata and data for all countries 2020 and 2025
    - [ ] Controller INPUT

- [ ] Test cases
  - [ ] Test: user login (admin)
  - [ ] Test: User invite (admin invite all roles, all combinations) (Verify working from admin page invitations)
  - [ ] Test: User accept invitation with login

------

**Comment by sorja** [comment]
Let's update:

-  Country collaborators:
    - Single list with mixed users and invitations (pending users)
- Admin manage collaborators

New view:

country_user_summary

columns:

name
surname
fullname?:
country_iso
role: the role for the given country_iso | nullable
invitation: the invitation for given country (admin page> text disabled -> something noting: pending invitation)

either is active

Type:

```typescript
type CounrtyUserSummary = {

}
```

Server
```

CountryUserRepository.{}

```
