### ISSUE TITLE
Review comments unavailable on latest cycle

### ISSUE THREAD

**Issue by minotogna** [openforis/fra-platform#4092]
Data table doesn't show review comments button , because Authorizer.canViewReview return false.
Logged in as admin 
https://fra-data.review.fao.org/assessments/fra/latest/FIN/sections/growingStockComposition
![Image](https://github.com/user-attachments/assets/c6e57756-5bf2-453c-bf88-de38babf39e2)

Even on Prod it doesn't show 
https://fra-data.fao.org/assessments/fra/2025/FIN/sections/growingStockComposition
![Image](https://github.com/user-attachments/assets/10cfe20a-539e-4be1-970b-51be6e83ac23)

**Comment by sorja** [comment]
@minotogna 


After testing this locally, it seems that it's working as expected by these rules:


```
  const allowedStatuses = [AssessmentStatus.review, AssessmentStatus.editing]
  const countryStatus = Object.fromEntries(
    [
      RoleName.ADMINISTRATOR,
      RoleName.REVIEWER,
      RoleName.NATIONAL_CORRESPONDENT,
      RoleName.ALTERNATE_NATIONAL_CORRESPONDENT,
      RoleName.COLLABORATOR,
    ].map((role) => [role, allowedStatuses])
  )
```

Should we change these rules, eg admin can view in all country statuses?

In the screenshots I see `Not Started` and `Accepted` which are outside of this rule `allowedStatuses`

Let me know

**Comment by minotogna** [comment]
@sorja in edit mode, all users with write access can see and post review comments if the edit lock is opened.
edit mode, includes even not started. 

in accepted mode only admin can see the review comments, but only when edit lock is opened.

does this answer ?
