### ISSUE TITLE
Refactor Atlantis countries usage

### ISSUE THREAD

**Issue by minotogna** [openforis/fra-platform#4156]
- Atlantis countries must be hidden only in published public view cycles .
- Not available in published public view cycles
- Remove env variable FRA_ATLANTIS_ALLOWED (locally, env template, and heroku after deploy)
- make sure fra all cycles have country Atlantis views 
- in src/server/repository/public/user/getOne.ts
  - remove allowedCountriesOnly prop (it is always true because it never gets invoked with allowedCountriesOnly=false)
  - line 65: get rid of  usersRoleSubquery

e.g. fra 2020 should hide them.

- check db fetch .
- check env

**Comment by sorja** [comment]
@minotogna We can also explore the option to delete Atlantis countries completely from published cycles (discussion)

I will implement: if cycle.ispublished = no antlantis countries

Let me know
