### ISSUE TITLE
Production branch release

### ISSUE THREAD

**Issue by minotogna** [openforis/fra-platform#472]
Create a test app on Heroku and test with another branch that the production deploy work

**Comment by sorja** [comment]
Currently done for 'test' branch and fra-platform-test on heroku. Works on commit => deploy.
I don't have sufficient permissions on Google to update the token for auth for login.

**Comment by sorja** [comment]
Another note: There is/was some issue with migrations. 
`2020-09-09T09:50:27.926721+00:00 app[web.1]: (node:23) UnhandledPromiseRejectionWarning: error: relation "user_sessions" does not exist`

This occurs on clean instance of Heroku.
It was fixed by commit `80713972`.
