### ISSUE TITLE
Navigation Scroll

### ISSUE THREAD

**Issue by sorja** [openforis/fra-platform#510]
Unable to reach last parts of navigations in some cases

![image](https://user-images.githubusercontent.com/5508251/92207459-e782d080-ee91-11ea-8a65-888bdd0bb1e0.png)

**Comment by apkretov** [comment]
At my notebook screen, I cannot access two more tables in section 6. There are two more tables below 6.10a one: 6.10b & 6.10c.

**Comment by sorja** [comment]
Resolved
