### ISSUE TITLE
Emails app link

### ISSUE THREAD

**Issue by minotogna** [openforis/fra-platform#528]
Verify (and fix if needed) that links in emails are correct: link fra-data.fao.org and fra-data.review.fao.org in emails link

- [x] assessmentNotifyUsers
- [x] resetPassword
- [x] userInvite

@AnssiSamuli

**Comment by sorja** [comment]
I suggest testing this by changing hosts file;
ex.
example.com => localhost

Not 100% sure this works, but worth trying

**Comment by rfontanarosa** [comment]
url is always process.env.APP_URI

assessmentNotifyUsers
```
  const link = `${url}${ClientRoutes.Assessment.Cycle.Country.Landing.getLink({
    assessmentName,
    countryIso,
    cycleName,
  })}`
```

resetPassword
```
  const link = `${url}${ClientRoutes.Assessment.Cycle.Login.ResetPassword.getLink({ assessmentName, cycleName })}${
    userResetPassword.uuid ? `?resetPasswordUuid=${userResetPassword.uuid}` : ''
  }`
```

userInvite/sendInvitationEmail
```
  const link = `${url}${ClientRoutes.Assessment.Cycle.Login.Invitation.getLink({ assessmentName, cycleName })}${
    role.invitationUuid ? `?invitationUuid=${role.invitationUuid}` : ''
  }`
```
