### ISSUE TITLE
Migrate to webpack 5  and webpack-cli 4

### ISSUE THREAD

**Issue by minotogna** [openforis/fra-platform#559]
webpack-web-server is included in web pack cli 4 and current setting won't work.

the command to run should be webpack serve

check here:
https://github.com/webpack/webpack-dev-server/issues/2759

**Comment by sorja** [comment]
This change breaks most of the plugins we are using (ex. Google Fonts)

```
Automatic polyfills for native Node.js modules were removed
- node.Buffer removed
- node.console removed
- node.process removed
- node.* (Node.js native module) removed
```

There is also mentioned on the site:
> So today (2020-10-10) webpack 5.0.0 is released, but this doesn't mean it's done, bugfree or even feature-complete

**Comment by minotogna** [comment]
strange. have you checked this: https://webpack.js.org/migrate/5/ ?

**Comment by sorja** [comment]
Yes, but if we migrate, our third party libs wont work (the webpack upgrade itself seems to have worked)
