### ISSUE TITLE
PanEuropean: Add Forest Europe region

### ISSUE THREAD

**Issue by minotogna** [openforis/fra-platform#592]
Pan European countries must be shown in country selector when accessing Pan European assessment 

- [x] Insert in db new region Forest Europe: FE (and assign to them countries that have currently the pan_european flag)
- [x] remove from country table column pan_euroepan 
- [x] In country selector, show region FE (Forest Europe) and FE country

**Comment by sorja** [comment]
Missing translation for {fr,es,ru}:
Forest Europe
