### ISSUE TITLE
CountrySelection: Group by user role

### ISSUE THREAD

**Issue by minotogna** [openforis/fra-platform#594]
- [x] FRA Country selection doesn't use countries in store, therefore when switching language, countries are not sorted.
Use countries in store

- [x] Country selection dropdown must be updated as follow:
```
Global
____________
...Regions
____________
NATIONAL CORRESPONDANT
Country 1 
Country 2
____________
REVIEWER
Country 3 
Country 4
____________
.... All other countries user has no role for
```

- [x] Add column assessment to user_country_role table with value fra2020

- [x] Update store
  - Do not store user role under country/countries 
  - Assoc roles directly to user object (when fetched from server)
```
{
 role: {
  fra2020: {
    REVIEWER:[iso1,iso2]
  }
 }
}
```

**Comment by sorja** [comment]
We have currently 2 country lists:
One list contains all (app.countries, useCountries)
Second one contains all user countries, with role information, this is under country.countries.{role}

Should we create another useCountries -style hook? or just sort them in place with similar `useEffect...[language]`
