### ISSUE TITLE
useEffect for countrylist

### ISSUE THREAD

**Issue by sorja** [openforis/fra-platform#602]
useOnUpdate doesn't work correctly

**Comment by minotogna** [comment]
can you provide a test case?

**Comment by sorja** [comment]
Test case:
- Open country or region list
- Note order
- Change language
- Open country or region list
- Note order is incorrect

**Comment by minotogna** [comment]
> Test case:
> 
> * Open country or region list
> * Note order
> * Change language
> * Open country or region list
> * Note order is incorrect

If you refer to CountrySelection in the Header, the issue is already opened. 
That component doesn't use the store countries or regions. or which country or region list are you mentioning?
